### ISSUE TITLE
Automatic cherry pick commits to active releases

### ISSUE THREAD

**Issue by luncj** [kubernetes-sigs/cloud-provider-azure#1018]
#### What would you like to be added:

- `hack/cherry-pick.sh <pr> <target-branch>`: checkout a new branch based on `<target-branch>`, then cherry-pick the commits from specified `<pr>`, and create a GitHub PR.

ref:
- https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh

#### Why is this needed:

https://github.com/kubernetes/kubernetes/issues/10730#issue-93131739

**Comment by feiskyer** [comment]
I think we could add a script for cherry-picking, but automatically cherry-pick may be hard as there are high chances of conflicts in different branches.

Could we add a cherry-pick-pull.sh script?

**Comment by luncj** [comment]
> I think we could add a script for cherry-picking, but automatically cherry-pick may be hard as there are high chances of conflicts in different branches.

Agreed. It's inevitable that we need to resolve the conflicts manually. The `create new branch` / `get commits from PR` / `try apply commits if no conflict occurs` / `create PR` parts could be automatic anyway.

**Comment by luncj** [comment]
https://prow.k8s.io/command-help#cherrypick

**Comment by luncj** [comment]
closed via https://github.com/kubernetes/test-infra/pull/24920
