### ISSUE TITLE
AKS standard vm types

### ISSUE THREAD

**Issue by anjmao** [kubernetes-sigs/cloud-provider-azure#1033]
Is it possible to configure AKS control plane to work with standalone nodes which are not part of vmss or node pools? Or should I just install https://github.com/kubernetes-sigs/cloud-provider-azure with vmType=standard and have two competing cloud-controller-managers?

I know how to join standalone nodes, but load balancers are not working. Service controller validates if node is part of vmss. I tried to add node to availability set but it looks that this is not supported due to https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c2bbb9638d3f3b8cdafdfa7289b35175da37c851/pkg/provider/azure.go#L495

There is similar request for aks https://github.com/Azure/AKS/issues/2712 to add karpenter which also requires standalone nodes.

**Comment by anjmao** [comment]
Gonna try scale set flexible mode https://docs.microsoft.com/en-us/azure/virtual-machines/flexible-virtual-machine-scale-sets to create one scaling set and attach all custom vms to it.

**Comment by feiskyer** [comment]
sorry, this is not supported as cloud provider azure is part of AKS control plane. If you want to manage the cloud provider azure yourself, [aks-engine](https://github.com/Azure/aks-engine), [capz](https://github.com/kubernetes-sigs/cluster-api-provider-azure) or other provisioning tools supporting Azure could be used.
