### ISSUE TITLE
Add health check for controllers

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#1071]
#### What would you like to be added:

We need to add health check for all controllers to gain insight if some of them are in failed state.
Example: https://github.com/kubernetes/cloud-provider/blob/ffb14a0934a04d96f6f92a9c801140193ec87bbf/app/controllermanager.go#L289-L303

#### Why is this needed:

There is a chance that the service controller is not working porperly ([test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1070/pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb/1486488608226414592), [cloud controller manager log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1070/pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb/1486488608226414592/artifacts/k8s-master-21859912-0/cloud-controller-manager-k8s-master-21859912-0_kube-system_cloud-controller-manager-ce4270a5f72e9fc160320eeccc2e3abf56e7706e5f60eb2a100db763a093c744.log)), and we do not know the reason. If we have health checks set on each controllers, we will get more context about the failures.

**Comment by lzhecheng** [comment]
I will take the task. /assign
