### ISSUE TITLE
Expose the health check failures to the CI logs

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#1137]
#### What would you like to be added:

#1085 adds health checks for ccm and cnm, but we still cannot tell what is wrong in the CI logs if the ccm is down accidentally. Need to expose the failure events to the CI logs for further investigation.

**Comment by lzhecheng** [comment]
The PR below adds support to dump Pod events. Closing this issue.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2087
