### ISSUE TITLE
Cluster auto scaler not supporting Standard_HBxxx type nodes after update from 1.21 to 1.22

### ISSUE THREAD

**Issue by hterik** [kubernetes-sigs/cloud-provider-azure#1181]
#### What happened:
Create AKS cluster on v1.22.6
Create Nodepool with vm_size=Standard_HB120rs_v3.
Start pod demanding this node pool.
Nodes never start up
Auto scaler logs show `E0219 12:52:11.365374 1 static_autoscaler.go:304] Failed to get node infos for groups: instance type "Standard_HB120rs_v3" not supported `

#### What you expected to happen:
Node pool scale up when pods are created.

#### Anything else we need to know?:
This was working before on v1.21
I found this commit which looks relevant, _adding_, support in 1.22  https://github.com/kubernetes/autoscaler/pull/4166/files
I suspect this might be caused by the jump to out-of-tree provider in 1.22 such that fix above was not included? I don't fully understand if upstream autoscaler is in use in AKS or if this cloud-provider-azure has its own branch.

Looking into https://github.com/Azure/azure-sdk-for-go/blob/main/profiles/2020-09-01/compute/mgmt/compute/enums.go that type of node is missing.

#### Environment:

- Kubernetes version: 
`- Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"299916054187763fc9be625667430fa45690357b", GitTreeState:"clean", BuildDate:"2022-01-30T03:25:00Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by nilo19** [comment]
@hterik please open an issue in https://github.com/kubernetes/autoscaler
(Need to update https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go)

**Comment by hterik** [comment]
Hi
`azure_instance_types.go` already has Standard_HB120rs_v3, see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/azure_instance_types.go#L3337. 

This was added in https://github.com/kubernetes/autoscaler/pull/4166/files which got released in https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.0 Aug 2021.
Can i find out exactly which revision of cluster-autoscaler that is running in my AKS? 


What puzzles me is how this was working before we upgraded from 1.21 to 1.22? Maybe the error message is irrelevant and there is some other issue causing the autoscaler to not work here any more?

**Comment by hterik** [comment]
Managed to find this in the diagnostics logs `I0221 06:51:20.218040 1 main.go:415] Cluster Autoscaler 1.22.5 `. This version doesn't seem to exist in https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.22/cluster-autoscaler/version/version.go.  :raised_eyebrow:

**Comment by nilo19** [comment]
> Managed to find this in the diagnostics logs `I0221 06:51:20.218040 1 main.go:415] Cluster Autoscaler 1.22.5 `. This version doesn't seem to exist in https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-release-1.22/cluster-autoscaler/version/version.go. 🤨

The AKS does not use the upstream version of cluster-autoscaler. Can you open an issue in https://github.com/Azure/AKS?

**Comment by hterik** [comment]
Thanks, reported https://github.com/Azure/AKS/issues/2799 instead.
