### ISSUE TITLE
Changes in Load Balancer Annotations do not cause load balancer to update

### ISSUE THREAD

**Issue by vsabella** [kubernetes-sigs/cloud-provider-azure#1197]
Azure Kubernetes Service 1.21.7
Azure Kubernetes Service 1.21.9

Whenever we update a load balancer health probe to switch from TCP to HTTP protocol by applying the annotation:

```service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol=http``` 

The load balancer health probes are never updated. We need to delete the service entry and recreate it to have the health probes updated (creating downtime)

**Comment by MartinForReal** [comment]
related to #1346

**Comment by MartinForReal** [comment]
Hi @vsabella, We fixed this issue in pr 1346. Please feel free to raise ticket if you still encounter this error. Thanks!
