### ISSUE TITLE
add unit test for azure file client

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/cloud-provider-azure#1201]
#### What would you like to be added:
add unit test for azure file client
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azureclients/fileclient/azure_fileclient.go

any volumteer?

**Comment by cvvz** [comment]
I would like to work on it.
/assign

**Comment by cvvz** [comment]
Seems like azure file client use [fileSharesClient](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azureclients/fileclient/azure_fileclient.go#L34) and [fileServicesClient](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azureclients/fileclient/azure_fileclient.go#L35) to  make http calls. Should I use [monkey](https://github.com/bouk/monkey) to create **stubs** for the methods of these two structs, or should I use [httptest](https://pkg.go.dev/net/http/httptest) to **mock** the web service?

**Comment by nilo19** [comment]
looks it is not easy to test, @andyzhangx any ideas?

**Comment by nilo19** [comment]
Is it possible to migrate to armClient?

**Comment by cvvz** [comment]
Maybe we could abstract another two interfaces for fileSharesClient and fileServicesClient, rather than using the instances directly. This can be helpful for UT.
