### ISSUE TITLE
External kubernetes dependencies

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#124]
This is the meta-issue for tracking all the external dependencies, which are blockers for full standalone azure cloud provider.

cross reference [KEP for out-of-tree Azure cloud provider](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/azure/20190125-out-of-tree-azure.md).

## API throttling 

Instance metadata service could help to reduce API throttling issues, and increase the nodes initialization duration. This is especially helpful for large clusters.

But with CCM, this is not possible anymore because the above functionality has been moved to cloud controller manager. We should add this back into Kubelet.

This issue is being tracked under https://github.com/kubernetes/cloud-provider/issues/30 and the KEP for supporting IMDS is https://github.com/kubernetes/enhancements/pull/1158.

## Credential provider

Azure credential provider is still required (set by `kubelet --azure-container-registry-config`)

- On tracking at https://github.com/kubernetes/kubernetes/issues/58034
- Being tracked under https://github.com/kubernetes/cloud-provider/issues/13.
- KEP https://github.com/kubernetes/enhancements/pull/1406

## AzureDisk and AzureFile CSI drivers

AzureDisk and AzureFile volume plugins are still in-tree, but even with `--external-cloud-volume-plugin=azure` configured on kube-controller-manager, AzureDisk and AzureFile are still not working. See https://github.com/kubernetes/kubernetes/issues/71018 for explanations.

So to use with CCM, CSI drivers should always be used. The CSI drivers for them are tracking on the separate repos:
  - https://github.com/kubernetes-sigs/azuredisk-csi-driver
  - https://github.com/kubernetes-sigs/azurefile-csi-driver

#### 1. CSI on Windows (alpha in k8s v1.18)  (in progress)
  - [make azure disk CSI driver work on Windows](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/45)
  - [make azure file CSI driver work on Windows](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/24)

#### 2. CSI Driver Migration (in-tree driver to CSI driver)  (alpha in k8s v1.18) (in progress)
 - [azure disk CSI Driver Migration](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/194)
 - [azure file CSI Driver Migration](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/115)

#### 3. CSI drivers support on Windows

- [azure disk CSI driver on Windows](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/45)
- [azure file CSI driver on Windows](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/24)

#### 4. CSI driver integration with aks-engine  (done)
 - [Deploy CSI drivers for AzureDisk/AzureFile for cloud-controller-manager](https://github.com/Azure/aks-engine/issues/1916)

**Comment by feiskyer** [comment]
To support production-level out-of-tree Azure cloud provider, API throttling issue is a hard-blocker. So we need a new proposal to make CCM support instance metadata (refer https://github.com/kubernetes/cloud-provider/issues/30). 

/milestone v1.16

**Comment by feiskyer** [comment]
Status update: 

* https://github.com/kubernetes/enhancements/pull/1284 is working on the KEP for Credential Provider Extraction
* https://github.com/kubernetes/enhancements/pull/1158 has been integrated with aks-engine for v1.16+ cluster

**Comment by craiglpeters** [comment]
https://github.com/kubernetes/enhancements/pull/1406 is the new KEP for Credential Provider Extraction
