### ISSUE TITLE
[e2e] Add Windows ccm-e2e and conformance tests

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#1358]
#### What would you like to be added:
Add Windows ccm-e2e and conformance tests for master branch.

- [x] `Makefile` should support building and pusing images according to the target instead of build images of all ARCHs and OSes.
- [x] CAPZ script should use new make target to build and push different images according to `TEST_WINDOWS` variable
- [x] `test-infra` repo should add ccm-e2e and conformane tests

#### Why is this needed:
Windows node manager images are not tested.

**Comment by CecileRobertMichon** [comment]
@lzhecheng what's the status on this? Is it done?

**Comment by lzhecheng** [comment]
@CecileRobertMichon yes, it's done.
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-ccm-windows-capz
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-conformance-windows-capz

**Comment by CecileRobertMichon** [comment]
cc @jackfrancis
