### ISSUE TITLE
Support for unmanaged nodes

### ISSUE THREAD

**Issue by qby-tofi** [kubernetes-sigs/cloud-provider-azure#1495]
Hi,

we are running several k8s Clusters and using kubeedge to connect edge nodes to them. Currently we are using k8s 1.22 and azure-cloud-provider 1.1.x. We are using the label _kubernetes.azure.com/managed=false_ to prevent azure-cloud-provider trying to set Azure routes for our edge devices and setting Network unavailable state every few seconds. To get this feature work we disabled the IPv6DualStack FeatureGate in the cloud-provider configuration.

This does no longer work on azure-cloud-provider. IPv6DualStack is GA since kubernetes 1.23 and a dependency upgrade from k8s.io/controller-manager to v0.23 in the 1.23 branch of azure-cloud-provider makes sure that azure-cloud-provider respects it now.

#### What happened:

Instead of respecting the label azure-cloud-provider only logs "unmanaged nodes are not supported in dual stack mode" and the edge devices get network unavailable state.

#### What you expected to happen:

Respecting the label and don't try to set routes in azure for our edge devices.

#### How to reproduce it (as minimally and precisely as possible):

Setup an k8s 1.23 Cluster in azure
Deploy and configure azure-cloud-provider
label a node with kubernetes.azure.com/managed=false

#### Anything else we need to know?:

The relevant code can be found in azure_routes.go:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/dc231681d2397fcd5d750a8341dd8276cfe6181b/pkg/provider/azure_routes.go#L383-L386

There is a TODO mentioning @khenidak

#### Environment:

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.23.5

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
Linux control-plane-rhcbx 5.11.0-1028-azure #31~20.04.2-Ubuntu SMP Tue Jan 18 08:46:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

cluster-api

**Comment by MartinForReal** [comment]
close issue because fix is merged.
