### ISSUE TITLE
Loadbalancer Health Probes are not configurable for services which use a different health check port

### ISSUE THREAD

**Issue by vsabella** [kubernetes-sigs/cloud-provider-azure#1499]
When configuring Health Checks for Azure Load Balancer you can specify the path and type, but it is not possible to specify the port.

Istio Ingress Gateway and similar services do not expose health checks on their actual endpoints (as it can operate across multiple protocols) but instead expose a general health check on a different status port.

In AWS this is easily possible with the `service.beta.kubernetes.io/aws-load-balancer-healthcheck-port` annotation but it does not seem possible in Azure.

This prevents us from configuring the more reliable HTTP health check probes against Istio

**Comment by MartinForReal** [comment]
Please refer to https://kubernetes-sigs.github.io/cloud-provider-azure/topics/loadbalancer/#custom-load-balancer-health-probe. 
If you still have any problem, feel free to reopen this issue. Thanks!

**Comment by vsabella** [comment]
Thanks @MartinForReal  but unfortunately that does not solve the problem. I will re-open.

For example
Istio hosted on two ports: Port 80 and Port 443 will not serve any traffic until a Virtual Service is deployed

The health check needs to be a HTTP health check against port 15021

Example

For the following spec:
```
spec:
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
```

The health probe needs to look like this:

![image](https://user-images.githubusercontent.com/2106153/163553850-363f77a5-2dea-4e04-962b-3af95d33e3b0.png)

The probe protocol and endpoint and everything can be set, but the PORT cannot be.

**Comment by vsabella** [comment]
I reopened as #1505
