### ISSUE TITLE
FailedToCreateRoute when creating unmanaged node due to IPv6DualStack

### ISSUE THREAD

**Issue by lastcoolnameleft** [kubernetes-sigs/cloud-provider-azure#1639]
LIQO is an CNCF project that allows you to federate two clusters.  When installing [LIQO](https://liqo.io/), it tries to create an unmanaged node, but fails because it's not supported with the current feature flags.

[Revelant Code](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_routes.go#L385)

The other cluster appears as another node (Similar to Virtual Kubelet + ACI).  I created two AKS clusters (only defaults) and joined them together.  The "unmanaged node" refers to the "liqo-liqo-1" shown below:

+ kubectl get nodes -o=custom-columns=NAME:.metadata.name,ADDRESSES:.status.addresses[?(@.type=='InternalIP')].address,PODCIDRS:.spec.podCIDRs[*]
NAME                                ADDRESSES    PODCIDRS
aks-nodepool1-15798508-vmss000000   10.240.0.4   10.244.2.0/24
aks-nodepool1-15798508-vmss000001   10.240.0.5   10.244.1.0/24
aks-nodepool1-15798508-vmss000002   10.240.0.6   10.244.0.0/24
liqo-liqo-1                         10.244.2.5   10.244.3.0/24

#### What happened:

```
  Warning  FailedToCreateRoute  74s   route_controller  Could not create route 883469eb-3134-4a1e-add1-2f4f64b7b40f 10.244.3.0/24 for node liqo-liqo-1 after 202.4µs: unmanaged nodes are not supported in dual stack mode
```

#### What you expected to happen:

I'd expect the route to be created and the unmanaged node to be successfully created.

#### How to reproduce it (as minimally and precisely as possible):

```
az aks create -n liqo-1 -g liqo
az aks create -n liqo-2 -g liqo

# Install LIQO on each cluster.
az aks get credentials -n liqo-1 -g liqo
liqoctl install aks --resource-group-name liqo --resource-name liqo-1 --subscription-id "${AKS_SUBSCRIPTION_ID}"

az aks get credentials -n liqo-2 -g liqo
liqoctl install aks --resource-group-name liqo --resource-name liqo-2 --subscription-id "${AKS_SUBSCRIPTION_ID}"


# Join the two clusters together 
# The IP/ID/Token are provided from the `liqoctl install` command earlier
liqoctl add cluster liqo-1 --auth-url https://<PROVIDED_IP> --id <PROVIDED_ID> --token <PROVIDED_TOKEN>

kubectl describe node liqo-liqo-1
# See the error for the route creation failure
```

#### Anything else we need to know?:

Is there a way either IPv6DualStack can be supported for unmanaged nodes in the Azure Cloud Provider code or that we can disable that feature flag in AKS cluster?

#### Environment:

Unfortunately, the cluster was deleted so I don't have some of the information, but it used comlpetely default settings.

- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: AKS 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by CecileRobertMichon** [comment]
I believe this is related to this [TODO here](https://github.dev/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_routes.go#L387) 

`//TODO (khenidak) add support for unmanaged nodes when the feature reaches beta`

cc @khenidak @aramase @nilo19 

Also cc @alexeldeib this might block CAPZ BYO AKS node

**Comment by MartinForReal** [comment]
I think label kubernetes.azure.com/managed: false should be applied to virtual node.

**Comment by MartinForReal** [comment]
@lastcoolnameleft Please refer to https://kubernetes-sigs.github.io/cloud-provider-azure/topics/cross-resource-group-nodes/#unmanaged-nodes

**Comment by nilo19** [comment]
@MartinForReal can we close this one?

**Comment by MartinForReal** [comment]
close because pr is merged
