### ISSUE TITLE
Nodes where exclude-from-external-load-balancers is set to false or removed are not added-back to the load balancer.

### ISSUE THREAD

**Issue by vsabella** [kubernetes-sigs/cloud-provider-azure#1643]
Nodes where exclude-from-external-load-balancers is set to false or removed are not added-back to the load balancer.

#### What happened:
When applying `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers=true` the node is effectively removed from the load balancer

However when applying `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers=false --overwrite` or  `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers= --overwrite` to remove the label, the node is never *added* back into the load balancer.

#### What you expected to happen:
Excluded node should be reconciled back into the load balancer.

#### How to reproduce it (as minimally and precisely as possible):
* `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers=true` 
* `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers=false --overwrite` 

#### Environment:
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Azure AKS v 1.22.6 (on US GovCloud, have not tried on Commercial yet)

**Comment by jwtty** [comment]
Hi @vsabella, cloud provider follows the same process as kubernetes main tree: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L677. We only check the existence of the label but not the value.
I tried removing the label by `kubectl label node aks-ingress-123 node.kubernetes.io/exclude-from-external-load-balancers-` and the node got added back properly.
Please try and see if it works.

**Comment by jwtty** [comment]
Close the issue as there is no response.

**Comment by vsabella** [comment]
@jwtty It may have been GovCloud controllers were behind in version. This seems to work again I will re-open if we see otherwise.
