### ISSUE TITLE
why separate the node-controller out of cloud-controller-manager

### ISSUE THREAD

**Issue by SnowmanCharles** [kubernetes-sigs/cloud-provider-azure#1700]
The cloud-controller-manager manages node-lifecycle-controller, service-controller, and route-controller. It runs as a Deployment on cluster control plane.

The azure-cloud-node-manager only manages node-controller. It runs as a DaemonSet on user nodes. Node-controller does two things:
1. reconcile labels
2. update node addresses

The question is why can't node-controller run on cluster control plane? Why do we need this extra azure-cloud-node-manager ?

**Comment by SnowmanCharles** [comment]
Also, the official doc says node-controller should be disabled when starting azure-cloud-controller-manager. https://kubernetes-sigs.github.io/cloud-provider-azure/install/azure-ccm/#azure-cloud-controller-manager

However, will the node-controller still work if I run it as part of azure-cloud-controller-manager (By not disabling it when starting azure-cloud-controller-manager)?

**Comment by MartinForReal** [comment]
Hi @SnowmanCharles ,
When the number of nodes are large enough, the node manager controller may got throttled by ARM. Sometimes it takes a while to update each node. FYI.

**Comment by SnowmanCharles** [comment]
> 

Hi @MartinForReal ,

Does running node manager on each node pool node help with this issue? Looks like the ARM API calls to get details of each VM does not reduce, unless the UseInstanceMetadataFlag is explicitly set as true.

Another question here is: If I do not disable node-controller when starting azure-cloud-controller-manager, will it just work?

Thanks

**Comment by MartinForReal** [comment]
> Does running node manager on each node pool node help with this issue? 
Yes, the client id is different
>If I do not disable node-controller when starting azure-cloud-controller-manager, will it just work?
The node is not ready because the node manager does not update the node.
