### ISSUE TITLE
slow disk attach relating to SetDiskLun failures

### ISSUE THREAD

**Issue by chmill-zz** [kubernetes-sigs/cloud-provider-azure#1742]
#### What happened:
azure disk attach is slow because of lun mapping issues

#### What you expected to happen:
disks to attach faster

#### How to reproduce it (as minimally and precisely as possible):
Right now I've seen this behavior reproduce after the cloud provider is throttled by Azure. When we retry to AttachDisk after the retry time is up we fail to SetDiskLun. I've seen this add 10minutes to an attach time after throttling delays.

I believe this can happen in any scenario where the AttachDisk func doesn't successfully apply/update the vmss model on the azure side (throttling is one of those scenarios).

#### Anything else we need to know?:

From the audit log of the cluster. We get a throttling failure. Followed by an issue setting the lun. Then we don't actually attach until ~10min later.

```
  "attachError": {
    "message": "rpc error: code = Unknown desc = Attach volume /subscriptions/.... to instance aks-agentpool-... failed with Retriable: true, RetryAfter: 121s, HTTPStatusCode: 0, RawError: azure cloud provider throttled for operation VMSSVMUpdateAsync with reason \"client throttled\"",
    "time": "2022-05-13T17:23:16Z"
  }
```

```
{
  "attachError": {
    "message": "rpc error: code = Unknown desc = Attach volume /subscriptions/... to instance aks-agentpool-... failed with could not find disk(/subscriptions/...) in current disk list(len: 14) nor in diskMap(map[])",
    "time": "2022-05-13T17:24:12Z"
  }
}
```

```
 "time": "2022-05-13T17:34:06Z",
  "status": {
    "attached": true,
    "attachmentMetadata": {
      "LUN": "23"
    }
```

From the Azure Activity logs I can see that the PUT with the disk didn't come in until 17:34. So it's not a delay on the azure side.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.22.6
- Cloud provider or hardware configuration: azure
- Others: disk.csi.azure.com/v1.17.0

**Comment by nilo19** [comment]
@andyzhangx can you have a look when you have time?

**Comment by andyzhangx** [comment]
@chmill-zz `VMSSVMUpdateAsync` operation was throttled, it happens when there are disk attach/detach on a lot of agent nodes simultaneously.
