### ISSUE TITLE
[helm] make update-helm will possibly replace the old ones in index.yaml

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#1756]
#### What happened:
After updating `helm/` chart, I found that `make update-helm` adds a new v1.24. but also removes the old two version.

#### What you expected to happen:
`make update-helm` adds a new version without touching old ones.

#### How to reproduce it (as minimally and precisely as possible):
Update `helm/` chart and `make update-helm`.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jackfrancis** [comment]
I noticed this too. It only happens when using `+<suffix`> like semver versions. :(
