### ISSUE TITLE
Introduce a new service annotation to replace service.Spec.LoadBalancerIP

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#1781]
#### What would you like to be added:

According to https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4434, we need to introduce a new annotation to replace the loadBalancerIP, as it will be removed in the future.

#### Why is this needed:

https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1781#tasklist-block-ecb5dc84-8396-45ad-9fd6-b5ed9cd8a154

**Comment by kanha-gupta** [comment]
what do we have to replace it with ?

**Comment by nilo19** [comment]
We can add an annotation here https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/consts/consts.go
I recommend `service.beta.kubernetes.io/azure-load-balancer-ip`, what do you think?

**Comment by kanha-gupta** [comment]
I think you are right

**Comment by nilo19** [comment]
Hi @kanha-gupta, do you still plan to do this one?

**Comment by nilo19** [comment]
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2428 to introduce a new annotation.
Use this issue to track as we need to completely remove the service.Spec.LoadBalancerIP in the future.

**Comment by feiskyer** [comment]
this was added by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2428.
