### ISSUE TITLE
Enable cloud-provider-azure-scalability periodic e2e tests

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#183]
Enable cloud-provider-azure-scalability periodic e2e tests and public the results to [testgrid](https://testgrid.k8s.io/sig-azure-master).

/kind testing

**Comment by feiskyer** [comment]
https://github.com/kubernetes/test-infra/pull/15067 is adding the tests for it.

**Comment by chewong** [comment]
[ci-kubernetes-kubemark-100-azure](https://testgrid.k8s.io/provider-azure-cloud-provider-azure#ci-kubernetes-kubemark-100-azure) is failing for a long time without any fix. I will look into this.

**Comment by feiskyer** [comment]
@nilo19 is also looking at the it

**Comment by nilo19** [comment]
https://github.com/nilo19/kubemark-performance-tests-on-azure

I've conducted the performance tests in my local environment. Need some time to figure out how it could  be migrated to test-infra because there're many manual hacks.

**Comment by feiskyer** [comment]
Status update: SSH is widely used in kubemark tests, while 22 port is disabled by security policies. Since aks-engine doesn't support customizing SSH port for master nodes, the next step is figuring out how to change 22 to a different port now.

**Comment by chewong** [comment]
@feiskyer once the test is running in the CNCF upstream subscription, such policy doesn't exist anymore and port 22 should be available. For example, SSH is used in https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-serial with SSH keypair defined [here](https://github.com/kubernetes/test-infra/blob/1a48e1bdde5a8a9c9027a92337463e262334000b/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L441-L447).

**Comment by nilo19** [comment]
> @feiskyer once the test is running in the CNCF upstream subscription, such policy doesn't exist anymore and port 22 should be available. For example, SSH is used in https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-serial with SSH keypair defined [here](https://github.com/kubernetes/test-infra/blob/1a48e1bdde5a8a9c9027a92337463e262334000b/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L441-L447).

That would be so nice.

**Comment by nilo19** [comment]
The test has been enabled https://testgrid.k8s.io/provider-azure-scalability#ci-kubernetes-kubemark-100-azure-test. Shall we close this?

**Comment by feiskyer** [comment]
thanks @nilo19 for enabling it.

/close
