### ISSUE TITLE
Azure load balancer incorrectly includes nodes from newly created node pools when using node.kubernetes.io/exclude-from-external-load-balancers label

### ISSUE THREAD

**Issue by sivetic** [kubernetes-sigs/cloud-provider-azure#1902]
#### What happened:
Azure load balancer fails to exclude nodes from newly created AKS user node pools when using `node.kubernetes.io/exclude-from-external-load-balancers=true` label.

I am creating:
* an AKS cluster with a dedicated system node pool and a user node pool
* a K8s service of type LoadBalancer and `service.beta.kubernetes.io/azure-load-balancer-internal: "true"` annotation to create an internal LB
* the user node pool has the `node.kubernetes.io/exclude-from-external-load-balancers=true` label applied, so that only system nodes are included in the ILB backend pool.  
 
The setup works properly - user node pools are excluded from internal load balancer while system nodes are properly included.

After adding a new AKS user node pool with the `node.kubernetes.io/exclude-from-external-load-balancers=true` label, nodes from the new user node pool are included in the ILB backend pool.  Nodes from the initial user node pool continue to be excluded.

Problem seems to be resolved after re-creating the Kubernetes service.  Kubernetes service has to be re-created each time a new user node pool is added.

#### What you expected to happen:

All nodes with `node.kubernetes.io/exclude-from-external-load-balancers=true` label should be excluded from the load balancer backend pool.

#### How to reproduce it (as minimally and precisely as possible):

* Create a new AKS cluster with the default system pool and an additional user node pool.  Add `node.kubernetes.io/exclude-from-external-load-balancers=true` label to user node pool.
![image](https://user-images.githubusercontent.com/1087320/174630168-4e8cef27-c753-4aa2-a44a-c3344149d464.png)

* Create a Kubernetes LB service
```
kind: Service
apiVersion: v1
metadata:
  name: lb-service
  labels:
    app: lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: lb
  ports:
    - protocol: TCP
      name: http
      port: 80
  type: LoadBalancer
```
* Confirm the internal load balancer backend pool only has system nodes: 
![image](https://user-images.githubusercontent.com/1087320/174630329-dea9d867-d2e9-4dbe-be7e-5d29f8db3f50.png)

* Create a new AKS user node pool. Add `node.kubernetes.io/exclude-from-external-load-balancers=true` label to new user node pool.
![image](https://user-images.githubusercontent.com/1087320/174630046-4e369593-b4df-4d51-9154-f6dd23200b68.png)

* Check nodes on internal load balancer backend pool, nodes from new user pool are now added to the backend pool, which is incorrect behaviour (note the userpool2 listed in network interface column).
![image](https://user-images.githubusercontent.com/1087320/174630608-30746619-0978-4ab7-8788-bfba68445b31.png)

* Delete and re-create Kubernetes LB service.  Check nodes on internal load balancer backend pool, now only system node pool nodes are listed.
![image](https://user-images.githubusercontent.com/1087320/174631283-cf61196f-eeae-4207-937a-576ca0385486.png)

* Scale both user node pools (add new nodes to each) to confirm new nodes are excluded:
![image](https://user-images.githubusercontent.com/1087320/174632083-20708735-7573-47db-9a2d-e7010943838b.png)
![image](https://user-images.githubusercontent.com/1087320/174632125-e22104e3-5b3d-4f7a-80e9-8a91f48e038c.png)

#### Anything else we need to know?:
Issue was reproduced in same fashion on AKS 1.22, 1.23 and 1.24 (preview)

#### Environment:

- Kubernetes version (use `kubectl version`):
```
PS C:\uce_code\temp\http504> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"8211ae4d6757c3fedc53cd740d163ef65287276a", GitTreeState:"clean", BuildDate:"2022-03-31T20:28:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Azure AKS
- OS (e.g: `cat /etc/os-release`):
```
root@aks-agentpool-74374278-vmss000000:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
root@aks-agentpool-74374278-vmss000000:/# uname -a
Linux aks-agentpool-74374278-vmss000000 5.4.0-1083-azure #87~18.04.1-Ubuntu SMP Fri Jun 3 13:19:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jackfrancis** [comment]
@alexeldeib is this a known AKS bug?

**Comment by jackfrancis** [comment]
@sivetic thank you for all the detailed info!

**Comment by sivetic** [comment]
Correction - deleting and re-creating the Kubernetes service and ILB does not seem to fix the issue.  I just tested it with an existing cluster and still see newly scaled nodes show in ILB backend pool.

Not sure if this is helpful, but here is VMSS loadBalancerBackendAddressPools configuration.  Order of operations was:
* Create AKS cluster with system and user pool (user pool has the exclude label)
* Create Kubernetes LoadBalancer service
* Create second user pool (user pool has the exclude label)
* Get JSON config of all 3 pools

System node pool:

```
"loadBalancerBackendAddressPools": [
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/aksOutboundBackendPool"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/mc_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes-internal/backendAddressPools/kubernetes"
    }
]
```

User node pool 1 (initially created pool):

```
"loadBalancerBackendAddressPools": [
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/aksOutboundBackendPool"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
    }
]
```

User node pool 2 (subsequently created pool):

```
"loadBalancerBackendAddressPools": [
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/aksOutboundBackendPool"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/mc_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes-internal/backendAddressPools/kubernetes"
    }
]
```


Initially created VMSS does not have the kubernetes-internal LB configured while the subsequently created VMSS does.

**Comment by sivetic** [comment]
More updates/workarounds from our troubleshooting that we found, hopefully they are of help:

* Deleting the Kubernetes service (and the ILB), creating a new node pool w/ exclude label and then creating the Kubernetes service works properly - nodes are excluded from ILB
* Creating a node pool without the exclude label and using az aks nodepool update to add the label works properly - nodes are excluded from ILB
* Creating a node pool with the exclude label, using az aks nodepool update to remove and re-add the label works properly - nodes are excluded from ILB

It looks like the last option can function as our temporary workaround until issue is fixed properly.

**Comment by sivetic** [comment]
Looks like removing the kubernetes-internal load balancer pool from VMSS works properly and excludes the VMs from LB.  Given VMSS config:

```
"loadBalancerBackendAddressPools": [
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/aksOutboundBackendPool"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/MC_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
    },
    {
        "id": "/subscriptions/<sub>/resourceGroups/mc_dev01-sasa-test_dev01-sasa-aks-09_eastus/providers/Microsoft.Network/loadBalancers/kubernetes-internal/backendAddressPools/kubernetes"
    }
]
```

LB pool can be edited using `az cli`:

```
az vmss update --name <vmss> --resource-group <rg> --remove virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerBackendAddressPools <ilb index>
```

Which results in VMs no longer being included as part of the load balancer backend pool.  I'm not sure however what is responsible for configuring the LB profile when a node pool is created, which is what needs to be fixed.

**Comment by weinong** [comment]
ack from AKS. cc: @nilo19 @feiskyer

**Comment by feiskyer** [comment]
The newly created VMSS networking profile is controlled by provisioning steps (e.g. in AKS API or capz), which is out control of cloud provider. Hence, we would fix this issue in AKS API.

From cloud provider side, I validated the VMSS nodes would be removed from SLB backend pool once the LoadBalancer services are reconciled, which has already been working as expected.
