### ISSUE TITLE
update docs to correctly describe how to run e2e tests 

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes-sigs/cloud-provider-azure#1927]
#### What happened:

https://kubernetes-sigs.github.io/cloud-provider-azure/development/e2e/e2e-tests/ talks about using the now-deprecated AKS Engine for e2e tests.

#### What you expected to happen:

Because https://github.com/kubernetes-sigs/cloud-provider-azure/issues/919 is resolved, I thought that we are deprecating e2e tests that use AKS Engine.

#### How to reproduce it (as minimally and precisely as possible):

See https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/site/content/en/development/e2e/e2e-tests.md#how-to-run-kubernetes-e2e-tests-locally for the outdated information.

#### Anything else we need to know?:

Please update the docs so we don't have people thinking that AKS Engine should be or is used for e2e tests. Thanks.

**Comment by lzhecheng** [comment]
/assign
@bridgetkromhout Thank you for raising this issue!
I will add CAPZ related info (how to create a cluster, how to repro e2e locally) into the doc. It should help developers debug why their ccm e2e tests fail in CI.
But actually these tests still work for aks-engine, at least for now (k8s v1.24). I will mention that capz is preferred and we don't guarantee testing on aks-engine works in the future.

**Comment by bridgetkromhout** [comment]
> these tests still work for aks-engine, at least for now (k8s v1.24)

Yes, but we should not encourage new people to start using AKS Engine, so I think it is better for the docs to only talk about the recommended path (CAPZ). What do you think?

**Comment by lzhecheng** [comment]
> > these tests still work for aks-engine, at least for now (k8s v1.24)
> 
> Yes, but we should not encourage new people to start using AKS Engine, so I think it is better for the docs to only talk about the recommended path (CAPZ). What do you think?

Yes. We can do that.
