### ISSUE TITLE
Add metrics about cloudprovider backoff and rate limiting

### ISSUE THREAD

**Issue by sylr** [kubernetes-sigs/cloud-provider-azure#201]
**Is your feature request related to a problem?/Why is this needed**

It would be very useful to be able to follow throttling of cloudprovider requests to be able to tune clouprovider backoff and rate limiting settings.

**Describe the solution you'd like in detail**

Gauges for the value of each settings and Counter incremented when requests are made, throttled, backed off ... etc.

**Describe alternatives you've considered**

**Additional context**

Related to https://github.com/Azure/aks-engine/issues/420

**Comment by feiskyer** [comment]
The metrics are already added in controller manager, you can get them from `<controller-manager-ip>:10252/metrics`.

**Comment by sylr** [comment]
@feiskyer can you do me a list of metrics that you have ?

So far I only see those on 1.13.6:

- cloudprovider_azure_api_request_duration_seconds_bucket{}
- cloudprovider_azure_api_request_duration_seconds_count{}
- cloudprovider_azure_api_request_duration_seconds_sum{}

**Comment by feiskyer** [comment]
For example:

```
cloudprovider_azure_api_request_duration_seconds_bucket{request="vm_list",resource_group="<rg-name>",source="",subscription_id="<subscription-id>",le="0.005"} 1
cloudprovider_azure_api_request_duration_seconds_count{request="vmssvm_get",resource_group="<rg-name>",source="",subscription_id="<subscription-id>"} 1
cloudprovider_azure_api_request_duration_seconds_bucket{request="vmss_list",resource_group="<rg-name>",source="",subscription_id="<subscription-id>",le="1"} 1
...
```

**Comment by sylr** [comment]
I don't see any metrics about the number of calls being throttled or backed off.

**Comment by feiskyer** [comment]
it doesn't include throttled numbers, only number of requests are exposed.

**Comment by sylr** [comment]
Yes, that's the purpose of the issue, expose metrics about the number of calls being throttled or backed off.

**Comment by craiglpeters** [comment]
@sylr is the way to get the metrics resolved for you? Can we close this issue?

**Comment by sylr** [comment]
I'm not sure to understand.

This issue will stand as long as there are no metrics exposed about throttled or backed off cloud provider API requests.

**Comment by feiskyer** [comment]
This is already supporte, see https://github.com/kubernetes/legacy-cloud-providers/blob/b0dccdf763a22dea0844dd23a1c9b4041b975d1c/azure/metrics/azure_metrics.go#L85-L114

**Comment by sylr** [comment]
Very well then! I'm closing this.

Thanks @feiskyer .
