### ISSUE TITLE
LoadBalancer Annotation service.beta.kubernetes.io/azure-shared-securityrule doesn't share rules

### ISSUE THREAD

**Issue by bradmann** [kubernetes-sigs/cloud-provider-azure#2143]
#### What happened:
- Created a LoadBalancer with the annotation `service.beta.kubernetes.io/azure-shared-securityrule=true`
- Add multiple `loadBalancerSourceRanges` rules to the LoadBalancer config.
- Multiple Security Rules are created in the Azure NSG.

#### What you expected to happen:
- Should only create a single shared Security Rule with comma-separated Source Addresses from `loadBalancerSourceRanges`.

#### How to reproduce it (as minimally and precisely as possible):
- See `What happened` section above.

#### Environment:

- Kubernetes version (use `kubectl version`): v1.19.16
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.6 LTS

**Comment by nilo19** [comment]
The version of v1.19.16 is expired. Can you try the out-of-tree cloud provider azure?
