### ISSUE TITLE
The node could be deleted unexpectedly because of a nil entry in the VMSS VM cache

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#2156]
#### What happened:

The deleting VMSS VM was set nil in the cache, and querying a deleting VM will result in `InstanceNotFound`. In this case, the node lifecycle controller will delete the node. But there is a chance that the VM is deleted and re-created with the same name in a short period of time, and we will not refresh the cache, node lifecycle controller will remove the node unexpectedly.
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2060/files fixes the nil issue but has not been cherry-picked onto release branches.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by feiskyer** [comment]
Refer https://github.com/kubernetes-sigs/cloud-provider-azure/issues/247, this is a known limitation introduced with caches to reduce throttling issues.
