### ISSUE TITLE
Retry deleting the LB if 204 is returned

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#2168]
#### What happened:

Deleting LB will sometimes succeed with code 204, but the request doesn't reach NRP side, and the LB doesn't get deleted. We should try to GET the LB to see if it still exists. If so, we should retry deleting it.

#### What you expected to happen:

The LB should be deleted.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by johurul000** [comment]
@nilo19 Hi, i am new to opensource and I would like to contribute to this issue. If you could help me!!

**Comment by uroy-personal** [comment]
Hi @nilo19 ,
I am interested in working on this issue.  Would appreciate If you could provide more info and guidance in implementing it.

**Comment by amargherio** [comment]
@uroy-personal are you still interested in working on this issue? If not, @nilo19 I'd like to take this work on if it hasn't been addressed already.

**Comment by amargherio** [comment]
After checking with @nilo19 and a bit of discussion, it appears that this behavior hasn't been observed for a while now. This might be safe to close and could be reopened if the behavior comes up again.

**Comment by feiskyer** [comment]
Thanks for the discussion and conclusion! 

/close
