### ISSUE TITLE
Worker nodes temporarily loose connectivity when creating/deleting LB service

### ISSUE THREAD

**Issue by rastislavs** [kubernetes-sigs/cloud-provider-azure#2171]
#### What happened:
When creating / deleting LoadBalancer services, Azure VM worker nodes may temporarily loose network connectivity. It does not happen always, and not always on all nodes. After several minutes, the issue recovers itself and the nodes gain connectivity again.

The issue has been tracked down to the update of the VM Network Interface that CCM is doing to update the `loadBalancerBackendAddressPools` of the network interface.

This update may be very quick, in which case no issues are observed. But sometimes that update seems to take longer and produces a list of events like this one:

![Screenshot 2022-08-12 at 11 49 12](https://user-images.githubusercontent.com/15926980/184357680-fcb3f429-a006-4d20-8c25-e9525c893161.png)

 During this particular network interface update, which started "18 minutes ago" (from the screenshot time perspective), the node connectivity has been recovered "6 minutes ago" after the 3rd "Succeeded" event, meaning that the node lost connectivity for 12 minutes.

#### What you expected to happen:
The worker nodes should not loose network connectivity when LoadBalancer services are being attached / detached to workloads running on them.

#### How to reproduce it (as minimally and precisely as possible):
This issue can be reproduced in k8s cluster consisting of 3 worker nodes consisting of `Standard_B2s` VMs running Ubuntu 20.04 OS (`5.15.0-1017-azure` kernel) without public IPs (with only private IPs), in the West Europe region.

#### Anything else we need to know?:
I managed to reproduce the same issue also with the in-tree CCM.

#### Environment:

- Kubernetes version (use `kubectl version`): v1.24.3
- Cloud provider or hardware configuration: `Standard_B2s` VMs, without public IPs (with only private IPs)
- OS (e.g: `cat /etc/os-release`): Linux (ubuntu 20.04)
- Kernel (e.g. `uname -a`): `5.15.0-1017-azure`
- Install tools:
- Network plugin and version (if this is a network-related bug): Canal v3.23
- Others:

**Comment by nilo19** [comment]
This is not an issue of cloud provider azure. Maybe there is a bug on the VM network side, but we cannot control that.

**Comment by sreis** [comment]
> When creating / deleting LoadBalancer services, Azure VM worker nodes may temporarily loose network connectivity. It does not happen always, and not always on all nodes. After several minutes, the issue recovers itself and the nodes gain connectivity again.

@rastislavs We're tracking down networking issues in our Azure clusters with similar symptoms. We're starting to suspect throttling by ARM (Azure Resource Manager). Still gathering evidence. With that in mind, what is the rough size of your cluster? Tens of nodes? Few hundreds?
