### ISSUE TITLE
[Dual-stack] LoadBalancer Service with disabled floating-ip got error when enabling service.beta.kubernetes.io/azure-shared-securityrule

### ISSUE THREAD

**Issue by andy-anhnguyen** [kubernetes-sigs/cloud-provider-azure#2218]
#### <a name="desc"></a>What happened:
- Add a Service typed LoadBalancer in dual-stack kubernetes cluster with the annotation `service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip: "true"`, AKS worked fine and created the expected load balancing rule.
- Add annotation `service.beta.kubernetes.io/azure-shared-securityrule: "true"` to the Service. 
- `kubectl describe svc <lb_service>` showed below error, and update doesn't take effect. No other changes can be made to services until reversing the 2 aboe rules.
    ```
	Warning  SyncLoadBalancerFailed  20s (x2 over 13m)   service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
	  "error": {
		"code": "ResourceCannotContainAddressPrefixesFromDifferentAddressFamilies",
		"message": "Resource /subscriptions/<sub_id>/resourceGroups/mc_<aks_resource_group>/providers/Microsoft.Network/networkSecurityGroups/<aks-agentpool-nsg>/securityRules/<random_string>-TCP-80-Internet contains IP addresses or prefixes that belong to different address families. All IP addresses or prefixes in the resource should belong to the same address family.",
		"details": []
	  }
	```
#### What you expected to happen:
- Enable `service.beta.kubernetes.io/azure-shared-securityrule` should not cause error.
- Disable 'service.beta.kubernetes.io/azure-shared-securityrule' should not cause error and doesn't require reversing disable-load-balancer-floating-ip config.

#### How to reproduce it (as minimally and precisely as possible):
- Create dual-stack AKS cluster.
- Deploy a simple application like nginx on it.
- Create a Service typed LoadBalancer following [What happened](#desc) section.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.24.0
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by jwtty** [comment]
The issue is actually not related to shared NSG rule. But service disabling floating ip cannot get reconciled in dual-stack clusters with above nsg failure.
