### ISSUE TITLE
Benchmark number of Azure requests

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#228]
**Is your feature request related to a problem?/Why is this needed**

According to Azure documentation [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits), for each Azure subscription and tenant, Resource Manager allows up to **12,000 read requests per hour** and 1,200 write requests per hour.

We need to benchmark how much requests cloud provider is sending to Azure, so that users could set proper backoff and retry params based on their specific scenarios. This is especially useful for large clusters and multiple clusters that share same Azure resources (e.g. VNET and NSG).

As there're 3Min, 30Min and 1Hour rate limits from Azure API, the benchmarks should also be done based on those periods.

Related params include:

|Name|Description|Remark|
|---|---|---|
|cloudProviderBackoff|Enable exponential backoff to manage resource request retries|Boolean value, default to false|
|cloudProviderBackoffRetries|Backoff retry limit|Integer value, valid if `cloudProviderBackoff` is true|
|cloudProviderBackoffExponent|Backoff exponent|Float value, valid if `cloudProviderBackoff` is true|
|cloudProviderBackoffDuration|Backoff duration|Integer value, valid if `cloudProviderBackoff` is true|
|cloudProviderBackoffJitter|Backoff jitter|Float value, valid if `cloudProviderBackoff` is true|
|cloudProviderRateLimit|Enable rate limiting|Boolean value, default to false|
|cloudProviderRateLimitQPS|Rate limit QPS (Read)|Float value, valid if `cloudProviderRateLimit` is true|
|cloudProviderRateLimitBucket|Rate limit Bucket Size|Integar value, valid if `cloudProviderRateLimit` is true|
|cloudProviderRateLimitQPSWrite|Rate limit QPS (Write)|Float value, valid if `cloudProviderRateLimit` is true|
|cloudProviderRateLimitBucketWrite|Rate limit Bucket Size|Integer value, valid if `cloudProviderRateLimit` is true|

**Describe the solution you'd like in detail**

Disable cloudProviderBackoff and cloudProviderRateLimit, then benchmark number of Azure requests based on the following scenarios:

* Number of nodes
* Number of LoadBalancer typed services
* Number of AzureDisk PVCs attached to Pods

**Describe alternatives you've considered**

**Additional context**

Refer https://github.com/Azure/aks-engine/pull/1783 and https://github.com/Azure/aks-engine/issues/420.

/assign @ritazh

**Comment by kkmsft** [comment]
We have latency metrics, but need metrics to count the number of operations we are performing to get the required data for this benchmark runs. 

Example:

```
func (az *azVirtualMachinesClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, VMName string, parameters compute.VirtualMachine, source string) (resp *http.Response, err error) {
	// /* Write rate limiting */
	if !az.rateLimiterWriter.TryAccept() {
		err = createRateLimitErr(true, "VMCreateOrUpdate")
		return
	}
	klog.V(10).Infof("azVirtualMachinesClient.CreateOrUpdate(%q, %q): start", resourceGroupName, VMName)
	defer func() {
		klog.V(10).Infof("azVirtualMachinesClient.CreateOrUpdate(%q, %q): end", resourceGroupName, VMName)
	}()
	mc := newMetricContext("vm", "create_or_update", resourceGroupName, az.client.SubscriptionID, source)
	future, err := az.client.CreateOrUpdate(ctx, resourceGroupName, VMName, parameters)
	if err != nil {
		return future.Response(), err
	}

	err = future.WaitForCompletionRef(ctx, az.client.Client)
	mc.Observe(err)
	return future.Response(), err
}
```

Will raise a PR to add them shortly.

**Comment by feiskyer** [comment]
@kkmsft thanks

**Comment by jcrowthe** [comment]
@feiskyer You're already aware of this, but I'm stating this here for the benefit of others.

ARM does in fact have limits of [12,000 read requests per hour and 1,200 write requests per hour.](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits) However this is just the "front door" of Azure's API's. Once you get past this front door layer (which does basic authn/authz, triaging, etc.), you then get to the individual Resource Providers which will actually fulfill the request. Examples of this would be Compute Resource Provider, found at `Microsoft.Compute/` or Network Resource Provider found at `Microsoft.Network/` in the API schema. These sub-API's enforce their own rate limits, which so far are known to be significantly smaller than 12k/1.2k, and which are dynamic, based on subscription usage.

This is only to say that if we are designing the Azure cloud provider controller expecting the limits to be 12k read/1.2k write, we will have egregiously overused the available quota and caused operators to receive 429 Too Many Requests. In my experience, I've never actually hit these ARM limits, only ever hitting the individual Resource Provider's limits.

Hopefully this helps others not familiar with the ecosystem!

**Comment by feiskyer** [comment]
@jcrowthe Thanks for the great information. Since there're more and more large clusters, or multiple clusters running in the same subscription, this work item aims to benchmark the total number of Azure requests, so that some guides could be generated to configure the client-side rate limiting.

**Comment by azizavi** [comment]
@feiskyer and @ritazh - I understand knowing the generic usage of the APIs count so that we can implement/design the respective backoff in the Azure cloud provider. But i think Azure provides options for these API rate-limits to be increased for customers, keeping this in mind should we have the option to make the backoff parameters configurable (default values can be used from this benchmark study)?
