### ISSUE TITLE
What is the plan to migrate existing clusters from in-tree to out-of-tree CPI?

### ISSUE THREAD

**Issue by wangyuan0916** [kubernetes-sigs/cloud-provider-azure#2297]
I'm planning to migrate existing k8s clusters on azure from in-tree to out-of-tree CPI in our product, and trying to figure out the process and the timeline. According to [KEP 2395](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers#removing-in-tree-cloud-provider-code), in Phase 3, "A plan to migrate existing clusters from using the kube-controller-manager to the cloud-controller-manager is currently being developed." Is it the newest status of azure? I guess yes because I didn't find any guide about this...
The second question is, in [KEP 2395](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers#removing-in-tree-cloud-provider-code), in Phase 4, I noticed two feature gates DisableCloudProviders and DisableKubeletCloudCredentialProvider are provided, and when in GA stage, we should finished migrating from in-tree to out-of-tree. For my understanding, this is the deadline of migration. One release after GA, the in-tree code will be removed. Please correct me if I'm wrong. Will azure follow this process? I heard some cloud providers will remove code before the two feature gates GA, so I'd like to make it clear on azure. 
Third, is there any info about the overall timeline about when migration plan is ready , when we cannot use in-tree cpi, when to remove code....?
Thanks!

**Comment by nilo19** [comment]
The plan and development of the migration are managed by sig cloud-provider, and I'm not sure if there will be an automatic migration tool in the future after Phase 3. But if you want to use out-of-tree cloud provider azure, you can try it now, as it has been GAed. Ref: https://cloud-provider-azure.sigs.k8s.io/install
Also, cluster provisioning tools such as aks-engine (deprecated) and capz also support creating a cluster with out-of-tree cloud provider azure.

**Comment by wangyuan0916** [comment]
Hi @nilo19 Thank you for your reply! What is the plan to remove code of in-tree azure CPI? I'm asking this because I'd like make sure the deadline of using in-tree azure CPI and make plan to migrate from in-tree to out-of-tree.
I think I don't need the automatic migration tool, but a guide about what is the procedure when migrating, especially the HA cluster in which unavailability of control plane cannot be tolerated. I can see that the k8s community is prepared for that by offering [Leader Migration](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/), but it also needs implementation from cloud provider, is Azure prepared for that?

**Comment by nilo19** [comment]
The migration plan is managed by sig cloud-provider or cloud-provider-extraction, I'm not sure which. You can ask them in the slack channel.

**Comment by wangyuan0916** [comment]
how about the implementation of leader migration feature? It needs the support of cloud provider azure.

**Comment by feiskyer** [comment]
leader migration is not implemented by Azure cloud provider, we suggest customers migrate to ccm when upgrading the cluster version.

**Comment by wangyuan0916** [comment]
Hi @feiskyer, we are going to upgrade clusters and together with migrating cloud provider to out-of-tree. These clusters are HA clusters, we don't want downtime in control plane during upgrading or migrating, are there any ideas about this?
