### ISSUE TITLE
LoadBalancerSku should default to Standard

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cloud-provider-azure#2414]
ClusterConfig defaults loadBalancerSku to `basic`: https://cloud-provider-azure.sigs.k8s.io/install/configs/#cluster-config.

> On 30 September 2025, Basic SKU public IP addresses will be retired in Azure. You can continue to use your existing Basic SKU public IP addresses until then, however, you'll no longer be able to create new ones after 31 March 2025.

Basic SKU is being retired. We should not be defaulting to basic for LB and public IP SKUs.

Standard SKU public IP addresses offer significant [improvements](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses#sku), including:

- Access to a variety of other Azure products, including Standard Load Balancer, Azure Firewall, and NAT Gateway.
- Security by default—closed to inbound flows unless allowed by a network security group.
- Zone-redundant and zonal front ends for inbound and outbound traffic.

Even if the retirement date is 3 years away, we should consider making this change now as the default value should reflect the recommended best practices in Azure.

**Comment by feiskyer** [comment]
@CecileRobertMichon thanks for raising this issue. Are there any graceful update support plans in capz or aks-engine?

**Comment by CecileRobertMichon** [comment]
CAPZ never supported basic LBs. AKS Engine will be deprecated long before the retirement.

/cc @bridgetkromhout
