### ISSUE TITLE
Stop using deprecated labels in cloud-node-manager since v1.26.0

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#2453]
#### What would you like to be added:

beta.kubernetes.io/instance-type
failure-domain.beta.kubernetes.io/region
failure-domain.beta.kubernetes.io/zone are still applied on nodes by cloud-node-manager
According to https://learn.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels, they have been deprecated since v1.25.0. We should avoid using them since v1.26.0.

**Comment by Bryce-Soghigian** [comment]
Would this be a good first issue to pick up?

**Comment by nilo19** [comment]
Yes, we need to delete them.

**Comment by Bryce-Soghigian** [comment]
I ended up submitting a pull request removing all of those labels from being added to the Nodes inside of nodemanager

**Comment by JoelSpeed** [comment]
Is there a recommended way to migrate these labels in an automated fashion? I've seen many different discussions about these labels (eg as part of CSI migration) and most folks seem to be leaning towards not removing them yet as we haven't got the migration sorted. While labels are deprecated in Kubernetes, the actual removal of the labels takes a very long time (note the labels for zone/region were deprecated in 1.17 and yet are still added by CCMs other than Azure in 1.26).

It would be great if there was a way to allow users to choose to extend the lifecycle of these annotations? Do you think it would be appropriate to revert the PR that fixed this and introduce a flag that, by default, disables the reconciliation, but allows folks who aren't ready to migrate, to maintain the old behaviour? Something like `--sync-deprecated-labels`
