### ISSUE TITLE
Can you use a single IP for multiple services? I received a CreateContainerError when I closed and reused 

### ISSUE THREAD

**Issue by xtianus79** [kubernetes-sigs/cloud-provider-azure#2544]
I am using AKS I have an IP that I was using for a redis cluster and I had it also using an ingress controller for another deployment. Everything worked fine. When I removed the ingress deployment and used the IP for another deployment my redis container failed with the change for no reason.  

```
    State:          Waiting
      Reason:       CreateContainerError
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 25 Sep 2022 09:53:35 -0400
      Finished:     Sat, 15 Oct 2022 19:54:07 -0400
    Ready:          False
```
Are you able to use a single ip with multiple services or perhaps this was from a different issue. I had to reinstall the redis server in order to get it working again. I can't really tell what the issue was. Perhaps it was too many resources towards the new deployment but I don't see why that would affected an entirely other service running. 

Here is a [github ](https://github.com/MicrosoftDocs/azure-docs/issues/57030)that says the issue was there before but now you can use a single IP for multiple services. I am not sure where the error derived from.

**Comment by jwtty** [comment]
It's possible to share one public ip among multiple services. Do you see any errors when you describe your service?

**Comment by nilo19** [comment]
Yes, we are able to do that. https://cloud-provider-azure.sigs.k8s.io/topics/shared-ip/
