### ISSUE TITLE
Prevent storage account secret deletion when there are still PVs refer storage entities

### ISSUE THREAD

**Issue by JunSun17** [kubernetes-sigs/cloud-provider-azure#258]
**Is your feature request related to a problem?/Why is this needed**
We see a case that customer provisioned a PV using AzureFile, and the storage account secret is deleted before the PV is being deleted. In this case, PV will report an error when delete:

Failed to create deleter for volume xyz: Couldn't get secret ns/abc

The workaround is to comment out the finalizers in PV, then deletion goes through.

**Describe the solution you'd like in detail**
If possible, we would like to have secret to be aware of entities which refers it. So when delete a secret, it will check if all entities referring it has been deleted as a pre-requirement. Probably something like a finalizes for secret object which contains such dependency information, and is required to return success before a secret can be deleted. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andyzhangx** [comment]
this is a new KEP for k8s secret finalizer, not related to azure cloud provider
