### ISSUE TITLE
cloud-controller-manager pods - ImagePullBackOff Error in Azure Stack Hub - Azure AKS 1.20.11

### ISSUE THREAD

**Issue by zohebs341** [kubernetes-sigs/cloud-provider-azure#2583]
Hi Team,

By using aks-engine, I've deployed azure aks 1.20.11 in Azure stack Hub. However, cloud-controller-manage pods are not coming up with ImagePullBackOff error.

Please check and assist. As I am a new user of Azure Stack Hub, appreciate your support on this.

Logs:

 kubectl describe po cloud-controller-manager-k8s-master-63284788-0 -n kube-system
Name:                 cloud-controller-manager-k8s-master-63284788-0
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 k8s-master-63284788-0/10.240.255.5
Start Time:           Wed, 19 Oct 2022 17:07:21 +0000
Labels:               component=cloud-controller-manager
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: 0fc7592f6150c08bd42b13d2916a6013
                      kubernetes.io/config.mirror: 0fc7592f6150c08bd42b13d2916a6013
                      kubernetes.io/config.seen: 2022-10-19T17:07:20.048628403Z
                      kubernetes.io/config.source: file
                      kubernetes.io/psp: privileged
Status:               Pending
IP:                   10.240.255.5
IPs:
  IP:           10.240.255.5
Controlled By:  Node/k8s-master-63284788-0
Containers:
  cloud-controller-manager:
    Container ID:
    Image:         mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.1.1-azs
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      cloud-controller-manager
    Args:
      --allocate-node-cidrs=true
      --cloud-config=/etc/kubernetes/azure.json
      --cloud-provider=azure
      --cluster-cidr=10.244.0.0/16
      --cluster-name=azstack
      --configure-cloud-routes=true
      --controllers=*,-cloud-node
      --kubeconfig=/var/lib/kubelet/kubeconfig
      --leader-elect=true
      --route-reconciliation-period=10s
      --v=2
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  2Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      AZURE_ENVIRONMENT_FILEPATH:  /etc/kubernetes/azurestackcloud.json
      AZURE_GO_SDK_LOG_LEVEL:      INFO
    Mounts:
      /etc/kubernetes from etc-kubernetes (rw)
      /etc/ssl from etc-ssl (ro)
      /var/lib/kubelet from var-lib-kubelet (rw)
      /var/lib/waagent/ManagedIdentity-Settings from msi (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  etc-kubernetes:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes
    HostPathType:
  etc-ssl:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl
    HostPathType:
  var-lib-kubelet:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet
    HostPathType:
  msi:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/waagent/ManagedIdentity-Settings
    HostPathType:
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute op=Exists
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Normal   Pulling  59m (x301 over 26h)     kubelet  Pulling image "mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.1.1-azs"
  Warning  Failed   19m (x6854 over 26h)    kubelet  Error: ImagePullBackOff
  Normal   BackOff  4m17s (x6919 over 26h)  kubelet  Back-off pulling image "mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.1.1-azs"

# kubectl get pods -n kube-system | grep -i cloud-controller-manage
cloud-controller-manager-k8s-master-63284788-0   0/1     ImagePullBackOff   0          26h
cloud-controller-manager-k8s-master-63284788-1   0/1     ImagePullBackOff   0          26h
cloud-controller-manager-k8s-master-63284788-2   0/1     ImagePullBackOff   0          26h

**Comment by nilo19** [comment]
The aks-engine has been deprecated, please use cluster api instead.
