### ISSUE TITLE
Support "dynamic" environments

### ISSUE THREAD

**Issue by jadarsie** [kubernetes-sigs/cloud-provider-azure#259]
**Is your feature request related to a problem?**

Azure and Azure Stack clouds expose the _same_ set of APIs that the cloud provider consumes. For public and government clouds, go-autorest defines a set of cloud `Environment` instances (one per cloud). Each of this is basically a list of endpoints required by the azure-sdk-for-go. 

With Azure Stack, enterprises are required to use their own domain. Therefore, the environment endpoints must be derived from the cloud’s “metadata endpoint”:

- Azure: https://management.azure.com/metadata/endpoints?api-version=1.0 
- Azure Stack: https://management.{location}.{domain}/metadata/endpoints?api-version=1.0 

**Describe the solution you'd like in detail**

It would be great if we could call go-autorest’s `EnvironmentFromURL` function from the cloud provider code base. This will allow us to dynamically generate the required set of endpoints.

Function `EnvironmentFromURL` takes the ARM management endpoint URI as input: `https://management.{location}.{domain}`. This should be easily achieved by adding an extra field to `azure.json`.

We can either pass `domain` (and derive the management endpoint URI) or directly pass the management endpoint URI. I think I prefer the first option (@feiskyer @aramase please comment if that's not your preference).

**Why is this needed**

Benefits are simplicity and consolidation. 

Currently, AKSe is computing the environment endpoints, dropping a json file on each node, mounting the json file into kubelet/ccm, setting `AZURE_ENVIRONMENT_FILEPATH` and passing the variable to kubelet/ccm.

Without this feature, we will have to re-implemente the process above to make Cluster API work on Azure Stack.

**Comment by feiskyer** [comment]
@jadarsie would you like to create a PR and add this feature?

**Comment by jadarsie** [comment]
Yep, will do.

**Comment by feiskyer** [comment]
@jadarsie thanks

**Comment by vpatelsj** [comment]
Dynamic endpoints will also help setting up non-public clouds as well as setting up test infrastructure for mocking azure apis for auto-remediation components that work with arm api's directly.
