### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/cloud-provider-azure#265]
**What happened**:
These jobs frequently fail.
- provider-azure-master#ci-cloud-provider-azure-multiple-zones  
-  provider-azure-master#cloud-provider-azure-slow-vmss 

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
@ritazh @chewong this is still not fixed yet, right?

**Comment by chewong** [comment]
No, it's not fixed yet. Looks like it's a duplicate of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/264.
