### ISSUE TITLE
we should support sharing one public ip address by multiple services.

### ISSUE THREAD

**Issue by andyliuliming** [kubernetes-sigs/cloud-provider-azure#267]
**Is your feature request related to a problem? Please describe.**

Cloud provider doesn't support sharing same Public IP for different services because of the following reasons:

* Cloud provider would create different Frontend IP configurations for different services
* Azure LoadBalancer doesn't support referring the same Public IPs on different Frontend IP configurations 

**Describe the solution you'd like in detail**

Support sharing the same public IP for multiple services.

**Describe alternatives you've considered**

We are doing it by manually editing the load balancer rules, but it caused some racing issues.

**Additional context**

**Comment by nilo19** [comment]
- [ ] feature PR: https://github.com/kubernetes/kubernetes/pull/94991
- [ ] e2e tests
- [ ] docs

**Comment by feiskyer** [comment]
https://github.com/kubernetes/kubernetes/pull/94991 would be part of k8s v1.20.0

**Comment by CecileRobertMichon** [comment]
@feiskyer @nilo19 how come this one got implemented directly in k/k as a feature without being merged in out of tree first? 

cc @jsturtevant

**Comment by feiskyer** [comment]
@CecileRobertMichon new features are added in k/k <=1.20, while new features are only added in CCM >=1.21.

**Comment by CecileRobertMichon** [comment]
Was this one backported in out-of-tree yet? We're seeing https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1347 with in-tree but not out-of-tree

**Comment by nilo19** [comment]
Yes, it has been supported in out-of-tree as well. https://kubernetes-sigs.github.io/cloud-provider-azure/topics/shared-ip/
