### ISSUE TITLE
Add liveness probe in example manifests

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#271]
**What happened**:

Ported from #222. Let's add the example of liveness and health probes in example manifests.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cpanato** [comment]
This is still needed? Can I work on that?

**Comment by feiskyer** [comment]
@cpanato yep, of course

/unassign @aramase 
/assign @cpanato
