### ISSUE TITLE
Add support for security group in a separate resource group

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cloud-provider-azure#281]
Currently, having a network security group in a different RG as the cluster VMs/Load Balancers (ie. in the same RG as the vnet) results in: `Error syncing load balancer: failed to ensure load balancer: nsg "control-plane-nsg" not found` when trying to expose a service. https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#cluster-config has a `vnetResourceGroup` but nothing about NSG resource group.

Add a `securityGroupResourceGroup` property to handle cases where the cluster NSG is in a separate RG.

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/87035, https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/356
