### ISSUE TITLE
Azure Private Link Service Integration

### ISSUE THREAD

**Issue by AgSync-Aaron** [kubernetes-sigs/cloud-provider-azure#2876]
What does any of this mean? This is from the docs, but there is no explanation what-so-ever. Does this register DNS entries? Is this for some kind of authorization? Specifically, what does `associated` mean in the docs?

<html>
<body>

service.beta.kubernetes.io/azure-pls-fqdns | "fqdn1 fqdn2" | A space separated list of fqdns associated with the PLS.
-- | -- | --

</body>
</html>

**Comment by nilo19** [comment]
@jwtty can you answer this one?

**Comment by AgSync-Aaron** [comment]
Thanks @jwtty & @nilo19 for looking into it. Like you I was unable to find any good information.

**Comment by CrisNevares** [comment]
Bump. I cannot find any documentation describing what the `service.beta.kubernetes.io/azure-pls-fqdns` annotation does precisely and what it means for an fqdn to be `associated` to the pls

**Comment by vzabawski** [comment]
I also can't understand what this annotation does.
