### ISSUE TITLE
Mixed protocols doesn't work on Azure

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#295]
Annotation `service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"` is added to support mixed protocols on Azure. With the annotation set on LoadBalancer services, the LoadBalancer rules are indeed created on Azure LoadBalancer. But iptables rules are only created for the protocol set from service spec (only TCP or UDP iptables rules on each node). Hence, the annotation doesn't actually work.

Since the iptables rules are managed by kube-proxy, we couldn't make any changes from cloud provider. Would pending for https://github.com/kubernetes/enhancements/pull/1438 to support this feature.

/kind bug

**Comment by feiskyer** [comment]
pending on https://github.com/kubernetes/kubernetes/pull/94028

**Comment by nilo19** [comment]
```
The usage of mixed protocol values in the same LoadBalancer Service is possible if the new feature gate MixedProtocolLBService is enabled.
"action required"
The feature gate is disabled by default. The user has to enable it for the API Server.
```
Shall we close this since it would be supported in 1.20.

**Comment by feiskyer** [comment]
> Shall we close this since it would be supported in 1.20.

@nilo19 have you validated it?

**Comment by nilo19** [comment]
as discussed, we would remove the mixed protocol annotation.

**Comment by feiskyer** [comment]
To be clear, the mixed protocol has been supported since v1.20 from Kubernetes API (no extra annotation is required).
