### ISSUE TITLE
CPI should be defined as daemonset (vs. deployment)

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes-sigs/cloud-provider-azure#3005]
#### What happened:

To scale the external CPI the same way as previously done when the reconciliation was done in the `kubernetes-controller-manager` it's required to reflect the number of control-plane nodes to the system which applies the CPI deployment.

As some of the other cloud-providers are defining the CPI as Daemonset (and bind it to the control-plane nodes), we've forked the CPI deployment and converted it into a `Daemonset` (xref: [azure-cpi as daemonset](https://github.com/giantswarm/azure-cloud-controller-manager-app/blob/main/helm/azure-cloud-controller-manager-app/templates/daemonset.yaml)). With that we don't have to take care about the number of control-plane nodes when the CPI got applied towards a workload cluster.

#### Anything else we need to know?:

as already discussed in this [slack thread in #provider-azure](https://kubernetes.slack.com/archives/C5HJXTT9Q/p1671546029638159), the issue was intended to keep the discussion/decision more public in a github repo than in the slack thread.

`Daemonset` spec of other CPI providers:
* [aws daemonset spec](https://github.com/kubernetes/cloud-provider-aws/blob/master/charts/aws-cloud-controller-manager/templates/daemonset.yaml)
* [openstack daemonset spec](https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml)
* [alibaba daemonset spec](https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/deploy/v2/cloud-controller-manager.yaml#L118)
* [vsphere daemonset spec](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/manifests/controller-manager/vsphere-cloud-controller-manager-ds.yaml)

`Deployment` spec of other CPI providers:
* [huawei-cloud deployment spec](https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/blob/master/docs/example-manifests/huawei-cloud-controller-manager.yaml#L133-L134)
* [bauducloud deployment spec](https://github.com/kubernetes-sigs/cloud-provider-baiducloud/blob/master/docs/example-manifests/cce-cloud-controller-manager-deployment.yaml#L143)

**Comment by feiskyer** [comment]
It's not necessary to run CPI as daemonset, as there is leader elections and only one replica would be selected to be running.
