### ISSUE TITLE
Deprecate service annotation service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#302]
**What happened**:

Annotation `annotation service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset` is added to disable tcp-reset for SLB loadbalancer rules. However, tcpreset should actually always be enabled, in order to avoid dropping packets silently.

See https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset for more details about SLB TCP Reset.

**What you expected to happen**:

`annotation service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset` would be deprecated in v1.18.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
Keep open until the annotation is removed.

/reopen

**Comment by cpanato** [comment]
Can I work on this when we open the branch for 1.20?

**Comment by feiskyer** [comment]
@cpanato thanks.the annotation should be removed per the todo https://github.com/kubernetes/kubernetes/blob/9fb34eddedca31c9e36b0adfeda6219a0efa6cb4/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L98.

/assign @cpanato

**Comment by MarcPow** [comment]
Apologies, @cpanato.  I didn't realize you'd specifically requested this one until I was preparing to post the PR.  My bad - I didn't mean to poach. 😧  [Note: I left references to the annotation in to produce a warning, but the maintainers may want a more complete removal.  If so, I'm happy to step back and leave it to you. 😄]

**Comment by cpanato** [comment]
@MarcPow  not a problem, you can continue on that
