### ISSUE TITLE
Service with type loadbalancer not working if a outbound lb with name diff than cluster name already exists frontending the same backend pool

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cloud-provider-azure#3087]
#### What happened:
When a workload cluster is created via cluster-api-provider-azure with AzureClusterName!=ClusterName and node outbound load balancer is opted, k8s service with type load balancer fails to route even if it gets a public IP assigned.

**PS: Using the in-tree cloud provider.**

#### What you expected to happen:
Service should route successfully.

#### How to reproduce it (as minimally and precisely as possible):
- Create a workload cluster via CAPZ so that AzureClusterName!=ClusterName
- Opt for out bound load balancer.
- Deploy a service of type load balancer. ( A simple nginx server with service of type load balancer can be used to test )
- The nginx server will not be accessible via the public IP

#### Anything else we need to know?:
- Node outbound load balancer is created whose name is the same as that of azure cluster name. ( by capz )

- When service of type LoadBalancer is created for an app, it creates a load balancer with the same name as cluster name. ( by in-tree cloud provider azure )

- Now this load balancer created for service cannot add backend bools as the one created by capz has already added the nodes in the backend pool. And the reason for this is Azure does not allow multiple load balancers of same type (public or internal) to be attached to the same backend pool.

- Now the the load balancer created for service is not able to attach backend pool causing the disconnect.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.23.6
- Cloud provider or hardware configuration: In-tree cloud provider
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonasingh46** [comment]
cc @andyzhangx

**Comment by feiskyer** [comment]
This is working as expected due to SLB limitations. Could you keep the ClusterName consistent so that the SLB could be shared by different services?
