### ISSUE TITLE
Improve unit test coverage with mock clients

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#310]
Since we have already switched to our own Azure clients with mocks, we should use mock clients to improve our unit test coverage.

/milestone v1.19

**Comment by nilo19** [comment]
/assign 
I'm working on it in cloud provider and cluster autoscaler provider azure.

**Comment by feiskyer** [comment]
done for cloud provider azure. Unit tests coverage has been improved to 86%
