### ISSUE TITLE
Kubectl azure auth module in external credential provider 

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/cloud-provider-azure#314]
As upstream community (sig-auth) is discussing to remove all the auth modules except oidc and exec in kubectl _eventually_, the ask is to migrate the [azure auth module](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure) to [KEP: External credential provider](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190711-external-credential-providers.md) which is available starting at v1.11 (beta).

This opportunity gives us a solution to implement more features (non-interactive login mode) and client side bug fixes with greater flexibility as it's no longer tied to in-tree kubectl.

Parent issue - https://github.com/Azure/container-compute-upstream/issues/91

**Comment by weinong** [comment]
implemented in https://github.com/Azure/kubelogin

**Comment by feiskyer** [comment]
Already been supported in https://github.com/Azure/kubelogin.

/close
