### ISSUE TITLE
Cloud provider Azure for kubernetes v1.18

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#315]
Meta issues to track kubernetes v1.18 work items.

- [x] Cut the version for v1.18
- [x] Build the release images including Windows images
- [x] Update release notes
- [x] Add out-of-tree cloud provider Azure in aks-engine
  - [x] cloud-controller-manager image and manifests update, which includes images update and Windows daemonset
- [ ] cluster-api-provider-azure support? (not a blocker)

**Comment by CecileRobertMichon** [comment]
@feiskyer we have https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/456 tracking adding support in capz, might need your help/guidance for it.

Is out-of-tree provider required with 1.18?

**Comment by feiskyer** [comment]
@CecileRobertMichon no, it is not required.  out-of-tree provider is still alpha with 1.18.

**Comment by feiskyer** [comment]
Already done in aks-engine.
