### ISSUE TITLE
Invalid API Version in v1.26.1 of Provider

### ISSUE THREAD

**Issue by rsmitty** [kubernetes-sigs/cloud-provider-azure#3153]
#### What happened:

Hi folks, hope you're well. I'm seeing what appears to be a bug with the cloud provider. I've installed v1.26.1 via Helm and, when running, I'm seeing the following failure when a LB service is created (nginx-ingress in this case):

```
I0113 17:57:59.762506       1 controller.go:386] Ensuring load balancer for service ingress-nginx/ingress-nginx-controller
I0113 17:57:59.763224       1 event.go:294] "Event occurred" object="ingress-nginx/ingress-nginx-controller" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I0113 17:57:59.763533       1 azure_loadbalancer.go:1535] reconcileLoadBalancer for service(ingress-nginx/ingress-nginx-controller) - wantLb(true): started
E0113 17:57:59.771975       1 azure_backoff.go:381] LoadBalancerClient.List() failure with err=&{false 400 0001-01-01 00:00:00 +0000 UTC {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2021-08-01' is invalid. The supported versions are '2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}}
```

I've deployed with the following overrides to the helm values, which seem fairly basic but there's not a ton of info about what's what in the repo.

```
        infra:
          clusterName: "ci-cluster"
        cloudControllerManager:
          cloudConfig: ''
          cloudConfigSecretName: azure-cloud-provider
          enableDynamicReloading: "true"
          configureCloudRoutes: "false"
          allocateNodeCidrs: "false"
          clusterCIDR: "192.168.0.0/17"
```

The cloud config secret itself looks like this, and seems to be working properly:

```
{
  "cloud":"AzurePublicCloud",
  "tenantId": "xxx",
  "subscriptionId": "xxx",
  "aadClientId": "xxx",
  "aadClientSecret": "xxx"
}  
```

#### What you expected to happen:

LBs are created as expected.

#### How to reproduce it (as minimally and precisely as possible):

Add cloud provider to cluster with configuration as set above.

#### Anything else we need to know?:

N/A

#### Environment:

- Kubernetes version (use `kubectl version`): 1.26.0
- OS (e.g: `cat /etc/os-release`): Talos Linux
- Kernel (e.g. `uname -a`): 5.15.86

**Comment by rsmitty** [comment]
Just another quick note, tried to do some extra due diligence here and redeployed the cluster with verification that all flags were set on kubelet and controller-manager, etc. Same result unfortunately :cry:

**Comment by feiskyer** [comment]
@rsmitty thanks for reporting. Which region are you using?

**Comment by feiskyer** [comment]
@rsmitty I validated the api-version should be supported in Virginia. Have you set `resourceGroup` and `location` parameters in your cloud config file?

Please also refer https://cloud-provider-azure.sigs.k8s.io/install/configs/ for a full config file sample.
