### ISSUE TITLE
cloud-provider-azure-ccm-windows-capz testgrid job is broken

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#3271]
#### Which jobs are failing:

cloud-provider-azure-ccm-windows-capz

#### Since when has it been failing:

It appears to have been failing since 25 Jan 2023

#### Reason for failure:

It seems that when we determine we need to build new ccm and cnm images (via capz) that we run into this error:

```
docker manifest create --amend franciscapzacr.azurecr.io/azure-cloud-node-manager:9ca2fa3 franciscapzacr.azurecr.io/azure-cloud-node-manager:9ca2fa3-linux-amd64 franciscapzacr.azurecr.io/azure-cloud-node-manager:9ca2fa3-windows-1809-amd64
franciscapzacr.azurecr.io/azure-cloud-node-manager:9ca2fa3-windows-1809-amd64 is a manifest list
make[1]: *** [manifest-node-manager-image-windows] Error 1
make: *** [manifest-node-manager-image-windows-1809-amd64] Error 2
```

For example:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-ccm-windows-capz/1618277709618614272

#### Anything else we need to know:

If the test determines that we *don't* need to build a new image, it appears to pass, which explains why we have successful runs after 25 January.

For example:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-ccm-windows-capz/1619002501678239744

**Comment by jackfrancis** [comment]
cc @CecileRobertMichon @marosset @jsturtevant

**Comment by marosset** [comment]
It looks like the last time the Makefile had updates to the manifest creation was July 2022

https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2026

Do we know if something changes to cause this issue to show up now or could this have always been an issue?
It looks like the only commits that went into the cloud-provider-azure repo around when the failure started were dep updates performed by dependabot.

**Comment by jackfrancis** [comment]
@marosset what are some other testgrid jobs where we do JIT windows image builds from the commit that the test is running from?

**Comment by feiskyer** [comment]
@lzhecheng could you have a look?

**Comment by lzhecheng** [comment]
/close
The pipeline is running well now.
There were some failures in Windows image building but they have been resolved, e.g. https://github.com/kubernetes-sigs/cloud-provider-azure/issues/3655
