### ISSUE TITLE
Labels of master node aren't set correctly by cloud-node-manager after upgrading

### ISSUE THREAD

**Issue by chewong** [kubernetes-sigs/cloud-provider-azure#331]
**What happened**:

**What you expected to happen**:

**How to reproduce it**:
https://github.com/Azure/aks-engine/issues/3090

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
The node initialize is only triggered on node register phase. Master node need to unregister and register again to get these labels updated.
