### ISSUE TITLE
[Action Required] Update references from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/cloud-provider-azure#3324]
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), projects within the Kubernetes orgs should update their image references to point to the new address.

**NOTE:** We can ignore references to staging-k8s.gcr.io, but any other references to k8s.gcr.io should be updated to registry.k8s.io

[k8s.gcr.io search results](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes-sigs/cloud-provider-azure) 

ref: [[Umbrella Issue] Migrate K8s projects from k8s.gcr.io -> registry.k8s.io](https://github.com/kubernetes/k8s.io/issues/4738)

/kind cleanup
/priority important-soon

**Comment by nikzayn** [comment]
@mrbobbytables Can you assign this issue to me, as I am a beginner to CNCF contribution?

**Comment by mrbobbytables** [comment]
@nikzayn I'm not an owner of this repo, I will leave triage to the maintainers of it.

**Comment by nikzayn** [comment]
Sure thing, I want to ask one thing this issue remarks that all references of **k8s.gcr.io** should be updated to **registry.k8s.io**. Why do we need to add this change, can you explain in brief or helpful links that I can refer to?

**Comment by mrbobbytables** [comment]
The blog posts linked in the issue explain it all 👍
