### ISSUE TITLE
when azure-allowed-service-tags is set, an inbound internet rule is still created on public load balancer

### ISSUE THREAD

**Issue by carlwoodhouse** [kubernetes-sigs/cloud-provider-azure#337]
**What happened**:
i set service.beta.kubernetes.io/azure-allowed-service-tags to AzureFrontDoor.BackEnd; this correctly sets an inbound rule in the nsg to my service for the service tag; however it also creates a rule for 0.0.0.0/0 Presumably this is because `loadBalancerSourceRanges` isnt set (which i thought was the point of the annotation ..)

**What you expected to happen**:
Just inbound rules for the listed service tag, not 0.0.0.0/0

**How to reproduce it**:
Create any service with the annotation of servicetype loadbalancer, look at the nsg.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15.11

**Comment by boundingboxes** [comment]
+1, seemingly impacts at least 1.16.8 too.

Any work around would be appreciated?

**Comment by feiskyer** [comment]
thanks for reporting, this is caused by a bug from cloud provider. @nilo19 would work on a fix

before that, could you add add an IP to `loadBalancerSourceRanges` as short term mitigation?

**Comment by carlwoodhouse** [comment]
> thanks for reporting, this is caused by a bug from cloud provider. @nilo19 would work on a fix
> 
> before that, could you add add an IP to `loadBalancerSourceRanges` as short term mitigation?

can confirm this is the workaround i am using too; it does work though clearly not ideal.
