### ISSUE TITLE
Update GO modules for cloud provider controllers

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#342]
**What happened**:

Since PR https://github.com/kubernetes/kubernetes/pull/90976, the cloud provider controllers are moved to `k8s.io/cloud-provider`. Hence, we should update Go modules with these new packages and hopefully simplify Go modules updating in out-of-tree cloud provider.

**What you expected to happen**:

Update GO modules for cloud provider controllers 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
should still wait a while for https://github.com/kubernetes/kubernetes/pull/91218.

**Comment by nilo19** [comment]
fixed by #348
