### ISSUE TITLE
Latest release container image not published

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cloud-provider-azure#3526]
#### What happened:
Tried to deploy latest release (1.24.16) but image could not be pulled:
```
  Warning  Failed     6s (x3 over 43s)   kubelet            Failed to pull image "mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.24.16": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.24.16": failed to resolve reference "mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.24.16": mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.24.16: not found
```

#### What you expected to happen:
Image is published when release is published.

#### How to reproduce it (as minimally and precisely as possible):
```
$ regctl tag ls mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager|grep 1.24.16
```

#### Anything else we need to know?:
Updated version in chart manually since helm chart is not updated automatically with each release (see #3280). 

#### Environment:

- Kubernetes version (use `kubectl version`): 1.24.11
- Cloud provider or hardware configuration: azure

**Comment by mboersma** [comment]
@mweibel unfortunately creating a release here on GitHub doesn't directly create the artifacts. Instead, an Azure DevOps pipeline job notices there is a new release and rebuilds the artifact internally, so we can ensure a secure build and sign the binaries before hosting them at mcr.microsoft.com.

The pipeline includes a strenuous set of tests, some of which failed on the first run, so no new container images are available yet. The cloud-provider and secure supply chain teams collaborate on fixing the issue, but it's kind of the "canary in the coalmine" for testing changes in several codebases so sometimes the issues aren't straightforward.

**Comment by mboersma** [comment]
That was just to explain how the current process works (as far as I can tell). But I agree that if somehow we could make the GitHub release simultaneous with the artifact publishing (and Helm chart update!) it would be better.

**Comment by feiskyer** [comment]
Thanks for reporting the issue. Yes, the MCR images are not published yet. @nilo19 is working on them.
