### ISSUE TITLE
Link to "cloud provider config" is broken on docs "Deploy Cloud Controller Manager" page

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cloud-provider-azure#3580]
On https://cloud-provider-azure.sigs.k8s.io/install/azure-ccm/#azure-cloud-controller-manager there is a link: [cloud provider config](https://cloud-provider-azure.sigs.k8s.io/install/configs.md), which returns 404.

**Comment by nikzayn** [comment]
@invidian I would like to take this up!

**Comment by invidian** [comment]
/remove-lifecycle stale

This still does not work :)
