### ISSUE TITLE
Azure Tags should be fowarded downstream

### ISSUE THREAD

**Issue by julienym** [kubernetes-sigs/cloud-provider-azure#365]
Actually the cloud provider doesn't have a list of tags that can be set on ressources created by it. (LB, disk, storage account)

Most other K8s cloud provider offer this.

Thanks

**Comment by andyzhangx** [comment]
@julienym we already added tags support for disk, file drivers, is that what your want?
https://github.com/kubernetes/kubernetes/pull/92825
https://github.com/kubernetes/kubernetes/pull/92356

Also could you list the offering link of other K8s cloud provider? thanks.

**Comment by julienym** [comment]
Thanks, if I'm wrong, this is available for k8s 1.19+ only ?

For the other cloud provider, one example is AWS LB: https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers

I mainly need to storage so your links help, thanks!

**Comment by andyzhangx** [comment]
> Thanks, if I'm wrong, this is available for k8s 1.19+ only ?
> 
> For the other cloud provider, one example is AWS LB: https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers
> 
> I mainly need to storage so your links help, thanks!

@julienym tags are supported in 1.19 for the in-tree drivers, and also supported on latest version for Azure File & Disk CSI drivers:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md

**Comment by nilo19** [comment]
All resources created by provider azure are supported to be tagged as configured in the cloud config file. Doc: https://kubernetes-sigs.github.io/cloud-provider-azure/topics/tagging-resources/.
