### ISSUE TITLE
Image building job is failing for not found image

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#3655]
#### Which jobs are failing:
post-cloud-provider-azure-push-images
#### Which test(s) are failing:
Building windows CNM.
#### Since when has it been failing:
The time this PR is merged.
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3555
#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-provider-azure-push-images/1640148615437488128
#### Reason for failure:
gcr.io/k8s-staging-e2e-test-images/windows-servercore-cache:1.0-linux-amd64-ltsc2019 not found.

**Comment by lzhecheng** [comment]
The root cause of this recent failure is in this PR: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3555. It bumps from 1809 to ltsc2019 while such image doesn't exist. There're only 1809 and ltsc2022 now
https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-windows-servercore-cache/1629572995020230656/artifacts/build.log
https://github.com/kubernetes/kubernetes/blob/ecd543be044f82b721ffaa1909f5a4fefe458a64/test/images/windows-servercore-cache/BASEIMAGE#L2
I created a PR to add ltsc2019: https://github.com/kubernetes/kubernetes/pull/116935

**Comment by jsturtevant** [comment]
@lzhecheng we might need to revert #3555 or use the 1809 tag until we can merge things upstream in k/k again.  

out of curiosity, why is netapi32.dll needed from the server cache image (this is in servercore image which is another option but could be slower pull times)?

**Comment by lzhecheng** [comment]
@jsturtevant let's revert it.
Yes, because windows-servercore-cache is a smaller image and it makes pulling faster.

**Comment by lzhecheng** [comment]
/close
The issue has been resolved for cloud-provider-azure.
