### ISSUE TITLE
Remove Windows SAC images from container builds

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#3665]
#### What would you like to be added:
For mcr.microsoft.com/windows/nanoserver, replace version 1809 with ltsc2019. Right now, windows-servercore-cache image doesn't have ltsc2019 version and the change is pending.
My PR in k/k to add ltsc2019: https://github.com/kubernetes/kubernetes/pull/116935
Reverted PR: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3555
#### Why is this needed:

cc @marosset @jsturtevant

**Comment by bridgetkromhout** [comment]
PR in progress being evaluated

/remove-lifecycle stale
