### ISSUE TITLE
VMSS + IPv6 backend address pool deletion failure

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#3707]
#### What happened:
When `ensureBackendPoolDeletedFromVMSS`, the IPv6 backendAddressPool is not deleted, which leads to "child resources <IPv6-backendAddressPool> are in use by virtual machine scale set" error. An example:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3398/pull-cluster-api-provider-azure-e2e/1643851112475791360/artifacts/clusters/capz-e2e-17k4mh-ipv6/kube-system/cloud-controller-manager-5fcf8dbddb-qf57j/cloud-controller-manager.log
#### What you expected to happen:
IPv6 backendAddressPool is deleted from VMSS.

#### How to reproduce it (as minimally and precisely as possible):
Test on a IPv6 + VMSS cluster.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lzhecheng** [comment]
Current investigation shows that in an IPv6 cluster, the primary `ipConfigurations` is still IPv4, so the deletion fails.
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/4554e85fb5030838494aaec79e554dc136fdf4a3/pkg/provider/azure_vmss.go#L1592

**Comment by lzhecheng** [comment]
Related: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3361
/cc @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
> For a IPv6 cluster, VMSS primary NIC's primary IP config is always IPv4, right?

correct
