### ISSUE TITLE
Support multiple Standard LoadBalancer in the same cluster

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#380]
**Is your feature request related to a problem? Please describe.**

Support multiple Standard LoadBalancer in the same cluster, which would allow us to

* Select different SLB for different node pools
* Support more LoadBalancer services (there is maximum request size of 4 MB limit from ARM)
* Setup different outbound IPs on different SLB

**Describe the solution you'd like in detail**

Allow different nodepool (e.g. VMSS or VMAS) to use different standard LoadBalancer (just like what we have for basic LoadBalancer).

**Describe alternatives you've considered**

**Additional context**

/kind feature
/milestone v1.20

**Comment by nilo19** [comment]
design proposal: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/407
