### ISSUE TITLE
Change `clusterCIDR` in Helm chart from a string to an array value

### ISSUE THREAD

**Issue by Jont828** [kubernetes-sigs/cloud-provider-azure#3821]
#### What would you like to be added:

For the field `cloudControllerManager.clusterCIDR` in the Helm chart to be converted to a list instead of a comma separated string.

#### Why is this needed: 

Given that this is supposed to be a list of CIDRs, it's confusing that it doesn't use the list type.

**Comment by nikzayn** [comment]
@Jont828 I would like to take this up, but first, confirm I need to update **clusterCIDR** from **string** datatype to array of strings 
 -> **[]string{}** 
 
 /assign

**Comment by Jont828** [comment]
@nikzayn Sorry for the late reply, but yes, I'd like to have `clusterCIDR` updated from a `string` datatype to `[]string`. This field is currently set like this

```
cloudControllerManager.clusterCIDR: "cidr1,cidr2,cidr3"
```

but I would like to be able to set it like this.

```
cloudControllerManager:
  clusterCIDR:
    - cidr1
    - cidr2
    - cidr3
```
