### ISSUE TITLE
VMSS Instances are not getting added as part of the backendaddresspool

### ISSUE THREAD

**Issue by aroramanish080282** [kubernetes-sigs/cloud-provider-azure#384]
Question:
This setup is a self-managed/hosted K8s and CCM changes for Azure vendor support. Existing/New VMSS Instances are not getting added automatically as part of the Kubernetes_internal backendaddresspools. 
 
Setup: VMSS + Kubernetes(Microk8s) + CCM Changes
 
Problem: 
 
Warning   SyncLoadBalancerFailed    service/nginx-svc    Error syncing load balancer: failed to ensure load balancer: ensure(default/nginx-svc): backendPoolID(/subscriptions/<subscription_id>/resourceGroups/amitestaug/providers/Microsoft.Network/loadBalancers/kubernetes-internal/backendAddressPools/kubernetes) - failed to ensure host in pool: "instance not found"”
 
Warning  SyncLoadBalancerFailed        37s (x7 over 8m42s)    service-controller         Error syncing load balancer: failed to ensure load balancer: ensure(cwpp/cwppbroker): backendPoolID(/subscriptions/<subscription_id>/resourceGroups/amitestaug/providers/Microsoft.Network/loadBalancers/kubernetes-internal/backendAddressPools/kubernetes) - failed to ensure host in pool: "instance not found"
 
Idea of using VMSS is to scale up the cluster and hosted services running behind a load balancer. This is self-managed Kubernetes deployment and not AKS.
 
The Azure implementation of CCM maintained by Microsoft we referred is https://github.com/kubernetes-sigs/cloud-provider-azure which would be consumed by any CNCF certified distributions of K8s.

**What happened**:

New and Existing Instances of VMSS are not added automatically as part of the LB backendAddressPool/Kubernetes

**What you expected to happen**:
New and Existing Instance of the VMSS should get added automatically as part of the LB backendAddressPool/Kubernetes

**How to reproduce it**:
Create and configure VMSS and launch few instances + configure Kubernetes(Microk8s) + CCM Changes implemented

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): microk8s --channel=1.19 
- OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): Linux TrailMaster 5.3.0-1035-azure #36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by feiskyer** [comment]
@aroramanish080282 I'm not familiar with Microk8s setup, but could you confirm whether NodeName is the same as hostname for all the instances?

**Comment by aroramanish080282** [comment]
Yes, NodeName are same as the hostname for all the Instance. 

MicroK8s is a CNCF certified upstream Kubernetes deployment that runs entirely on your workstation or edge device. Being a snap it runs all Kubernetes services natively (i.e. no virtual machines) while packing the entire set of libraries and binaries needed.
