### ISSUE TITLE
Windows: Cloud Node Manager in CrashloopBackoff 

### ISSUE THREAD

**Issue by rahulgupta999** [kubernetes-sigs/cloud-provider-azure#3862]
. NA

#### What happened:
This issue is similar to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1807. Since that cannot be reopened, I am requesting a new issue.
The issue is seen on Windows, where the cloud node manager goes into a crashloopbackoff for every node joining the cluster. This delays the overall node readiness

Log for the cloud-node-manager windows is as follows:
------------------------
Running C:\hpc\/cloud-node-manager.exe  --node-name=cxp-workl-p5szn --use-instance-metadata=true --kubeconfig=C:\hpc\/var/lib/cpaw/kubeconfig.conf invalid configuration: unable to read certificate-authority C:\hpc\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt for default due to open C:\hpc\var\lib\cpaw\var\run\secrets\kubernetes.io\serviceaccount\ca.crt: The system cannot find the path specified.
--------------

The cluster is created using CAPI+CAPZ. The cloud-node-manager on windows fails a few times before it starts working. The container restarts 3-4 times with the above error then it automatically starts working.

#### What you expected to happen:
I expect the cloud node manager to boot-up and be ready in one go. 

#### How to reproduce it (as minimally and precisely as possible):
Follow the cluster API quick start book to provision a cluster using Azure Provider on Windows. Install the cloud-node-manager Helm chart.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.25.7
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): windows 2022
- Kernel (e.g. `uname -a`): windows server 2022
- Install tools: CAPI and CAPZ (latest)
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by feiskyer** [comment]
It seems the path of ca.crt is not correct. Are you using helm chart to deploy the cloud provider, or just running it as a host process?
