### ISSUE TITLE
Nodes not deleted after VMs are deleted

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#3921]
#### What happened:

Nodes are not getting deleted after their VMs (not VMSS instances) are deleted.

#### What you expected to happen:

I would expect that nodes will eventually get cleaned up when they no longer point to a valid VM.

#### How to reproduce it (as minimally and precisely as possible):

I built a CAPZ cluster with a Linux MachineDeployment (this uses VMs, not VMSS). I installed cluster-autoscaler, and scaled out the cluster to around 30 nodes. After I removed pods, the cluster scaled back in, but two `NotReady` nodes were left around.

#### Anything else we need to know?:

```sh
$ k get nodes -o wide
NAME                                     STATUS     ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION      CONTAINER-RUNTIME
capz-e2e-dskz4                           Ready      <none>          22h   v1.25.9   10.1.0.7      <none>        Windows Server 2019 Datacenter   10.0.17763.4252     containerd://1.6.20
capz-e2e-hlvn2                           Ready      <none>          22h   v1.25.9   10.1.0.6      <none>        Windows Server 2019 Datacenter   10.0.17763.4252     containerd://1.6.20
capz-e2e-xmsbq0-ha-control-plane-4vj9s   Ready      control-plane   22h   v1.25.9   10.0.0.4      <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
capz-e2e-xmsbq0-ha-control-plane-6dsw5   Ready      control-plane   22h   v1.25.9   10.0.0.6      <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
capz-e2e-xmsbq0-ha-control-plane-g6scw   Ready      control-plane   22h   v1.25.9   10.0.0.5      <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
capz-e2e-xmsbq0-ha-md-0-6j79q            NotReady   <none>          17h   v1.25.9   10.1.0.57     <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
capz-e2e-xmsbq0-ha-md-0-ht4dz            NotReady   <none>          17h   v1.25.9   10.1.0.59     <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
capz-e2e-xmsbq0-ha-md-0-zxrqm            Ready      <none>          17h   v1.25.9   10.1.0.62     <none>        Ubuntu 22.04.2 LTS               5.15.0-1035-azure   containerd://1.6.20
```

Note the nodes `capz-e2e-xmsbq0-ha-md-0-6j79q` and `capz-e2e-xmsbq0-ha-md-0-ht4dz` above.

The NotReady nodes don't have any providerID data at all. The Ready node does. See:

```sh
$ k get node capz-e2e-xmsbq0-ha-md-0-zxrqm -o yaml | grep providerID
  providerID: azure:///subscriptions/aa3d3369-e814-4495-899d-d31e8d7d09ce/resourceGroups/capz-e2e-xmsbq0-ha/providers/Microsoft.Compute/virtualMachines/capz-e2e-xmsbq0-ha-md-0-zxrqm
$ k get node capz-e2e-xmsbq0-ha-md-0-6j79q -o yaml | grep providerID
$ echo $?
1
$ k get node capz-e2e-xmsbq0-ha-md-0-ht4dz -o yaml | grep providerID
$ echo $?
1
```

#### Environment:

- Kubernetes version (use `kubectl version`): v1.25.9
- Cloud provider or hardware configuration:
  - mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v1.25.12
  - mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.25.12
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by feiskyer** [comment]
@jackfrancis could you share the logs of cloud-controller-manager? Have you found some errors in the logs?

**Comment by feiskyer** [comment]
close for inactivity in multiple months. Feel free to re-open if you still have the problem.
/close
