### ISSUE TITLE
Issues with the NATGateway and the loadbalancer on Kubernetes 

### ISSUE THREAD

**Issue by aroramanish080282** [kubernetes-sigs/cloud-provider-azure#393]
This setup is a self-managed/hosted K8s and CCM changes for Azure vendor support. 
Azure VM running Microk8s with all the required CCM configuration changes. 

This VM is part of the private Subnet and connected with NATGateway. PublicIP is assigned on the NATGateway. I can see on loading kubernetes service launched with the required loadbalancer of basic SKU type and after that it got into Error Code "SubnetWithNatGatewatAndBasicSKUResourceNotAllowed"

Please advice on the below queries
1. Do we have annotations to change the loadbalancer type from basic to standard, If yes, request you to share the details

2. I have also observed a problem where we configure kubernetes Services on a VM configured in a AZ, The problem with LB was not able to add these VM/nodes as part of the Loadbalancer backendAddresspool. I have also observed the same problem with the VMSS
refer https://github.com/kubernetes-sigs/cloud-provider-azure/issues/384 for more details.

3. Adding NatGetway(Public IP) and Basic SKU LB and it ends up at "SubnetWithNatGatewatAndBasicSKUResourceNotAllowed", any configuration changes for the same?

**What happened**:
This VM is part of the private Subnet and connected with NATGateway. PublicIP is assigned on the NATGateway. I can see on loading kubernetes service launched with the required loadbalancer of basic SKU type and after that it got into Error Code "SubnetWithNatGatewatAndBasicSKUResourceNotAllowed"

**What you expected to happen**:
Should be able to configure the basic SKU Load balancer connect with the VM/Node configured with NATGateway

**How to reproduce it**:
Just a private subnet with the netgateway(having public ip) and kubernetes configured with CCM changes required for Azure ecosystem. On default loading of loadbalancer SKU type will be basic and this issue cane be observed.
 
**Anything else we need to know?**:

**Environment**:
Kubernetes version (use kubectl version): microk8s --channel=1.19
OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
Kernel (e.g. uname -a): Linux TrailMaster 5.3.0-1035-azure #36-Ubuntu SMP Thu Aug 6 09:21:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Install tools:
Others:

**Comment by deepakrbharadwaj** [comment]
On the first Item listed regarding having Standard load balancers, it is important that we support this else, the services exposed by LB cannot be configured for private link and there is no way to share services running on k8s across multiple vNET in a shared services model.
