### ISSUE TITLE
Exclude node from LoadBalancer doesn't work as expected

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#401]
**What happened**:

Exclude node from LoadBalancer only works when first time a node joins cluster, it doesn't work when apply the node label later.

e.g. when running `kubectl label node k8s-agentpool-86949660-0 node.kubernetes.io/exclude-from-external-load-balancers=true`, the node is still in LoadBalancer backend address pool.

**What you expected to happen**:

The node should be removed from LoadBalancer backend address pool.

**How to reproduce it**:

Run `kubectl label node <node-name> node.kubernetes.io/exclude-from-external-load-balancers=true` and then check LoadBalancer backend address pool list.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by nilo19** [comment]
- [ ] pr: https://github.com/kubernetes/kubernetes/pull/95519
- [ ] e2e tests
- [ ] docs
