### ISSUE TITLE
Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cloud-provider-azure#4038]
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-master-ipv6-vmss-capz

Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by feiskyer** [comment]
@lzhecheng is fixing the CI.

**Comment by lzhecheng** [comment]
PR to fix:
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3914
