### ISSUE TITLE
Enable configurable log verbosity for cloud-node-manager

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#4070]
#### What would you like to be added:

cloud-node-manager enables user-configurable log verbosity configuration (via the common `--v` flag). Let's do the same for cloud-node-manager

**Comment by lzhecheng** [comment]
/close
This issue has been resolved by this PR: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4111
