### ISSUE TITLE
CCM might be too sensitive to update the LB backend pool

### ISSUE THREAD

**Issue by gsxmax** [kubernetes-sigs/cloud-provider-azure#4200]
#### What would you like to be added:
CCM wait for some time to remove the NotReady node from the LB backend pool.

#### Why is this needed:
Usually, if one replica of the APIserver is scaling down or restarting, the node lease sent to that replicas will be lost, and the node is marked as NotReady and CCM will start to remove the node from the LB backend pool. However, that is not an actual node NotReady event, the following node lease would reach the ative APIserver and correct status in 1 minutes. We should avoid the LB backend updating under this scenario.

**Comment by JoelSpeed** [comment]
Which version of the provider are you observing this on?

**Comment by feiskyer** [comment]
related to #4230.

**Comment by nilo19** [comment]
fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4234
