### ISSUE TITLE
Configurable TCP Idle timeout limit does not match Azure limit

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/cloud-provider-azure#4360]
#### What happened:

Azure [documents](https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset#configurable-tcp-idle-timeout) that the load balancer tcp idle timeout is configurable between 4 minutes and 100 minutes.

If you use the `service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout` annotation on a service, and set the value to 100 minutes, an error is returned saying that the maximum value is 30 mins.

#### What you expected to happen:

100 minute value should be accepted and should be configured for the load balancer managed by the service.

#### Anything else we need to know?:

Code to update looks to be here, https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c18b82b3d48b7022455f3e3230af5de7fd4fb1a5/pkg/provider/azure_loadbalancer.go#L2634

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by feiskyer** [comment]
Thanks for reporting the issue. This is a bug we should fix.
