### ISSUE TITLE
Support Public IP Address  servicePublicIPAddress property through service annotation

### ISSUE THREAD

**Issue by TonyDou** [kubernetes-sigs/cloud-provider-azure#437]
**Is your feature request related to a problem? Please describe.**

We need to specify IPTags and servicePublicIPAddress property when creating the public IPs. Preferably, we want to create the load balancer service together with these IPs.
```json
        {
            "name": "ipv6name",
            "type": "Microsoft.Network/publicIPAddresses",
            "apiVersion": "2020-05-01",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "Standard"
            },
            "properties": {
                "publicIPAllocationMethod": "Static",
                "publicIPAddressVersion": "IPv6",
                "IpTags": [
                    {
                        "IpTagType": "<IpTagType>",
                        "Tag": "<IPTag-Name>"
                    }
                ],
                "servicePublicIPAddress": {
                    "id": "[resourceid('Microsoft.Network/publicIPAddresses/', 'ipv4name')]"
                }
            }
        }
```

**Describe the solution you'd like in detail**

We can consider to add a new Load Balancer service annotation to create with servicePublicIPAddress.
```
service.beta.kubernetes.io/azure-pip-service-pip
```
**Describe alternatives you've considered**

Creating the IPs beforehand and then reference to the resource names when deploying the load balancer service through annotations.

**Additional context**

**Comment by nilo19** [comment]
have you tried this annotation? https://github.com/kubernetes-sigs/cloud-provider-azure/blob/42b9965e8a4dc57b336ab028c3160f8120aaa5c0/pkg/provider/azure_loadbalancer.go#L86

**Comment by TonyDou** [comment]
I just tried on the latest kubernetes 1.20, the IPTags are supported now. This is awesome. 
But to make our scenario work, we need to setup the servicePublicIPAddress for the IPv6 address.

I will update this issue to only focus on servicePublicIPAddress.

**Comment by feiskyer** [comment]
@TonyDou I checked network API 2020-08-01 and didn't find the new property `servicePublicIPAddress`. Do you know which network API version supports this feature and when would it be available in Azure Go SDK?

**Comment by TonyDou** [comment]
2019-09-01 and later versions should support it. But it's a hidden and internal property. Supporting this property in azure-sdk-for-go is tracked in https://github.com/Azure/azure-sdk-for-go/issues/14465
