### ISSUE TITLE
Add CloudCIDRAllocator 

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#462]
**Is your feature request related to a problem?/Why is this needed**

/kind feature

**Describe the solution you'd like in detail**

Copied from https://github.com/kubernetes/kubernetes/issues/97835:  cloudCIDRAllocator is part of nodeipam, which allows cloud provider to allocate node CIDRs according to IP address aliases:

https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go#L55-L61

The current in-tree implementation is not exposed as an interface and it is under moving to out-of-tree. 

To support per-nodepool (VMSS or VMAS) nodeCIDR allocation, we should add allocator inside out-of-tree cloud provider Azure.

**Describe alternatives you've considered**

**Additional context**

/milestone v1.21

**Comment by nilo19** [comment]
- [x] decouple in-tree node ipam controller and enable range allocator (https://github.com/kubernetes-sigs/cloud-provider-azure/pull/511)
- [ ] implement cloud allocator (VMSS: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/539)
- [ ] docs
- [ ] e2e tests

/reopen
