### ISSUE TITLE
ELB Node Label PR (upstream k8s PR 95542) broke Windows + Availability Sets

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#505]
**What happened**:

This PR introduced several new flows and requirements for functional ELB behaviors:

https://github.com/kubernetes/kubernetes/pull/95542

I'll copy [this comment](https://github.com/kubernetes/kubernetes/pull/95542#pullrequestreview-584724351) below:

I have test data from 1.21.0-alpha clusters built by aks-engine that suggests this PR broke ELB creation for clusters running Windows availability sets. AKS Engine creates Windows NIC interfaces with a name like `1598k8s01nic-1`. The regex in the `nicIDRE` reference above expects an explicit `-nic-` suffix (note the `-` before `nic-1`).

See this go playground example that proves that the above regex fails the match length test:

https://play.golang.org/p/Eh63N6EAOsc

It will be hard to change the name of the NIC that Windows VMs are attached in the AKS Engine ARM template logic without breaking backwards compatibility. Would it be possible to change the NIC regex to:

`/subscriptions/(?:.*)/resourceGroups/(?:.+)/providers/Microsoft.Network/networkInterfaces/(.+)nic-(.+)/ipConfigurations/(?:.*)`

cc @marosset @jsturtevant @nilo19 @jadarsie @CecileRobertMichon @devigned

This took longer than normal to verify it should have to discover due to the fact that we don't have a lot of AvailabilitySet tests for Windows.

@chewong how are we testing Windows + Availability Set nodes upstream? We should probably target catching these symptoms earlier in the upstream tests themselves.

**What you expected to happen**:

I expect existing Windows + Availability Set implementations (e.g., aks-engine) to continue to work in 1.21

**How to reproduce it**:

Build an 1.21 cluster using an aks-engine configuration such as this one:

https://github.com/Azure/aks-engine/blob/master/test/e2e/test_cluster_configs/availabilityset.json

You will notice errors like these when you attempt to create an External Load Balancer:

```
E0205 21:59:19.463761       1 azure_loadbalancer.go:189] reconcileLoadBalancer(default/ingress-nginx-elb) failed: invalid ip config ID /subscriptions/<sub>/resourceGroups/kubernetes-westus2-25664/providers/Microsoft.Network/networkInterfaces/1147k8s01nic-0/ipConfigurations/ipconfig1
E0205 21:59:19.463862       1 controller.go:254] error processing service default/ingress-nginx-elb (will retry): failed to ensure load balancer: invalid ip config ID /subscriptions/<sub>/resourceGroups/kubernetes-westus2-25664/providers/Microsoft.Network/networkInterfaces/1147k8s01nic-0/ipConfigurations/ipconfig1
I0205 21:59:19.464713       1 event.go:291] "Event occurred" object="default/ingress-nginx-elb" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: invalid ip config ID /subscriptions/<sub>/resourceGroups/kubernetes-westus2-25664/providers/Microsoft.Network/networkInterfaces/1147k8s01nic-0/ipConfigurations/ipconfig1"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nilo19** [comment]
It should be fixed by https://github.com/kubernetes/kubernetes/pull/97635

**Comment by jackfrancis** [comment]
Thanks @nilo19, confirmed the fix by building from source!
