### ISSUE TITLE
CAPI protective Contract for Azure cloud provider changes

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cloud-provider-azure#507]
**Is your feature request related to a problem?/Why is this needed**

Lookin for some guidelines for using `cloud-provider-azure` , that are either test-or semantic oriented / i.e. a CAPI contract that we can enforce/use to review clloud provider changes 

**Describe the solution you'd like in detail**

A contract/cloud provider/e2e test that we can run for all CP AZure requiests that prevent CAPZ from being broken.

Case in point  https://github.com/kubernetes-sigs/cloud-provider-azure/issues/505#issuecomment-774483489.

Im not sure how we normally would enforce this though.

**Describe alternatives you've considered**

We could just test capi after cp changes, but, i suspect thats a long tail to find out.

**Additional context**

the root cause here was the vnic naming i think
```
I0205 20:32:49.146435       1 event.go:291] "Event occurred" object="default/ingress-nginx-elb" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: invalid ip config ID /subscriptions/aa3d3369-e814-4495-899d-d31e8d7d09ce/resourceGroups/kubernetes-westus2-80684/providers/Microsoft.Network/networkInterfaces/1598k8s01nic-1/ipConfigurations/ipconfig1"
```

I suppose this applies to both in tree and out of tree, right @CecileRobertMichon  ? 

# SELFISH REASON FOR FILING THIS ISSUE

I want CAPz to always work properly w diffferent cloud providers :)

**Comment by CecileRobertMichon** [comment]
cc @feiskyer @nilo19 @craiglpeters 
cc @devigned @nader-ziada @jackfrancis 

+1 it would be great to start a contract between cloud provider Azure and various infra provisioning tools of k8s on Azure (AKS, AKS Engine, CAPZ, openshift, giantswarm, etc) so we can define: 
- the expectations for infra provisioners in terms of what resources they should create and any requirements to be able to use the Azure cloud provider (eg. availability sets, load balancer SKUs, etc.)
- which resources Cloud Provider expects to be able to reconcile (wg. the external LB for services which often doubles as the outbound LB for nodes. ref https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1141)

Any changes to the contract should be documented, especially breaking changes.

In addition, to enforce the contract, we should run tests with various provisioners on PRs and/or in periodic jobs so that the tests don't assume a particular provisioning method (ie. AKS Engine).

**Comment by jayunit100** [comment]
@andrewsykim pointed me at https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/1771-versioning-policy-for-external-cloud-providers 

maybe its just a matter of getting the adherence to that hardened ?

**Comment by feiskyer** [comment]
That's a bug that has been fixed by https://github.com/kubernetes/kubernetes/pull/97635.

**Comment by CecileRobertMichon** [comment]
We discussed this issue at the Azure Cloud provider office hours yesterday, pasting notes here for visibility:

> Issue: Contract for Cloud Provider CAPI protective Contract for Azure cloud provider changes · Issue #507 · kubernetes-sigs/cloud-provider-azure (github.com)
> - Qi Ni fixed the issue Jack provided
> - The question raised in Jay’s issue is what guarantees can Azure Cloud provider make to ensure interop with which versions of Kubernetes
> - Cloud Provider should document exactly what assumptions it makes about Azure resources, so that tools can guarantee that they should work with a given version of Cloud Provider
> - Pengfei will document the assumptions in a contract: 
    - all resources in the same Azure tenant
    - all VMs should be in VMSS or VMAS 
    - VM machine name should be the same as the hostname.
> - Provisioner (aks-engine, capz, terraform, etc.) should allow cloud provider to modify which resources. Jack and Cecile to review. Should take some GiantSwarm and RedHat folks on the PR for review
> - E2e tests should be expanded to cover more scenarios against the master/main branch and include Cluster API
> - Jack will audit the aks-engine e2e
> - Current tests are not PR blocking and against releases, not main/master
> - Which resources does Cloud Provider expect to modify - and which should not be modified by other resource
> - Any expansion of the scope of Cloud Provider control over resources (e.g., name of the NIC) should result in a major new  version of the Cloud Provider (breaking change)
> - Azure CP is already consistent KEP for consistent CP semantic versioning and version skew policy enhancements/keps/sig-cloud-provider/1771-versioning-policy-for-external-cloud-providers at master · kubernetes/enhancements (github.com)

Next steps: @feiskyer will open a PR to add the initial draft of the contract and we will try to get as many stakeholders as possible to review.
/cc @craiglpeters @jackfrancis @nilo19
