### ISSUE TITLE
Artificial limitations exist on the number of Services that we can have sharing a single Public IP

### ISSUE THREAD

**Issue by MarcPow** [kubernetes-sigs/cloud-provider-azure#510]
**What happened**:
I attempted to create a StatefulSet of 100 instances, and then create a LoadBalancer Service for each, on a different port, but sharing a common public ip, 

However, rather than ending up with 100 services, I ended up with between 10 and 20, with the rest erroring out with load balancer reconciliation failures.

Warning  CreateOrUpdatePublicIPAddress  4m54s  azure-cloud-provider  Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidTagValueLength","message":"Tag value too large.  Following tag value 'default/echo-01,default/echo-02,default/echo-03,default/echo-04,default/echo-05,default/echo-06,default/echo-07,default/echo-08,default/echo-09,default/echo-010,default/echo-011,default/echo-012,default/echo-013,default/echo-014,default/echo-015,default/echo-016' exceeded the maximum length. Maximum allowed length for tag value - '256' characters."}} 

 

  Warning  SyncLoadBalancerFailed         4m54s  service-controller    Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"InvalidTagValueLength","message":"Tag value too large.  Following tag value 'default/echo-01,default/echo-02,default/echo-03,default/echo-04,default/echo-05,default/echo-06,default/echo-07,default/echo-08,default/echo-09,default/echo-010,default/echo-011,default/echo-012,default/echo-013,default/echo-014,default/echo-015,default/echo-016' exceeded the maximum length. Maximum allowed length for tag value - '256' characters."}} 
 
**What you expected to happen**:

100 services should have been provisioned.

**How to reproduce it**:
See attached files:
[statefulset-services-sharing-ip.yaml.txt](https://github.com/kubernetes-sigs/cloud-provider-azure/files/5974121/statefulset-services-sharing-ip.yaml.txt)
[statefulset.yaml.txt](https://github.com/kubernetes-sigs/cloud-provider-azure/files/5974122/statefulset.yaml.txt)
**Anything else we need to know?**:

**Environment**:  Azure Kubernetes/West Central US
- Kubernetes version (use `kubectl version`): 1.20.2
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1036-azure x86_64)

**Comment by nilo19** [comment]
This is a known issue because the maximum length of the tags on azure resources are 256. We plan to fix this.

**Comment by feiskyer** [comment]
From Azure docs [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#limitations), there're a lot of limitations including:

- Each resource, resource group, and subscription can have a maximum of 50 tag name/value pairs. If you need to apply more tags than the maximum allowed number, use a JSON string for the tag value. The JSON string can contain many values that are applied to a single tag name. A resource group or subscription can contain many resources that each have 50 tag name/value pairs.
- The tag name is limited to 512 characters, and the tag value is limited to 256 characters. For storage accounts, the tag name is limited to 128 characters, and the tag value is limited to 256 characters.

Based on these limitations, to share many services with the same PIP, tags should not be used to workaround those limitations. Let's document the workaround (BYO PIP) when customer wants to share many services with the same PIP (e.g. >10 services).

**Comment by nilo19** [comment]
will enrich the doc
/assign

**Comment by MarcPow** [comment]
How does BYO PIP work around these issues today?  Even external PIPs are tagged, IIRC.

**Comment by nilo19** [comment]
@MarkPow we don't tag BYO PIP the service names. Ref: https://kubernetes-sigs.github.io/cloud-provider-azure/topics/shared-ip/
