### ISSUE TITLE
Should ignore the case of lb name when determing if the load balancer is an internal one

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#5192]
#### What happened:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/7c0a8afb84df58905abe03583929f0f70ad48236/pkg/provider/azure_standard.go#L250

We should ignore the case of lb name when determing if the load balaner is an internal one.
For example: kubernetes-internal is an internal lb, KUBERNETES_INTERNAL is also an internal lb.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by haitch** [comment]
this would cause the cloudprovider not able to reconcile the ILB (Internal Load Balancer), it would fail with error message

E1220 22:55:14.089285       1 azure_loadbalancer.go:1594] reconcileLoadBalancer: **failed to get load balancer for service "ingress/ingress-ingress-nginx-controller", error: get(ingress/ingress-ingress-nginx-controller): lb(KUBERNETES-INTERNAL) - failed to get LB PublicIPAddress is Nil**
