### ISSUE TITLE
Use helm chart to install OOT credential provider

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes-sigs/cloud-provider-azure#5231]
#### What would you like to be added:
Use helm chart to install OOT credential provider
#### Why is this needed:
Now, OOT credential provider is installed with customized script in provisioning tool like CAPZ. It is better to do it in helm way.

**Comment by lzhecheng** [comment]
@CecileRobertMichon Hello, I discussed the implementation of this with @feiskyer . There seems to be a problem.
OOT credential provider migration needs 2 changes:
* add additional flags for kubelet
* copy a new binary to the node.

For the second change, it seems a kubelet restart cannot be avoided with helm install, which may lead to problem for other k8s components. Current solution seems better which copies credential provider binary in kubeadm step. What do you think?

Can the new CAAPH feature help this, which I'm not familiar with? If so, could you share how?

**Comment by CecileRobertMichon** [comment]
Could we install the binary in the VM image for CAPZ by changing the image-builder project https://github.com/kubernetes-sigs/image-builder/tree/main/images/capi ? 

Using kubeadm pre/post commands is not a valid solution for production / user facing (it's only acceptable for tests) because users would need to add the script in their templates which is not user friendly, and they may have different requirements for custom scripts so we try to reserve pre/post kubeadm commands for user commands.

**Comment by CecileRobertMichon** [comment]
cc @mboersma @jackfrancis @dtzar

**Comment by jackfrancis** [comment]
+1

**Comment by lzhecheng** [comment]
> Could we install the binary in the VM image for CAPZ by changing the image-builder project https://github.com/kubernetes-sigs/image-builder/tree/main/images/capi ?
> 
> Using kubeadm pre/post commands is not a valid solution for production / user facing (it's only acceptable for tests) because users would need to add the script in their templates which is not user friendly, and they may have different requirements for custom scripts so we try to reserve pre/post kubeadm commands for user commands.

I will check this image-builder repo.
If we put the binary into VM image, then we cannot build latest binary for each build. Is it true?

**Comment by CecileRobertMichon** [comment]
For testing custom cloud-provider builds we can still use the custom script method. This is only for user facing and other CAPZ testing.
