### ISSUE TITLE
kubenet route table latency causing DNS resolution failure right after node creation

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#527]
**What happened**:

When using kubenet network plugin together with cluster-autoscaler, new Pods scheduled to newly created node would get DNS resolution failure.

After talking with Azure Networking team, we confirmed this is because the route updates haven't take effect yet when the async updating returns success.

**What you expected to happen**:

Route updates should take effect when the node is marked as network ready state.

**How to reproduce it**:

Create a cluster with kubenet plugin and enable cluster autoscaler. Then enable HPA for the workload Pods.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20 and 1.19.
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jaygridley** [comment]
@feiskyer Is there any ETA when this could be actually available in AKS?

**Comment by feiskyer** [comment]
since there're some changes required in external cloud provider (including controller and agents), this fix would only be available as part of out-of-tree cloud provider (>=1.20).
