### ISSUE TITLE
Unable to install Azure cloud provider on Mariner OS: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Jasstkn** [kubernetes-sigs/cloud-provider-azure#5339]
#### What happened:

I was trying to deploy Azure Cloud Provider using helm-chart to Mariner-based controlplane node. It resulted in the following errors:
```sh
W0118 14:46:57.327369       1 azure_zones.go:51] syncRegionZonesMap: error when get zones: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Get "[https://management.azure.com/subscriptions/XXXXX/providers?api-version=2020-06-01":](https://management.azure.com/subscriptions/XXXXX/providers?api-version=2020-06-01%22:) tls: failed to verify certificate: x509: certificate signed by unknown authority, will retry after 30m0s
E0118 14:46:57.327395       1 azure.go:668] InitializeCloudFromConfig: failed to sync regional zones map for the first time: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Get "[https://management.azure.com/subscriptions/XXXX/providers?api-version=2020-06-01":](https://management.azure.com/subscriptions/XXXX/providers?api-version=2020-06-01%22:) tls: failed to verify certificate: x509: certificate signed by unknown authority
F0118 14:46:57.327408       1 controllermanager.go:315] Cloud provider azure could not be initialized: could not init cloud provider azure: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Get "
[https://management.azure.com/subscriptions/XXXXX/providers?api-version=2020-06-01":](https://management.azure.com/subscriptions/XXXXX/providers?api-version=2020-06-01%22:) tls: failed to verify certificate: x509: certificate signed by unknown authority
```

#### What you expected to happen:

Successful installation

#### How to reproduce it (as minimally and precisely as possible):

1. use Mariner OS-based image (e.g. from CAPI/CAPZ project)

2. Install Azure CCM using the following command:
```sh
helm upgrade --install cloud-provider-azure --repo https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo/ cloud-provider-azure --set cloudControllerManager.imageRepository=mcr.microsoft.com/oss/kubernetes --set cloudControllerManager.imageName=azure-cloud-controller-manager --set cloudNodeManager.imageRepository=mcr.microsoft.com/oss/kubernetes --set cloudNodeManager.imageName=azure-cloud-node-manager --set cloudControllerManager.cloudConfig="/etc/kubernetes/cloud-config/azure.json"
```
3. kubectl logs -f <pod_name>

#### Anything else we need to know?:

Issue was mitigated by specifying different location with certificates via flag: `-- set cloudControllerManager.caCertDir="/etc/pki/tls/certs"`

However, I tried to dig in to the issue because default location `/etc/ssl` contains the exact same certificates as the `/etc/pki/tls/certs`/
```
$ ls -lahtr /etc/ssl/certs
lrwxrwxrwx 1 root root 18 Dec  7 03:15 /etc/ssl/certs -> /etc/pki/tls/certs
$ ls -lahtr /etc/ssl/certs/
total 8.0K
lrwxrwxrwx 1 root root   49 Dec  7 03:15 ca-certificates.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx 1 root root   55 Dec  7 03:15 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
lrwxrwxrwx 1 root root   49 Dec  7 03:15 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
...

$ ls -lahtr /etc/pki/tls/
total 36K
drwxr-xr-x 6 root root 4.0K Nov 30 23:51 ..
lrwxrwxrwx 1 root root   49 Dec  7 03:15 cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
drwxr-xr-x 2 root root 4.0K Dec 11 23:15 private
-rw-r--r-- 1 root root  11K Dec 11 23:15 openssl.cnf
-rw-r--r-- 1 root root  412 Dec 11 23:15 ct_log_list.cnf
drwxr-xr-x 2 root root 4.0K Dec 11 23:16 misc
drwxr-xr-x 2 root root 4.0K Dec 14 16:17 certs
$ ls -lahtr /etc/pki/tls/certs/
total 8.0K
lrwxrwxrwx 1 root root   49 Dec  7 03:15 ca-certificates.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx 1 root root   55 Dec  7 03:15 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
lrwxrwxrwx 1 root root   49 Dec  7 03:15 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
...
```
Then I have tried to create an empty dir and change caCertDir to its location: e.g.
```
mkdir /tmp/test
helm upgrade --install ... -- set cloudControllerManager.caCertDir="/tmp/test"
```
And Azure CCM successfully starts up with no errors.

I have checked the base image that is being used for Azure CCM and it contains some [default CA certificate](https://github.com/GoogleContainerTools/distroless/tree/main/cacerts), see proof below:
![image](https://github.com/kubernetes-sigs/cloud-provider-azure/assets/20466436/b77675e9-874c-467e-843b-8daff19ca7f3)

Issue might be related to: #1717, https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3387#issuecomment-1495684214, https://github.com/kubernetes/cloud-provider-openstack/pull/1928, https://github.com/kubernetes/cloud-provider-openstack/issues/1923

It is not clear to me where exactly default SSL is being used and changing `caCertDir` parameter doesn't mount provided directory within the /etc/ssl, it just mounts it on the same path, see [helm-chart reference](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/helm/cloud-provider-azure/templates/cloud-provider-azure.yaml#L291). 

I also found list of the default locations in [Golang's crypto/x509](https://go.dev/src/crypto/x509/root_linux.go) and it looks like it works on the first match basis. Therefore it might use the certificate bundle that is provided from the image in all cases.

#### Environment:

- Kubernetes version (use `kubectl version`): `v1.27.10`
- Cloud provider or hardware configuration: `v1.27.9`
- OS (e.g: `cat /etc/os-release`): 
```sh
NAME="Common Base Linux Mariner"
VERSION="2.0.20231130"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```
- Kernel (e.g. `uname -a`):
```sh
Linux control000000 5.15.138.1-4.cm2 #1 SMP Thu Nov 30 21:48:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nilo19** [comment]
@Jasstkn can you open the issue in capz or capi? This is not a cloud provider issue.
