### ISSUE TITLE
Setting different service tags for different ports in AKS/Helm?

### ISSUE THREAD

**Issue by fstugren** [kubernetes-sigs/cloud-provider-azure#5341]
[Public AKS documentation](https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard) indicates that the annotation **service.beta.kubernetes.io/azure-allowed-service-tags** can be used in a Helm service yaml of type LoadBalancer to configure service tags on the Network Security Group inbound rules associated with the public endpoint of an AKS cluster. This works.

However, I couldn't find a way to configure the service tags to apply to one specific port opened by the load balancer, and not to others. When creating NSG rules by hand in the Azure Portal, the rule requires inbound service tag, destination IP and destination port. No such distinction is available via the Helm annotations.

How can a service tag be configured via helm on a specific port? Is there a workaround? If this is not supported, can it be added?

**Comment by zarvd** [comment]
> How can a service tag be configured via helm on a specific port? Is there a workaround? If this is not supported, can it be added?

Currently, you cannot configured on **a specific port of a service** using the annotation `service.beta.kubernetes.io/azure-allowed-service-tags`. It is intended to allow traffic from the given service tags to all ports of the service.

But you can set up 2 services, like Service A on port 80 and Service B on port 81 with `service.beta.kubernetes.io/azure-allowed-service-tags`. This way, only Service B on port 81 is allowed in NSG. Plus, both services can share the same public IP.
