### ISSUE TITLE
LoadBalancerInUseByVirtualMachineScaleSet when the node pool has 0 nodes and we try to delete the k8s service

### ISSUE THREAD

**Issue by axelgMS** [kubernetes-sigs/cloud-provider-azure#559]
**What happened**:  
Created an AKS cluster with 2 node pools, and created a k8s service to get an Internal LB.
Scaled down one of the node pool to 0 nodes - and then attempted to delete the service
--> Error LoadBalancerInUseByVirtualMachineScaleSet

**What you expected to happen**:
We should be able to delete the service even if the node pool has 0 nodes.
If we scale that node pool to 1 node and retry the deletion, then it works just fine.

**How to reproduce it**:

1. Create an AKS with 2 nodepools.  I created a 1.18.14 with kubenet.
2. Create an Internal-LB - eg.  https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
3. Scale 1 nodepool to 0 nodes.
4. Delete LB service via CLI:  kubectl delete service <internal-lb-service-name>

The delete command will stuck on loops indefinitely, with that error that still be in use - LoadBalancerInUseByVirtualMachineScaleSet

**Anything else we need to know?**:

Looked at the CCP logs for my repro, and it seems that k8s is receiving a 404 from CRP VMSS on the presence of nodes (expected since the VMSS contains 0 nodes) - so Controller Manager is trying to delete the LB, but that fails since the VMSS is still registered with the LB in NRP. And NRP doesn't allow deleting a LB in that case.

My repro on CCP namespace 604b9236d999440001aaf701 - on March 12th - from 16:20 to 16:50 UTC.

Also see internal email on CRI 231523972

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hterik** [comment]
We still see this problem on AKS with 1.21.2. Did you find any solution or workaround?

**Comment by nilo19** [comment]
Need to cherry pick that change to the in-tree code. Before that, is it possible foryou to switch to out-of-tree ccm to solve the issue @hterik ?

**Comment by hterik** [comment]
Thank you for the tip. I guess what you are suggesting is this? https://docs.microsoft.com/en-us/azure/aks/out-of-tree, it has a lot of scary _preview_-disclaimers. 
It also says this:

> The Cloud Controller Manager will be the default controller from Kubernetes 1.22, supported by AKS.

Would it be enough to just upgrade the kubernetes version of the AKS cluster instead? [1.22 is now GA.](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)

If not, would it make sense to try to cherry pick this into in-tree provider or how long will it take for azure specific provider to land to us mortals? As an outsider I'm struggling a bit to grok the relation between this repo, kubernetes and AKS, from my understanding the in-tree code is deprecated?

**Comment by nilo19** [comment]
> Thank you for the tip. I guess what you are suggesting is this? https://docs.microsoft.com/en-us/azure/aks/out-of-tree, it has a lot of scary _preview_-disclaimers. It also says this:
> 
> > The Cloud Controller Manager will be the default controller from Kubernetes 1.22, supported by AKS.
> 
> Would it be enough to just upgrade the kubernetes version of the AKS cluster instead? [1.22 is now GA.](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)
> 
> If not, would it make sense to try to cherry pick this into in-tree provider or how long will it take for azure specific provider to land to us mortals? As an outsider I'm struggling a bit to grok the relation between this repo, kubernetes and AKS, from my understanding the in-tree code is deprecated?

yes, please upgrade it to 1.22.x if possible. We have GA out-of-tree cloud provider azure since v1.22.0.
