### ISSUE TITLE
When node pools nodes are exposed via public IP, Network Security Groups are not updated properly

### ISSUE THREAD

**Issue by MarcPow** [kubernetes-sigs/cloud-provider-azure#575]
**What happened**:
- We deployed clusters using [Node Pool Public IPs](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#assign-a-public-ip-per-node-for-your-node-pools)
- We assigned services using *hostPorts* to that node pool
- These services were not reachable from the internet, until we manually opened the NSG (which does not scale and breaks the managed cluster abstraction).

**What you expected to happen**:
- We expected the services listening on hostPorts to be accessible from the public internet via the node public ips

**Environment**
- Kubernetes version: 1.18.x
- Node Pool Operating System: Windows

**Comment by feiskyer** [comment]
this is working as expected as NodePort typed services are not expected to be exposed on internet by default (secure by default).

**Comment by whihathac** [comment]
hi @feiskyer, some of the services on our cluster want to expose the hostPort on the node's public IP (ILPIP). So how do you recommend we mitigate this automatically?

**Comment by feiskyer** [comment]
@whihathac I think you need to create such NSG rules manually, or build a controller to do that automatically.
