### ISSUE TITLE
Cloud provider azure autoscaling test fails on cluster creation

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#581]
**What happened**:
https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-autoscaling
error details:
```
Custom data in OSProfile must be in Base64 encoding and with a maximum length of 87380 characters.
```
I cannot repro it locally. @CecileRobertMichon @chewong  could you help to determine if this could be migrated to capz?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nilo19** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@CecileRobertMichon @chewong This test has been failing for a long time and not fixed inside aks-engine. Appreciate if you could help to migrate it to capz (though I'm not sure whether capz supports cluster-autoscaler addon or not).

/cc @jackfrancis @craiglpeters

**Comment by chewong** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1279

**Comment by chewong** [comment]
Meanwhile, to fix the aks-engine autoscaling test, could you try decreasing the length of the API model by removing unnecessary config?

**Comment by CecileRobertMichon** [comment]
cluster-autoscaler has a cluster-api [provider](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi) that is cloud agnostic, it does not use the azure cluster-autoscaler provider, so if the goal is to test the azure cluster-autoscaler we wouldn't use CAPZ for that.

**Comment by feiskyer** [comment]
@CecileRobertMichon do you mean capz is not compatible with cluster-autoscaler on vmss?

**Comment by feiskyer** [comment]
> Meanwhile, to fix the aks-engine autoscaling test, could you try decreasing the length of the API model by removing unnecessary config?

@chewong we have already tried a few ways, but the generated ARM template is still too large. Could you help to check which part could be dropped for a short term workaround?

**Comment by nilo19** [comment]
@CecileRobertMichon behind the cloud-agnostic api there is the cluster autoscaler provider azure, right?

**Comment by CecileRobertMichon** [comment]
> behind the cloud-agnostic api there is the cluster autoscaler provider azure, right?

No, the cluster-autoscaler provider CAPI talks directly to the CAPI CRDs (increase/decrease the number of replicas on a MachineDeployment, etc.). The great thing about it is that it makes 0 API calls to Azure since it can get and modify the state of the cluster directly with CRDs.

Currently, it is supported for MachineDeployments (backed by VMs in CAPZ) and work is in progress to add MachinePools (backed by VMSS). We're also working on adding CI for CAPZ + CAPI autoscaler (see the issue Ernest linked above).

**Comment by jackfrancis** [comment]
I was able to repro this, and in my tests adding this configuration to the api model `"addons"` array unblocks the testing of this scenario:

```
{
    "name": "blobfuse-flexvolume",
    "enabled": false
}
```

@andyzhangx should we disable that addon by default in aks-engine now that the project is deprecated?

**Comment by andyzhangx** [comment]
> I was able to repro this, and in my tests adding this configuration to the api model `"addons"` array unblocks the testing of this scenario:
> 
> ```
> {
>     "name": "blobfuse-flexvolume",
>     "enabled": false
> }
> ```
> 
> @andyzhangx should we disable that addon by default in aks-engine now that the project is deprecated?

@jackfrancis yes, just go ahead disable `blobfuse-flexvolume` addon

**Comment by nilo19** [comment]
https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-autoscaler.json
we don't have this addon in our API model manifest.

**Comment by jackfrancis** [comment]
@feiskyer your change appears to have restored test signal, should we wait for another few test runs and then close this issue?

**Comment by feiskyer** [comment]
@jackfrancis yes, it is running though some tests failed. Appreciate the helping.

**Comment by jackfrancis** [comment]
I vote to close this issue as the custom data error has been fixed.
