### ISSUE TITLE
K8s master nodes are never added to standard load balancer backend pool

### ISSUE THREAD

**Issue by amsuggs37** [kubernetes-sigs/cloud-provider-azure#5849]
#### What happened:

When using the out-of-tree cloud provider azure as [documented](https://cloud-provider-azure.sigs.k8s.io/install/configs/), I have been unable to get the cloud-controller-manager to add master nodes to the backend pool of a standard load balancer.
I followed the notes about [`excludeMasterFromStandardLB`](https://cloud-provider-azure.sigs.k8s.io/install/configs/#excludemasterfromstandardlb) by setting to "false" and removed the `node-role.kubernetes.io/master` label from all the master nodes. Even then, the master nodes are not added to the load balancer backend pool.

#### What you expected to happen:

Configuring the cloud provider to not `excludeMasterFromStandardLB` and also removing the `node-role.kubernetes.io/master` label from all nodes should allow the cloud controller manager to add the master nodes to the standard load balancer backend pool.

#### How to reproduce it (as minimally and precisely as possible):

1. Deploy a 3 node kubernetes cluster in cloud. I'm using RKE2 with a VMSS to do so. Each node should have the control-plane and etcd node-role.
2. Deploy the cloud-provider-azure (configuration below)
3. Deploy a workload to the cluster and expose it with a LoadBalancer type service
4. The service should get an ExternalIP, but checking the load balancer in azure portal reveals that there are no nodes in the "kubernetes" backend pool.

#### Anything else we need to know?:

The same cloud provider configuration works as expected when the cluster has 1 or more worker nodes (not control-plane/etcd). Nodes with no node-role label successfully are added to the load balancer backend pool.

The following logs are present in the cloud-controller-manager deployment for a LoadBalancer type service called "http-echo". They indicate the load balancer being deleted from the vmss for seemingly no reason.
```
I0403 17:59:34.268581       1 azure_loadbalancer_backendpool.go:583] bi.ReconcileBackendPools for service (default/http-echo) and vmSet (): ensuring the LB is decoupled from the VMSet
I0403 17:59:34.268600       1 azure_vmss.go:1485] ensureBackendPoolDeletedFromVMSS: vmSetName (), backendPoolID (/subscriptions/<my_subscription>/resourceGroups/<my_resourcegroup>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes)
I0403 17:59:34.268609       1 azure_vmss.go:1505] ensureBackendPoolDeletedFromVmss: vmss (<my_vmss>)
```

#### Environment:

- Kubernetes version (use `kubectl version`): 1.24.12 (rke2 version: v1.24.12+rke2r1)
- Cloud provider or hardware configuration:
Cloud Provider:
```
{
  "cloud": "AzureUSGovernmentCloud",
  "cloudProviderBackoff": false,
  "excludeMasterFromStandardLB": false,
  "loadBalancerBackendPoolConfigurationType": "nodeIp",
  "loadBalancerSku": "standard",
  "location": "usgovvirginia",
  "resourceGroup": "<my_resourcegroup>",
  "securityGroupName": "k8s-nsg",
  "securityGroupResourceGroup": "<my_resourcegroup>",
  "subnetName": "<my_subnet>",
  "subscriptionId": "<my_subscription>",
  "tenantId": "<my_tenant>",
  "useInstanceMetadata": true,
  "useManagedIdentityExtension": true,
  "vmType": "vmss",
  "vnetName": "<my_vnet>",
  "vnetResourceGroup": "<my_resourcegroup>"
}
```
K8s bootstrap args:
```
kube-controller-manager-arg:
  - "cloud-provider=external"
  - "use-service-account-credentials=true"
  - "tls-min-version=VersionTLS12"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE
_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  - "feature-gates=CSIMigrationAWS=false"
  - "use-service-account-credentials=true"
kube-scheduler-arg:
  - "tls-min-version=VersionTLS12"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE
_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
kube-apiserver-arg:    
  - "tls-min-version=VersionTLS12"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE
_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
  - "enable-admission-plugins=NodeRestriction,PodSecurityPolicy,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
  - "request-timeout=300s"
  - "feature-gates=CSIMigrationAWS=false"
kubelet-arg: 
  - "cloud-provider=external"  
  - "azure-container-registry-config=/etc/kubernetes/cloud-config/azure.json"
  - "streaming-connection-idle-timeout=5m"
  - "feature-gates=CSIMigrationAWS=false"
  - "protect-kernel-defaults=true"
```
- OS (e.g: `cat /etc/os-release`): rhel 8.9
- Kernel (e.g. `uname -a`): 4.18.0-513.18.1.el8_9.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by brandond** [comment]
@amsuggs37 are you actually using `cloud-provider-azure` when deploying the nodes, or are you initially provisioning the cluster with the RKE2 embedded cloud provider, and then attempting to switch later?

The later will not work, as the node providerID and instance-type are set by the cloud provider that is in use when the node joins, and cannot be changed later. I suspect this is why you still see no nodes in the pool even after changing the `excludeMasterFromStandardLB` setting - the nodes do not have the correct fields to be managed by the azure cloud provider.

**Comment by amsuggs37** [comment]
Hi @brandond, thanks for commenting.

I am fairly certain I am using the `cloud-provider-azure` when deploying the nodes.
I followed the documentation [here](https://cloud-provider-azure.sigs.k8s.io/install/azure-ccm/) and set the appropriate flags in the `/etc/rancher/rke2/config.yaml` file per that documentation.

That config is in the initial issue description, but I do set `cloud-provider=external` in the kubelet and kube-controller-manager and also `disable-cloud-controller: true`.

My `cloud-provider-config.json` is also in the initial description.

From what I understand the helm deployment of the `cloud-provider-azure` should have all the correct default values.

Anyway, I checked my nodes as you suggested...
The `node.kubernetes.io/instance-type` label is set to: `Standard_DS2_v2` for all three of my nodes.
The `providerID` is set to: `azure:///subscriptions/<my_subscription>/resourceGroups/<my_resourcegroup>/providers/Microsoft.Compute/virtualMachineScaleSets/<my_vmss>/virtualMachines/X` where "X" is the number 0-2 depending on which of the three nodes you are looking at.

I cannot find any documentation on what determines these values as valid, but I can continue to dig. Do you know off the top of your head what determines them as valid?
Also, I would expect that if what you are saying is the issue, then I would not be able to add worker nodes to the LoadBalance either. If I create a cluster with a worker nodepool, those nodes are successfully added to the LoadBalancer BackendPool when I create LoadBalancer type services.

Let me know your thoughts, and thanks again for the ideas!

**Comment by brandond** [comment]
That all sounds correct then!

**Comment by cl-rf** [comment]
I was able to get this to work on a single node cluster with "vmType" set to "standard" but not when using scaling groups even using a single node. The cloud provider creates the load balancer, but does not add the "master" into the backend pool.

**Comment by amsuggs37** [comment]
So after about a month of research and digging around in this codebase, I think I have some more information.

Firstly, the documentation about "[excludeMasterFromStandardLB](https://cloud-provider-azure.sigs.k8s.io/install/configs/#excludemasterfromstandardlb)" is outdated/incorrect.
It makes mention of the fact that master nodes are not added to the load balancer backend pool by default, but that can be circumvented by setting `excludeMasterFromStandardLB: false` in the cloud provider config json file and then also removing the `node-role.kubernetes.io/master` label from those nodes. I did both of those steps, as I mentioned, and still had no luck.
As it turns out, the actual code determines if a node is a "master" by checking more criteria than the `node-role.kubernetes.io/master` label. Check out [azure_loadbalancer_backendpool.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_loadbalancer_backendpool.go#L453-L456) and [azure_standard.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_standard.go#L144-L156)... As can be seen, the provider is not only checking for the deprecated "master" node-role label, but also the `node-role.kubernetes.io/control-plane` label. See the logs from the cloud-controller-manager pod:
```
I0710 16:50:48.374056       1 azure_loadbalancer_backendpool.go:453] bi.EnsureHostsInPool: skipping control plane node masterset-master-d1tf000000
I0710 16:50:48.374065       1 azure_loadbalancer_backendpool.go:453] bi.EnsureHostsInPool: skipping control plane node masterset-master-d1tf000001
I0710 16:50:48.374079       1 azure_loadbalancer_backendpool.go:453] bi.EnsureHostsInPool: skipping control plane node masterset-master-d1tf000002
```
So, that is to say that in order for the azure cloud provider to place a master (control plane) node into the loadbalancer's backend pool, it would need to have the "control-plane" node-role label removed. This is unsafe and not recommended as it is a standard practice to have some workload's schedule on the control-plane with a node affinity selecting via that label. Removing that label would cause certain critical workloads to be stuck in a "Pending" state.
**So for a k8s cluster that consists only of a control-plane, which for some applications is a best-practice, the azure cloud provider will NEVER add those nodes to a loadbalancer backend pool.**

Secondly, for a cluster with nodes managed by VMSS, if those nodes' NICs have already been added to some other loadbalancer's backend pool, they CANNOT be added to another loadbalancer backend pool when the "loadBalancerBackendPoolConfigurationType" is set to "nodeIPConfiguration" (which is the default) in the cloud config json file. See the logs from the cloud-controller-manager pod:
```
I0709 13:57:24.100083 1 azure_vmss.go:1086] ensuring node "masterset-master-as7l000000" of scaleset "masterset-master-as7l" in LB backendpool "/subscriptions/<mySub>/resourceGroups/<myRG>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
I0709 13:57:24.100120 1 azure_vmss.go:1168] Node "masterset-master-as7l000000" has already been added to LB "cluster-lb", omit adding it to a new one
I0709 13:57:24.100138 1 azure_vmss.go:1086] ensuring node "masterset-master-as7l000001" of scaleset "masterset-master-as7l" in LB backendpool "/subscriptions/<mySub>/resourceGroups/<myRG>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
I0709 13:57:24.100170 1 azure_vmss.go:1168] Node "masterset-master-as7l000001" has already been added to LB "cluster-lb", omit adding it to a new one
I0709 13:57:24.100180 1 azure_vmss.go:1086] ensuring node "masterset-master-as7l000002" of scaleset "masterset-master-as7l" in LB backendpool "/subscriptions/<mySub>/resourceGroups/<myRG>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes"
I0709 13:57:24.100205 1 azure_vmss.go:1168] Node "masterset-master-as7l000002" has already been added to LB "cluster-lb", omit adding it to a new one
I0709 13:57:24.100211 1 azure_vmss.go:1215] ensureVMSSInPool: ensuring VMSS with backendPoolID /subscriptions/<mySub>/resourceGroups/<myRG>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes
I0709 13:57:24.100248 1 azure_vmss.go:1266] ensureVMSSInPool begins to update VMSS map[masterset-master-as7l:true] with backendPoolID /subscriptions/<mySub>/resourceGroups/<myRG>/providers/Microsoft.Network/loadBalancers/kubernetes/backendAddressPools/kubernetes
I0709 13:57:24.100279 1 azure_vmss.go:1327] VMSS "masterset-master-as7l" has already been added to LB "cluster-lb", omit adding it to a new one
```
As can be seen here, I have a loadbalancer called "cluster-lb" that I have associated my nodes' NICs with. This is an internal loadbalancer in order to allow the nodes to communicate with one-another. That prevents my nodes from being added to the backend pool, but this can be circumvented by setting "loadBalancerBackendPoolConfigurationType" to "nodeIp" in the cloud config json file. However, this DOES NOT solve the first issue and only allows worker nodes to be added to the loadbalancer backend pool.

My questions I'd like answered:
- Is there any reason why this cloud provider does not allow control plane nodes to be added to a backend pool by default? This seems to be a reasonable thing to do, not to mention that it is allowed in other cloud providers like AWS.
  - If there is a good reason, is there another way to circumvent that setting WITHOUT removing a critical node-role label?
- What is the difference between "nodeIpConfiguration" and "nodeIp" backend pool configurations? Why does azure not allow NICs to be associated with multiple backend pools? Again, this is something that is available in other cloud providers like AWS.

**Comment by nilo19** [comment]
@amsuggs37 one vmss vm nic cannot be added to more than one LB of the same type, external or internal. This is an Azure restriction, not cloud provider azure.
`nodeIP` does not support including master nodes, as control plane nodes are in a different subnet as workers, but IP-based backend pool requires all IPs are in one subnet.

**Comment by amsuggs37** [comment]
@nilo19 I don't understand your second point...
I am in control of how I provision my nodes (note that I am NOT using AKS)

I have n+1 VMSS (n for worker nodepools +1 for control plane ). I determine where those VMSS get deployed and into which subnet. **They are both deployed into the same VirtualNetwork/subnet.** 

Can you please address the issue that I posted about that proves that the cloud-provider-azure code does NOT match what is documented and omits nodes from the loadbalancer if the node-role.kubernetes.io/control-plane label ([consts.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/consts/consts.go#L89)) are also present. Those labels CANNOT be removed.
