### ISSUE TITLE
List() method is missing for Network Interface

### ISSUE THREAD

**Issue by gauravAggrhari** [kubernetes-sigs/cloud-provider-azure#612]
**Is your feature request related to a problem?/Why is this needed**
List method is needed to list all the network interfaces.

**Describe the solution you'd like in detail**
We can implement the new List() method to address the above issue.

**Describe alternatives you've considered**
Alternative would be directly make use of Azure SDK which imposes an inconsistency.

**Additional context**
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azureclients/interfaceclient/interface.go#L45-L57

**Comment by feiskyer** [comment]
The clients inside cloud-provider-azure only exposes interfaces that we consume today, and hence not all interfaces are added yet. Would you like to file a PR and add this interface?

**Comment by gauravAggrhari** [comment]
Yes @feiskyer, I would like to file a PR for this.
