### ISSUE TITLE
Human readable service identification for loadbalancer frontend IPs

### ISSUE THREAD

**Issue by tdihp** [kubernetes-sigs/cloud-provider-azure#6170]
#### What would you like to be added:

Add a indicator on which frontend IP address is for which service of which namespace, either as a part of LB comment (if that come to exist), or as a part of service status.

#### Why is this needed:

This will be more direct for users to see which service is relevant for which frontend IP object for troubleshooting, eliminate the need to crosscheck joining loadbalancer setting  with the service yamls.

**Comment by nilo19** [comment]
Frontend IP configuration is not a network subresource so we cannot tag it. One possible solution is to tag the load balancer, but that would be messy if the number of frontend ip configs is big.

**Comment by tdihp** [comment]
Possible to just put a configmap in kube-system for the mapping?

**Comment by nilo19** [comment]
> Possible to just put a configmap in kube-system for the mapping?

We need to consider if it's worth it creating a new resource just for clarification. The cost of checking this config map and checking the service uid would be pretty much the same.
