### ISSUE TITLE
Upgrade cloud-provider-azure to use Debian 12 Distroless

### ISSUE THREAD

**Issue by jhawkins1** [kubernetes-sigs/cloud-provider-azure#6189]
#### What would you like to be added:
Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes related projects have moved to Debian 12, we would request that cloud-provider-azure move to Debian 12 Distroless to align with other Kubernetes components.    Requested for 1.29.x and 1.30.x releases.

#### Why is this needed:
Alignment of  the Container OS being used to other Kubernetes related Projects. Reduces fan-out of multiple OSes or different versions of OSes across components. Potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS (Debian 12) release and not older LTS releases.

**Comment by kady1711** [comment]
I wanted to follow up on the request for migrating `cloud-provider-azure` to Debian 12 Distroless for the upcoming 1.29.x and 1.30.x releases. This change is crucial for ensuring alignment with the broader Kubernetes ecosystem and leveraging the security and maintenance benefits of Debian 12.

Could you please provide an update on the progress of this request? Specifically, it would be incredibly helpful to know the targeted release date or version number by which this migration is expected to be completed.

Having this information would greatly assist in our planning and integration efforts, ensuring we can align our deployments with the latest security and compatibility standards.

**Comment by nilo19** [comment]
Could you provide more information on this, for example a kubernetes issue that encourages components to migrate to debian 12 distroless or so? It seems other cloud providers have not migrated to that so I am not sure the necessity and urgency of the migration.
