### ISSUE TITLE
Cannot deploy Controller Manager 

### ISSUE THREAD

**Issue by tfontana1** [kubernetes-sigs/cloud-provider-azure#6201]
#### What happened:

We have created a new rke2 cluster and we want to deploy the Azure cloud provider using the helm chart. The cloud controller manager fails to launch saying "0/8 nodes are available: 8 node(s) didn't match Pod's node affinity/selector. preemption: 0/8 nodes are available: 8 Preemption is not helpful for scheduling." 

The node managers deploy successfully but the controller manager fails to deploy. 

#### What you expected to happen:

Azure cloud provider deploys successfully. 

#### How to reproduce it (as minimally and precisely as possible):

Install with helm, following the documentation instructions it fails right away. 

#### Anything else we need to know?:

We are running RKE2 in azure VM's (We are not using AKS)

#### Environment:

- Kubernetes version (use `kubectl version`): v1.29.1+rke2r1 
- Cloud provider or hardware configuration: Azure cloud provider
- OS (e.g: `cat /etc/os-release`): ubuntu 22
- Kernel (e.g. `uname -a`): 6.5.0-1021-azure 22~22.04.1-Ubuntu SMP Tue Apr 30 16:08:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Helm

**Comment by nilo19** [comment]
Capz uses helm to deploy cloud-controller-manager so this should work. Can you share more information for example, node affinities, selectors and pod description?
