### ISSUE TITLE
Unexpected VMSS capacity updates

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#635]
**What happened**:

Since the VMSS and instances are cached in cloud provider memory (default TTL is 10 min), if there're some changes on the VMSS capacity (e.g. by autoscaler), then the capacity value would be outdated in memory. However, cloud provider sets `vmss.Sku` when updating network profile, which may cause unexpected capacity change on VMSS.

**Impacted clusters:**

The Kubernetes clusters using internal LB or external LB may be impacted by this issue when cloud provider tries to add/remove VMSS from LoadBalancer backend address pool.

**Mitigation:**

Issue could be avoided if there're always an external LB service and an internal LB service (if it is used) in the cluster.

**Fixes**:

- out-of-tree cloud provider has been fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/630
- k/k fix https://github.com/kubernetes/kubernetes/pull/102005 is still pending on approval

**Comment by nilo19** [comment]
Fixes have been merged.
