### ISSUE TITLE
Support VMSS with Flexible orchestration

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#639]
**Is your feature request related to a problem? Please describe.**

VMSS provides flexible orchestration, which would have different behavior from current uniform orchestration. Some changes are required inside cloud provider to ensure it is supported as well.

**Describe the solution you'd like in detail**

Ensure VMSS Flex virtual machines are characterized as "vmss" type for node pool related features while still using VM APIs to perform disk attach/detach and network profile updates.

**Describe alternatives you've considered**

**Additional context**

- VMSS Flex would be supported in compute API version 2021-03-01
- Refer VMSS docs https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#scale-sets-with-flexible-orchestration.

**Comment by feiskyer** [comment]
this is still pending on new VMSS Flex APIs (together with Go SDK)

**Comment by varnastadeus** [comment]
Hey, any news on supporting flexible orchestration vmss?

**Comment by SnowmanCharles** [comment]
Hey folks, any progress on this issue?
