### ISSUE TITLE
k8s community infra migration: azureAuthConfigFromTestProfile needs federated identity

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#6621]
cloud-provider-azure jobs relying upon CAPZ are failing due to a new requirement for federated identity as part of the migration to k8s community infra on GKE and EKS.

Here is a sample test that shows this failure:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-capz-main/1813967116143955968

The cloud-provider-azure E2E test environment must rely upon an Azure client context running federated identity.

Ref: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#defaultazurecredential

**Comment by feiskyer** [comment]
related to #6577

**Comment by nilo19** [comment]
@jackfrancis it seems we need to set AADFederatedTokenFile from the environment variable. Do you know where can we find it in the context of a capz e2e test pipeline?
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azclient/auth_conf.go#L79
