### ISSUE TITLE
Cloud Controller Manager crashes after initial deployment with nil pointer dereference

### ISSUE THREAD

**Issue by daveman1010221** [kubernetes-sigs/cloud-provider-azure#676]
Hello. I've deployed Azure cloud controller manager to my Talos OS cluster, in Azure. The deployment seems to go well, but as the pod is initializing, it dies at runtime. I've never seen it run before, so this could easily be caused by some problem with my configuration, although the nil pointer is rather unexpected. Please let me know if there is anything else I can provide to help. Thanks.

**azure.json**

Sorry, I did have to scrub a few of the account identifiers here. If they are needed, let me know.

`{"cloud": "AzurePublicCloud", "tenantId": "...", "subscriptionId": "...", "resourceGroup": "...", "location": "eas      tus", "vmType": "standard", "subnetName": "talos-subnet", "securityGroupName": "talos-sg", "vnetName": "talos-vnet", "vnetResourceGroup": "...", "cloudProviderBackoff": true, "cloudProviderBackoffRetries": 6, "cloudProviderBackoffExponent": 1.5, "cloudProviderBackoffDuration": 5, "cloudProviderBackoffJitter": 1, "cloudProviderRatelimit": true, "cloudProviderRateLimitQPS": 6, "cloudProviderRateLimitBucket": 20, "useManagedIdentityExtension": false, "useInstanceMetadata": true, "loadBalancerSku": "basic", "excludeMasterFromStandardLB": false}
`

**Pod Config:**

` apiVersion: v1    
  kind: Pod    
  metadata:    
    name: cloud-controller-manager    
    namespace: kube-system    
    labels:    
      tier: control-plane    
      component: cloud-controller-manager    
  spec:    
    priorityClassName: system-node-critical    
    hostNetwork: true    
    serviceAccountName: cloud-controller-manager    
    tolerations:    
      - key: node-role.kubernetes.io/master    
        effect: NoSchedule    
    affinity:    
      nodeAffinity:    
        requiredDuringSchedulingIgnoredDuringExecution:    
          nodeSelectorTerms:    
          - matchExpressions:    
            - key: "node-role.kubernetes.io/master"    
              operator: Exists    
    containers:    
      - name: cloud-controller-manager    
        image: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.0.1    
        env:    
        - name: AZURE_ENVIRONMENT_FILEPATH    
          value: "/var/azure.json"    
        imagePullPolicy: IfNotPresent    
        command: ["cloud-controller-manager"]    
        args:    
          - "--allocate-node-cidrs=true"    
          - "--cloud-config=/var/azure.json"    
          - "--cloud-provider=azure"    
          - "--cluster-cidr=10.0.0.0/8"    
          - "--cluster-name=k8s"    
          - "--controllers=*,-cloud-node" # disable cloud-node controller    
          - "--configure-cloud-routes=true" # "false" for Azure CNI and "true" for other network plugins    
          - "--leader-elect=true"    
          - "--route-reconciliation-period=10s"    
          - "--v=2"    
          - "--port=10267"    
        resources:    
          requests:    
            cpu: 100m    
            memory: 128Mi    
          limits:    
            cpu: "4"    
            memory: 2Gi    
        livenessProbe:    
          httpGet:    
            path: /healthz    
            port: 10267    
          initialDelaySeconds: 20    
          periodSeconds: 10    
          timeoutSeconds: 5    
        volumeMounts:    
          - name: etc-ssl    
            mountPath: /etc/ssl    
            readOnly: true    
          - name: var    
            mountPath: /var    
            readOnly: false    
    volumes:    
      - name: etc-ssl    
        hostPath:    
          path: /etc/ssl    
      - name: var    
        hostPath:    
          path: /var    
`

**Error message from pod logs**

`E0625 03:18:36.624254       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 268 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d9a820, 0x3080290)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1d9a820, 0x3080290)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).getInternal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:90 +0x4a
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:125 +0x6c
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xc000873000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go:82 +0x75
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc000873000, 0x232a4a0, 0xc000056020, 0x7ffc9050fbba, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:271 +0x14d
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc000795380, 0x0, 0x46cd2b)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:126 +0x64
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:117 +0x2e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00062f0e0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00062f0e0, 0x22dcfc0, 0xc000955140, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062f0e0, 0x2540be400, 0x0, 0x2159200, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc00062f0e0, 0x2540be400, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x4d
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:116 +0x255
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a3a5aa]

goroutine 268 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1d9a820, 0x3080290)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).getInternal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:90 +0x4a
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:125 +0x6c
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xc000873000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go:82 +0x75
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc000873000, 0x232a4a0, 0xc000056020, 0x7ffc9050fbba, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:271 +0x14d
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc000795380, 0x0, 0x46cd2b)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:126 +0x64
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:117 +0x2e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00062f0e0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00062f0e0, 0x22dcfc0, 0xc000955140, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00062f0e0, 0x2540be400, 0x0, 0x2159200, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc00062f0e0, 0x2540be400, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x4d
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:116 +0x255
`

**Comment by daveman1010221** [comment]
Been playing around a bit, fixing a few minor things. Got a new nil pointer, thought I'd share:

`E0625 16:43:08.104810       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 310 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d9a820, 0x3080290)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1d9a820, 0x3080290)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).getInternal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:90 +0x4a
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:125 +0x6c
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xc0008a9000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go:82 +0x75
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc0008a9000, 0x232a4a0, 0xc00011c018, 0x7ffd6d463bba, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:271 +0x14d
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc00052f400, 0x0, 0x46cd2b)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:126 +0x64
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:117 +0x2e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009ec5a0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0009ec5a0, 0x22dcfc0, 0xc000a5a690, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009ec5a0, 0x2540be400, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc0009ec5a0, 0x2540be400, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x4d
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:116 +0x255
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a3a5aa]

goroutine 310 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1d9a820, 0x3080290)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).getInternal(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:90 +0x4a
sigs.k8s.io/cloud-provider-azure/pkg/cache.(*TimedCache).Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/cache/azure_cache.go:125 +0x6c
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xc0008a9000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_wrap.go:82 +0x75
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc0008a9000, 0x232a4a0, 0xc00011c018, 0x7ffd6d463bba, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:271 +0x14d
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc00052f400, 0x0, 0x46cd2b)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:126 +0x64
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:117 +0x2e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009ec5a0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0009ec5a0, 0x22dcfc0, 0xc000a5a690, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009ec5a0, 0x2540be400, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc0009ec5a0, 0x2540be400, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:109 +0x4d
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:116 +0x255`

Thoughts on how I can troubleshoot this?

**Comment by lobziik** [comment]
>Thoughts on how I can troubleshoot this?

Might worth to check credentials, I have feeling that smth wrong with is it. Worth try to put it into cloud-config for test if there are no credentials.

Namely parameters:
- aadClientId
- aadClientSecret

Doc: https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/
