### ISSUE TITLE
Failing PR tests : cm-vmss-ip-lb-capz and ccm-vmss-capz

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cloud-provider-azure#6979]
#### Which jobs are failing:
- Two PR jobs 
  - pr-cloud-provider-azure-e2e-ccm-vmss-capz-1-31
  - pr-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz-1-31
#### Since when has it been failing:
- Failing since 09/02/2024
#### Testgrid link:
- https://testgrid.k8s.io/provider-azure-cloud-provider-azure-1-31#pr-cloud-provider-azure-e2e-ccm-vmss-capz-1-31
- https://testgrid.k8s.io/provider-azure-cloud-provider-azure-1-31#pr-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz-1-31
#### Reason for failure:
- initial thoughts: workload cluster does not seem to be coming up. 
#### Anything else we need to know:
- kublet logs for [https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz-1-31/1831259427504656384](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz-1-31/1831259427504656384) are below
```
Sep 04 10:03:50.031576 capz-2jlm4x-control-plane-v42sr systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 04 10:03:50.074143 capz-2jlm4x-control-plane-v42sr kubelet[1653]: E0904 10:03:50.074062    1653 run.go:72] "command failed" err="failed to parse kubelet flag: unknown flag: --azure-container-registry-config"
Sep 04 10:03:50.076200 capz-2jlm4x-control-plane-v42sr systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Sep 04 10:03:50.076346 capz-2jlm4x-control-plane-v42sr systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 04 10:04:00.170840 capz-2jlm4x-control-plane-v42sr systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 9.
Sep 04 10:04:00.171061 capz-2jlm4x-control-plane-v42sr systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
```

**Comment by nilo19** [comment]
> controller="azuremachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureMachine" AzureMachine="default/capz-nodfd4-control-plane-hb4f2" namespace="default" name="capz-nodfd4-control-plane-hb4f2" reconcileID="6a5252f8-3917-47da-8433-48dd1c76c663"
I0902 18:27:42.553734       1 azuremachine_controller.go:237] "Reconciling AzureMachine" logger="controllers.AzureMachineReconciler.reconcileNormal" controller="azuremachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AzureMachine" AzureMachine="default/capz-nodfd4-control-plane-hb4f2" namespace="default" name="capz-nodfd4-control-plane-hb4f2" reconcileID="e76a046f-11a3-4297-9093-a099a92f3be6" x-ms-correlation-request-id="6417a45e-5000-4d7a-ac14-5cf2a848b236"
E0902 18:27:44.986794       1 controller.go:329] "Reconciler error" err=<
	failed to reconcile AzureMachine: failed to reconcile AzureMachine service vmextensions: extension state failed. This likely means the Kubernetes node bootstrapping process failed or timed out. Check VM boot diagnostics logs to learn more: failed to create or update resource capz-nodfd4/CAPZ.Linux.Bootstrapping (service: vmextensions): GET https://management.azure.com/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/providers/Microsoft.Compute/locations/uksouth/operations/de735d8a-94bf-47b6-a13d-b9206a4474b0
	--------------------------------------------------------------------------------
	RESPONSE 200: 200 OK
	ERROR CODE: VMExtensionProvisioningError
	--------------------------------------------------------------------------------
	{
	  "startTime": "2024-09-02T18:22:05.9005882+00:00",
	  "endTime": "2024-09-02T18:27:26.7624102+00:00",
	  "status": "Failed",
	  "error": {
	    "code": "VMExtensionProvisioningError",
	    "message": "VM has reported a failure when processing extension 'CAPZ.Linux.Bootstrapping' (publisher 'Microsoft.Azure.ContainerUpstream' and type 'CAPZ.Linux.Bootstrapping'). Error message: 'Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n\n[stderr]\n'. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot. "
	  },
	  "name": "de735d8a-94bf-47b6-a13d-b9206a4474b0"
	}

**Comment by mainred** [comment]
The error says failed to "parse kubelet flag: unknown flag: --azure-container-registry-config", azure-container-registry-config is removed from 1.31

**Comment by mainred** [comment]
The failure is caused by pull-cloud-provider-azure-e2e-ccm-vmss-capz-1-31 uses cluster template https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/cluster-api/linux-vmss-ci-version.yaml, which stil passes `azure-container-registry-config: /etc/kubernetes/azure.json` to kubelet, but kubelet has removed this flag in 1.31

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-presubmit-1.31.yaml
