### ISSUE TITLE
Allow define 0.0.0.0/0 as spec.loadBalancerSourceRanges for peered networks

### ISSUE THREAD

**Issue by keymon** [kubernetes-sigs/cloud-provider-azure#698]
**Is your feature request related to a problem? Please describe.**

We are peering our private network with some external third party network. 

When peering, we can add the flag `AllowVirtualNetworkAccess`, but that means that they can reach every resource in our network, including the AKS nodes.

The solution is to set `AllowVirtualNetworkAccess=false` and get the service controller adding the NSG rules for each loadbalancer by defining `spec.loadBalancerSourceRanges`. But the peerings are dynamic and happen AFTER the LB is created, integrating this is complicated. 

Instead, it is OK to us to use `spec.loadBalancerSourceRanges: [0.0.0.0/0]` in our private LoadBalancer and allow any traffic in the private network to reach the LoadBalancers.

The problem is that this service controller explicitely ignores `0.0.0.0/0` and does not add the rule (`servicehelpers.IsAllowAll(sourceRanges)`:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/17d5b7cd1f70e07444599a61c6d5e403a5009504/pkg/provider/azure_loadbalancer.go#L2256
```
if (sourceRanges == nil || servicehelpers.IsAllowAll(sourceRanges)) && len(serviceTags) == 0 
```

Our workaround use this hack: `spec.loadBalancerSourceRanges: ["0.0.0.0/1", "128.0.0.0/1"]`, which is equivalent, but requires 2 rules.

**Describe the solution you'd like in detail**

The service controller should add a rule for `0.0.0.0/0` for private LBs.

**Describe alternatives you've considered**
Our workaround use this hack: `spec.loadBalancerSourceRanges: ["0.0.0.0/1", "128.0.0.0/1"]`, which is equivalent, but requires 2 rules.

**Additional context**

**Comment by keymon** [comment]
The solution would be as simple as remove `servicehelpers.IsAllowAll(sourceRanges)`. 

Is there any reason why that is there?

**Comment by feiskyer** [comment]
Sorry for the late response, @keymon just to confirm, are you using internal LoadBalancer, or you mean the "Internet" rule behaviors different from "0.0.0.0/0" rule?

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/17d5b7cd1f70e07444599a61c6d5e403a5009504/pkg/provider/azure_loadbalancer.go#L2256-L2260

**Comment by keymon** [comment]
We are using internal loadbalancer. The issue description details the case.
.

**Comment by feiskyer** [comment]
> We are using internal loadbalancer. The issue description details the case.

Thanks for the confirmation. As Kubernetes default sourceRanges is "0.0.0.0/0" for external IPs, the check for `servicehelpers.IsAllowAll(sourceRanges)` is required for public LB. And L2257 ensures internal IPs are not exposed to Internet by default.

To fix this issue, we should differentiate whether "0.0.0.0/0" is coming from service spec or from default value. If it is from service.spec, then we should configure the NSG.

/kind bug

**Comment by feiskyer** [comment]
@MartinForReal could you help to fix this issue?
