### ISSUE TITLE
Add e2e tests for Load Balancers with Windows Clusters

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cloud-provider-azure#705]
**Is your feature request related to a problem?/Why is this needed**

Currently the e2e tests for load balancers are run against Linux clusters but they do not run against Windows.

Possible list of the tests we should enable against Windows:

pull-cloud-provider-azure-e2e-ccm                 
pull-cloud-provider-azure-e2e-ccm-capz                    
pull-cloud-provider-azure-e2e-ccm-vmss
pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb 

Questions:
Will these tests work against Windows?
Have they been tried at all?

**Describe the solution you'd like in detail**

Tests to provide coverage for load balancers against Windows clusters for VMAS and VMSS.  One way to do this would be to have a cluster with VMSS and VMAS clusters together and run tests against each configuration.

**Describe alternatives you've considered**

**Additional context**

/sig windows
/cc @CecileRobertMichon @marosset

**Comment by CecileRobertMichon** [comment]
@nilo19 @feiskyer I don't see anything in https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/network/ensureloadbalancer.go that tests Windows services specifically, can we add some tests for deployments with os selector "windows"?

**Comment by feiskyer** [comment]
@CecileRobertMichon agreed to add Windows service tests. Does capz support Windows nodes now? if so, we could add one and use capz to validate the Windows service connectivity.

**Comment by CecileRobertMichon** [comment]
It does. I opened https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1563 so we can use it to test out of tree with Windows.

**Comment by nilo19** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1563 has been closed. Do we still plan to support windows with out-of-tree cloud provider in capz? @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
@nilo19 yes, see https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1994 which is changing all test flavors to out of tree

@jackfrancis was actually having trouble getting out of tree provider working with windows, see this slack thread: https://kubernetes.slack.com/archives/CEX9HENG7/p1643223810161800?thread_ts=1643218459.154600&cid=CEX9HENG7

It would still be good to have a story for testing windows services with out of tree so we can make sure the integration works.

**Comment by lzhecheng** [comment]
/assign
I will adjust current lb e2e tests and CI jobs to verify Windows implementation.
