### ISSUE TITLE
Deploy Cloud Controller Manager

### ISSUE THREAD

**Issue by m-deepakraja** [kubernetes-sigs/cloud-provider-azure#717]
https://kubernetes-sigs.github.io/cloud-provider-azure/install/example/out-of-tree.md link doesn't exist. 

But it is supposed to show sample deployment examples for cloud provider

**Comment by feiskyer** [comment]
@m-deepakraja All the links could be found in docs https://kubernetes-sigs.github.io/cloud-provider-azure/example/out-of-tree/.

Where did you find that link? let's fix the links if it is broken somewhere.

**Comment by m-deepakraja** [comment]
I found the link here 
https://kubernetes-sigs.github.io/cloud-provider-azure/install/azure-ccm/#azuredisk-and-azurefile

"Please refer examples "here" for sample deployment manifests for above components."

"here" link is broken

**Comment by feiskyer** [comment]
thanks for the info. I would fix the links

**Comment by m-deepakraja** [comment]
https://kubernetes-sigs.github.io/cloud-provider-azure/install/azure-ccm/#azure-cloud-node-manager 
Sorry, the link is broken for azure-cloud-node-manager 

![image](https://user-images.githubusercontent.com/11572323/127056882-0b599151-c71e-40d3-aeae-b05679f33e9d.png)

**Comment by m-deepakraja** [comment]
Also, I have a question about the version matrix : https://github.com/kubernetes-sigs/cloud-provider-azure#current-status

I see that cloud-provider-azure has been GA since v1.0.0. 
Lets say I want to use, kubernetes with 1.19, can I use the latest cloud-provider-azure(v1.0.3) or should I only use v0.6.0 ? 
Is it backward compatible ?

**Comment by feiskyer** [comment]
v1.0.3 should be used. We don't guarantee backward compatibility.

**Comment by m-deepakraja** [comment]
@feiskyer : Thanks for the response. 
I have two more questions  : 
1.Upgrade story : Is it compatible for upgrades?  for eg: I have kubernetes 1.20.x with v0.7.6 cloud provider, then I upgrade the kubernetes to 1.21.x and upgrade the cloud provider to v1.0.3. Will it work ? Like at some point during the upgrade, few control plane nodes will be @ 1.21 with v1.0.3 and some control plane nodes will be @ 1.20 with v0.7.6. is this scenario supported ? 

2. is v0.7.6 stable ? I am experimenting the codebase, but just want some thoughts. I see that v1.0.0 is the GA, but just want to understand the potential fallouts if any. 

Thanks
Deepak

**Comment by feiskyer** [comment]
1. yes, it would work
2. yes, it is also a stable version (and it is also actively maintained as you can see the new changes in release branch).

**Comment by m-deepakraja** [comment]
@feiskyer : Thanks for the response. One last question about the doc.
In this doc, I see that while deploying cloud controller manager, it is suggesting to disable cloud-node controller.
https://kubernetes-sigs.github.io/cloud-provider-azure/install/azure-ccm/#azure-cloud-controller-manager

why does it needs to be disabled? Is this the in-built node controller which is being disabled ? 

and we deploying the cloud node controller manually in all the pods?

**Comment by feiskyer** [comment]
1. cloud-node-manager needs to be deployed on all nodes (including Windows), while cloud-controller-manager only needs to be deployed on master
2. It is because we switch node controller to a daemonset cloud-node-manager

**Comment by m-deepakraja** [comment]
@feiskyer 
Question about this config : allocate-node-cidrs
According to this doc : https://github.com/kubernetes-sigs/cloud-provider-azure/blob/19228b1629f36b6ac63b07128275435f67a8ebb0/site/content/en/topics/ipam.md#configurations

We have to set **allocate-node-cidrs**  to false in kube-controller-manager to disable the in-tree node IPAM controller.

But in this example for out-of-tree, 
kube-controller-manager also set to true
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/19228b1629f36b6ac63b07128275435f67a8ebb0/examples/out-of-tree/kube-controller-manager.yaml#L17

and cloud-controller-manager also set to true
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/19228b1629f36b6ac63b07128275435f67a8ebb0/examples/out-of-tree/cloud-controller-manager.yaml#L153

I see that it is set as true both in kube-controller-manager and cloud controller manager. 

Can you please help me understand the correct configuration ? 
Thanks
