### ISSUE TITLE
Unable to create k8s service of type loadbalancer using internal load balancer

### ISSUE THREAD

**Issue by gregmo2413** [kubernetes-sigs/cloud-provider-azure#7200]
After upgrading from Azure Cloud Controller Manager (CCM) version v1.27.17 to version v1.29.9, we are unable to create a new
service of type 'Loadbalancer' using the internal load balancer 'kubernetes-internal'.

Please note that this is a self-managed k8s cluster, not one managed by AKS.

If the matter is security related, please disclose it privately via https://kubernetes.io/security/
-->

#### What happened:
We tried to create a service of type loadbalancer after upgrading the Azure CCM from version 1.27.17 to version v1.29.9. The service never transitioned past the pending state. Existing services of type loadbalancer using the internal load balancer remained operational.

#### What you expected to happen:
Create a service of type loadbalancer using an internal load balancer.

#### How to reproduce it (as minimally and precisely as possible):
Create a new service of type loadbalancer configured to use an internal load balancer.

#### Environment:

- Kubernetes version (use `kubectl version`): v1.29.4
- Cloud provider or hardware configuration: A self-managed k8s cluster. We are not using AKS.
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): 6.5.0-1025-azure #26~22.04.1-Ubuntu SMP Thu Jul 11 22:33:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): cilium v1.14.13

- Others:
[k8s_upgrade_azure_ccm_bug_internal-lb.txt](https://github.com/user-attachments/files/17259208/k8s_upgrade_azure_ccm_bug_internal-lb.txt)

**Comment by nilo19** [comment]
@gregmo2413 are you updating from nic-lb to multi-slb? If so, can you try to migrate from nic-lb to ip-based lb first, and enable the multi-slb afterwards?
