### ISSUE TITLE
`--version` flag reports incorrect version

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/cloud-provider-azure#744]
**What happened**:

`--version` flag reports incorrect version.

**What you expected to happen**:

`--version` to report the correct component version.

**How to reproduce it**:

```
$ docker run mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.0.3 --version=raw
version.Info{Major:"", Minor:"", GitVersion:"latest", GitCommit:"latest", GitTreeState:"", BuildDate:"2021-07-20T06:37:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

`Major`, `Minor`, `GitTreeState` fields are empty. `GitVersion`, `GitCommit` are wrongly set to latest.

**Anything else we need to know?**:

**Environment**:
aws-cloud-controller-manager version: v1.0.3

**Comment by feiskyer** [comment]
thanks for reporting the issue. It should be caused by some issues in build scripts

/assign

**Comment by ialidzhikov** [comment]
The output of `--version=raw` can be still improved after #745:

```
$ ./bin/azure-cloud-controller-manager --version=raw
version.Info{Major:"", Minor:"", GitVersion:"v1.0.1-110-gdb55133e7", GitCommit:"db55133e7d8ad1b110ec0d46ca823c3a580de4ca", GitTreeState:"", BuildDate:"2021-08-10T07:34:59Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
```

`Major`, `Minor`, `GitTreeState` fields are still empty.

/reopen

**Comment by feiskyer** [comment]
> Major, Minor, GitTreeState fields are still empty.

Sorry, I didn't notice this issue. Let's fix with a follow PR.
