### ISSUE TITLE
SyncLoadBalancerFailed due to etag mismatch

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cloud-provider-azure#792]
#### What happened:

I've been testing out large cluster scenarios, and validating that I can create basic svc resources as the number of nodes increases. In increments of 500, I've been able to successfully create a basic LoadBalancer-backed svc with 500, 1000, 1500, 2000, 2500, and 3000 nodes. This is the svc definition I'm using:

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-elb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
```

However, once I scaled out to 3500 nodes, I observe that I am no longer able to create a svc with the below error:

```
$ k describe svc ingress-nginx-elb
Name:                     ingress-nginx-elb
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=ingress-nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.0.27.56
IPs:                      10.0.27.56
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  31718/TCP
Endpoints:                10.240.109.200:80
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31712/TCP
Endpoints:                10.240.109.200:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                  From                Message
  ----     ------                  ----                 ----                -------
  Normal   UpdatedLoadBalancer     2m21s                service-controller  Updated load balancer with new hosts
  Warning  SyncLoadBalancerFailed  104s                 service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 429, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 429, RawError: {"Error":{"Details":[{"Code":"GatewayError","Message":"Error occurred in resource provider infrastructure services.","Target":null}],"InnerError":"Source: RD0003FFE5AE82. Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.NrpException: A retryable error occurred. ---> Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.NrpException: Error occurred in resource provider infrastructure services. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.Common.ReliableHttpClient.HttpClientWrapper.<SendAsync>d__5.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\Common\\ReliableHttpClient\\HttpClientWrapper.cs:line 121\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<CallNrpAndGetResponseWithRetries>d__42.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 715\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<CallNrpAndGetResponseWithRetries>d__42.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 748\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<ForwardMessageToNrpAndProcessResponseAsync>d__34.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 269\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---","Code":"RetryableError","Message":"A retryable error occurred.","Target":null}}
```

#### What you expected to happen:

I expected the svc to create a new Public IP, attach it to the Standard LB front end configuration, and for the Kubernetes svc to be reconciled.

#### How to reproduce it (as minimally and precisely as possible):

Build a cluster w/ one Standard Load Balancer and many VMSS node pools. Add instances to the VMSS, thus adding nodes to the cluster. Observe that eventually new svc resources are not able to be created because of etag mismatch.

#### Environment:

- Kubernetes version (use `kubectl version`): 1.22.0
- Cloud provider or hardware configuration: `mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.22.0`
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04-LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jackfrancis** [comment]
Easier to read here:

Warning  SyncLoadBalancerFailed  104s                 service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 429, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 429, RawError: {"Error":{"Details":[{"Code":"GatewayError","Message":"Error occurred in resource provider infrastructure services.","Target":null}],"InnerError":"Source: RD0003FFE5AE82. Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.NrpException: A retryable error occurred. ---> Microsoft.WindowsAzure.Networking.Nrp.Frontend.Common.NrpException: Error occurred in resource provider infrastructure services. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.Common.ReliableHttpClient.HttpClientWrapper.<SendAsync>d__5.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\Common\\ReliableHttpClient\\HttpClientWrapper.cs:line 121\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<CallNrpAndGetResponseWithRetries>d__42.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 715\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<CallNrpAndGetResponseWithRetries>d__42.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 748\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.WindowsAzure.Networking.Nrp.GatewayServiceCommon.GatewayServiceRoutingController.<ForwardMessageToNrpAndProcessResponseAsync>d__34.MoveNext() in X:\\bt\\1121427\\repo\\src\\sources\\GatewayService\\GatewayCommon\\GatewayServiceRoutingController.cs:line 269\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---","Code":"RetryableError","Message":"A retryable error occurred.","Target":null}}

**Comment by jackfrancis** [comment]
And more information:

"error": {
    "details": [
      {
        "code": "RetryableErrorDueToAnotherOperation",
        "message": "Operation ValidateVMScaleSetOperation (f28918c7-228c-47ce-a71b-3e06ca542012) is updating resource /subscriptions/<sub id>/resourceGroups/KUBERNETES-WESTUS2-12602/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-agentpool1-35287130-vmss/validate. The call can be retried in 12 seconds."
      }
    ],
    "code": "RetryableError",
    "message": "A retryable error occurred."
  }
}
  Warning  SyncLoadBalancerFailed  90s  service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: {
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch",
        "message": "Etag provided in if-match header W/\"c87e02d2-0b0b-4a40-8ede-87fafcff15ab\" does not match etag W/\"b53e0a33-febc-41cb-b293-0a7220be0c1f\" of resource /subscriptions/<sub id>/resourceGroups/kubernetes-westus2-12602/providers/Microsoft.Network/loadBalancers/kubernetes-westus2-12602 in NRP data store."
      }
    ]
  }

**Comment by jackfrancis** [comment]
I will try to repro using `mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.1.1` today. Will report back...

**Comment by jackfrancis** [comment]
I can repro this with the latest out of tree cloud-provider-azure as well:

```
E0902 23:08:47.407278       1 controller.go:307] error processing service default/ingress-nginx-elb (will retry): failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: {
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch",
        "message": "Etag provided in if-match header W/\"515da78d-62b6-4130-8220-834ee4148a9f\" does not match etag W/\"8821be0b-1d25-47f6-b3de-771d4771196a\" of resource /subscriptions/01993b85-2035-47d7-99ad-a70e8520136f/resourceGroups/kubernetes-eastus2-56461/providers/Microsoft.Network/loadBalancers/kubernetes-eastus2-56461 in NRP data store."
      }
    ]
  }
}
```

**Comment by jackfrancis** [comment]
But, it looks to be temporary with the latest code! LB eventually reconciled.

**Comment by feiskyer** [comment]
etag mismatch is an expected error when the LB is changed from other services (e.g. PUT VMSS may change LB configuration when adding or removing backend address pools). Azure network and VMSS teams are working together to improve the general performance and we could expect less errors and less reconciling time in the future.

**Comment by chapmanc** [comment]
How long does it take to reconcile after this error? In the above issue we are having issues handling delete as it seems to exit before actually cleaning up the load balancer.
