### ISSUE TITLE
Add support for dualstack service

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#814]
#### What would you like to be added:

Only single stack service (either ipv4 or ipv6) is supported today as `service.Spec.ClusterIP` is used to determine the public IP family. We should add support for dualstack services and allocate both ipv4 and ipv6 public IPs.

**Comment by MartinForReal** [comment]
related: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2154

**Comment by lzhecheng** [comment]
Developing in this branch https://github.com/lzhecheng/cloud-provider-azure/tree/support-ds.dev
