### ISSUE TITLE
Add support for Private Link Service when exposing service as LoadBalancer

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#872]
#### What would you like to be added:

Add support for Private Link Service when exposing service as LoadBalancer with a new annotation `service.beta.kubernetes.io/azure-private-link-service: enabled`

Without this, customers have to perform the following steps manually:

step 1): ILB service creation: https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
step 2): find the ILB frontend configuration ID from above step and then follow https://docs.microsoft.com/en-us/azure/private-link/create-private-link-service-cli#create-a-private-link-service to create PLS.

#### Why is this needed:

Refer https://github.com/Azure/AKS/issues/1604.

**Comment by MartinForReal** [comment]
IMHO, we should divide these feature into two parts: integration setup and PLS/PE lifecycle management. Because PLS can be shared between different services and event between difference resource instances. Thus, PLS should not be maintained in service object lifecycle. However,  I think it's reasonable to create a PE object for the service object when appropriate PLS resources is specified because PE has one-to-one relationship with the internal load balancer which the service owns.

Considering the lifecycle management of PLS/PE, should we introduce new resources in [azure service operator](https://github.com/Azure/azure-service-operator/blob/main/api/v1alpha2/aso_types.go) to wrap up maintenance logic for PLS/PE?

Regarding integration setup, we can create/delete PE instance in svc reconciling loop.

@feiskyer @erjosito @miwithro Any advice is appreciated. Thanks!

**Comment by feiskyer** [comment]
No, PE is not involved here. The feature here only needs to create a new PLS for the service associated ILB frontend configurations.

And by the way, PLS couldn't be shared by multiple services (PLS is associated to ILB frontend configurations, and ILB frontend configuration is 1:1 map to k8s service).

**Comment by MartinForReal** [comment]
Thanks for pointing out!

**Comment by MSSedusch** [comment]
can we also somehow include the approval process into K8s? It would be nice to update the K8s object if there is a connection request(s), along with the required information to decide if the connection request can be approved (request message, source resource ID), and a way to approve/decline the request.

Also, should this feature be Azure only or can this be a generic extension that Azure, AWS, GCP.... can implement?

**Comment by feiskyer** [comment]
@MSSedusch PLS connection approval is a different topic. Both its API and approval process are different from k8s service objects. I think it's better for customer to use PLS API for that since PLS API is required anyway to create a PE.

**Comment by MSSedusch** [comment]
I think the PE creation is outside of the scope of Kubernetes, I assume in this scenario, the person that creates the PE would not be the operator of the K8s cluster but rather a customer that uses a service that is hosted on K8s. 

Approving the connection on PLS side updates the PLS resource and since K8s creates the PLS resource, it feels like a good idea to also approve the connection inside K8s. Otherwise, applications in K8s would have a dependency to an Azure REST API only to approve the connection.

**Comment by jwtty** [comment]
Design document for adding annotations on service objects to enable Azure PLS integration: https://kubernetes-sigs.github.io/cloud-provider-azure/development/design-docs/pls-integration/

**Comment by sebader** [comment]
@jwtty is this already live now and can be tested on public AKS clusters?

**Comment by sebader** [comment]
@feiskyer no worries, I figured :) would you mind to please update this thread once it goes lives? Since the [issue ](https://github.com/Azure/AKS/issues/1604)from the AKS repo also points to this one here

**Comment by jwtty** [comment]
Hi @sebader, sure we will keep this thread updated! Thank you for checking.

**Comment by sschu** [comment]
It's really cool to see this happen. Thanks to anybody who was involved! By coincidence, Front Door Standard/Premium also became GA quite recently...

**Comment by sebader** [comment]
It was actually already posted on Azure Update yesterday but I assume it will take a couple of weeks until the new version of cloud-node-manager lands in an AKS release and then gets rolled out, right?

https://azure.microsoft.com/en-us/updates/public-preview-aks-private-link-service-integration/

**Comment by JamesDLD** [comment]
Thanks guys for the job done. 

- Just tried it and I do have my load balancer "kubernetes-internal" but _i don't see my Private Link_, any idea? 

I based my yaml according to this [example](https://kubernetes-sigs.github.io/cloud-provider-azure/development/design-docs/pls-integration/#managed-privatelinkservice-creation-example).
Context: 
- Kubernetes version: 1.22.6
- Azure CNI and version 
FYI @MartinForReal

**Comment by sebader** [comment]
@JamesDLD the changes are not rolled out yet to the live clusters

**Comment by JamesDLD** [comment]
> @JamesDLD the changes are not rolled out yet to the live clusters

Do you know if I can be updated on when this will be rolled ou to live clusters?

**Comment by MartinForReal** [comment]
It often takes two weeks after a new release is published. But it depends.

**Comment by JamesDLD** [comment]
When using Kubernetes network policies do you know the source subnet we should allow in order to publish our pod? 
The Internal Load Balancer subnet?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/18073917/169712039-417b0bc5-750b-452d-9aa4-195eb134ffe6.png">

**Comment by jwtty** [comment]
Hey, this feature has been rolled out to all prod regions. It's now in public preview, here is the [official doc](https://docs.microsoft.com/en-us/azure/aks/internal-lb#connect-azure-private-link-service-to-internal-load-balancer-preview) 
Please feel free to try it!

Note: aks-preview cli extension is not required. We will update the doc soon.

**Comment by gitakp** [comment]
> Just published an article about it! https://medium.com/microsoftazure/connect-azure-front-door-premium-to-an-aks-app-origin-with-private-link-5978341c2650 Thanks for this feature! Any idea when this will be GA?

This voting app does work. There is no subsequent path attached to hostname. Did you try for another application with a /path? For me, it does not work.

**Comment by sebader** [comment]
@gitakp I think you issue is not really related to this original issue here (which is for tracking Private Link on AKS, which does work).

Anyway, I built a (fairly complex but complete) scenario:

Installing nginx ingress, which is exposed via PLS:
https://github.com/Azure/Mission-Critical-Connected/blob/feature/afd-privatelink/.ado/pipelines/templates/jobs-configuration.yaml#L46

Ingress configuration, including path:
https://github.com/Azure/Mission-Critical-Connected/blob/feature/afd-privatelink/src/app/charts/catalogservice/templates/ingress.yaml

Front Door config (in Terraform, not yet GA)
https://github.com/Azure/Mission-Critical-Connected/blob/feature/afd-privatelink/src/infra/workload/globalresources/frontdoorv2.tf#L161

and the route:
https://github.com/Azure/Mission-Critical-Connected/blob/feature/afd-privatelink/src/infra/workload/globalresources/frontdoorv2.tf#L188

**Comment by jwtty** [comment]
Hi @gitakp @JamesDLD , the current estimate GA Date is 12/1/2022.
