### ISSUE TITLE
Publish release notes automatically with github actions

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#878]
When cutting new releases, the following commands could be used to generate the release notes:

```sh
GO111MODULE=on go install k8s.io/release/cmd/release-notes@latest

release-notes --repo=cloud-provider-azure \
	--org=kubernetes-sigs \
	--branch=release-1.1 \
	--start-sha=$(git rev-parse v1.1.1) \
	--end-sha=$(git rev-parse v1.1.2) \
	--output=v1.1.2.md
```

The same commands could be executed in github actions and hence the release notes could be published automatically.

**Comment by Darshnadas** [comment]
Can I take this issue?

**Comment by Darshnadas** [comment]
Can someone tell me that these commands, shall be written in a new script?

**Comment by feiskyer** [comment]
Thanks for taking this. Yes, `release-notes` could be installed and invoked in a new script

**Comment by Darshnadas** [comment]
Hi @feiskyer sorry for replying late, but can you help me understand this issue more briefly? This is my first time working on this type of issue, it will be really helpful if you can explain by `release-notes` installed and what has to be done? Can you explain me more clearly?

**Comment by feiskyer** [comment]
Generally, it could be done in 4 steps:

1) collect the branch name and github tags
2) Install by `GO111MODULE=on go install k8s.io/release/cmd/release-notes@latest`
3) run `release-notes ...` as shared above
4) publish the contents of result in github releases

**Comment by Darshnadas** [comment]
For all the releases? does it have to publish separately or at once for all the releases it can published?

**Comment by luncj** [comment]
When we push a new release tag, it should trigger the action to generate release-note and publish release. Right?

https://github.com/softprops/action-gh-release may help (example: https://github.com/linkerd/linkerd2/blob/main/.github/workflows/release.yml).

**Comment by Darshnadas** [comment]
Hi, @luncj I will read them and again get back to you or @feiskyer. It'll be easier if I start a slack thread regarding this issue, will it be okay?

**Comment by luncj** [comment]
Hi, @Darshnadas. Is there any progress? I will help solve this issue along with #879.

**Comment by Darshnadas** [comment]
Hi @luncj, unfortunately, I have been busy with another work, will start with this issue this week.

**Comment by feiskyer** [comment]
@Darshnadas thanks for the reply. this is already done by #1014.

**Comment by Darshnadas** [comment]
Okay, @feiskyer. Will look forward to contribute to another issue :)
