### ISSUE TITLE
Publish cloud-node-manager binaries for new releases

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#879]
With scenarios like https://github.com/kubernetes-sigs/cloud-provider-azure/pull/823, cloud-node-manager couldn't be run as daemonsets, hence cloud-node-manager.exe is required to run it as Windows services.

To avoid asking customers to build the binaries themselves, the binaries for cloud-node-manager should be built and published for new releases.

**Comment by luncj** [comment]
fixed via #1014
