### ISSUE TITLE
version skew/matching k8s releases

### ISSUE THREAD

**Issue by bridgetkromhout** [kubernetes-sigs/cloud-provider-azure#881]
Request from sig cloud provider: can we match the release versions for the sig cloud provider to the k8s versions? The current version skew is in https://github.com/kubernetes-sigs/cloud-provider-azure#current-status but the version numbers don't match k8s versions.

**Comment by CecileRobertMichon** [comment]
@feiskyer any idea of when this could be done?

**Comment by feiskyer** [comment]
We would cut a new version after 1.23.0 comes out (would need to update go modules to 1.23).

**Comment by nilo19** [comment]
released v1.23.0.
