### ISSUE TITLE
Avoid adding tags on the BYO PIP or clean up the tag once delete the svc

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes-sigs/cloud-provider-azure#900]
#### What happened:
When user creates the LB svc with BYO PIP and add the DNS name annotation, KCM tagged the service but didn't clean up once the service is deleted
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L745 

there was commit to avoid tagging BYO PIP but it looks like the tag field is still changed. I might miss something pls feel free to correct me
https://github.com/kubernetes-sigs/cloud-provider-azure/commit/1ebfb609b3762e9abe25d717a3a6ecfaca62bbcf#diff-ec0e9d2cbe0713dd82a1be0894ef682a36222d21f7fb47d299b843ebbed8ba6dR887
https://github.com/kubernetes-sigs/cloud-provider-azure/blame/master/pkg/provider/azure_loadbalancer.go#L1184 

#### What you expected to happen:
either KCM should avoid tagging the resource because it's BYO or clean up once svc gets deleted
#### How to reproduce it (as minimally and precisely as possible):
1. create AKS v1.22.2
2. create a static IP
3. create a service associate with this IP and add DNS name annotation
4. delete the svc and the tag persists on the ip
#### Environment:

- Kubernetes version (use `kubectl version`): 1.22.2
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): ubuntu-18
- Kernel (e.g. `uname -a`): azure-1059
- Install tools: AKS
- Network plugin and version (if this is a network-related bug):N/A
- Others:N/A

**Comment by feiskyer** [comment]
Thanks for reporting the issue. Though other tags have been removed for BYO PIP scenario, but `kubernetes-dns-label-service` is a  special one because it would also change the configuration public IP address (while all others are only changing `tags` property).

To keep tracking the dns configuration of a PIP, I think this one is still required. or else it may be changed to a different dns later by a new service and then existing clients using old dns would be broken.

so, @Shuanglu is it possible to setup the DNS for the BYO PIP before using it in k8s cluster? In this way, you don't need to set dns name annotation on service specs.

**Comment by Shuanglu** [comment]
> Thanks for reporting the issue. Though other tags have been removed for BYO PIP scenario, but `kubernetes-dns-label-service` is a special one because it would also change the configuration public IP address (while all others are only changing `tags` property).
> 
> To keep tracking the dns configuration of a PIP, I think this one is still required. or else it may be changed to a different dns later by a new service and then existing clients using old dns would be broken.
> 
> so, @Shuanglu is it possible to setup the DNS for the BYO PIP before using it in k8s cluster? In this way, you don't need to set dns name annotation on service specs.

Thanks for the explanation. Maybe it's better to directly mention that there might be conflict 'tag' on the BYO PIP when we return the error? Most of users would check if they have existing service using the DNS instead of checking the tags according to the error message  
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_loadbalancer.go#L1161

**Comment by feiskyer** [comment]
@nilo19 do we still have this issue?

**Comment by nilo19** [comment]
I think so. I don't touch this because we haven't drawn a conclusion if it's needed or not, based on the previous conversation.
