### ISSUE TITLE
Does it support EnableMultipleStandardLoadBalancers now on aks

### ISSUE THREAD

**Issue by veezhang** [kubernetes-sigs/cloud-provider-azure#908]
Does it support EnableMultipleStandardLoadBalancers now on aks?
I found that there only support 8 Private Link Server per Load Balance(`kubernetes-internal`).
But I want to add more Private Link Server per aks.

**Comment by feiskyer** [comment]
Not supported yet

**Comment by veezhang** [comment]
Is it supported now? If not, are there any plans?

**Comment by hofmannma** [comment]
same issue here.... need to support more private link services for AKS than 8.
