### ISSUE TITLE
Static IP is deleted when service is deleted

### ISSUE THREAD

**Issue by PSanetra** [kubernetes-sigs/cloud-provider-azure#914]
#### What happened:
We had a service with a static `loadBalancerIP`. The ip resource was located in a special resource group using the annotation `service.beta.kubernetes.io/azure-load-balancer-resource-group`.

After deleting the service temporarily, the cloud provider deleted the ip resource although it was not created by the provider but instead via terraform.

#### What you expected to happen:
The ip should not be deleted by the provider if the provider did not create the resource.

#### How to reproduce it (as minimally and precisely as possible):

1. Create static ip resource via Azure portal in separate resource group
2. Create Service with loadBalancerIP and `service.beta.kubernetes.io/azure-load-balancer-resource-group` annotation
3. Delete service again
4. ip resource is now deleted

#### Environment:

- Kubernetes version: v1.20.5
- Cloud provider or hardware configuration: AKS

**Comment by feiskyer** [comment]
Thanks for reporting the issue. The [fix](https://github.com/kubernetes/kubernetes/pull/100691) has been included in 1.20.6+, 1.21.1+ or >=1.22.0. Could you upgrade the cluster to newer versions?

And please notice that if you are using versions 1.20.0-1.20.5, or have used these versions with BYO public IP, you also need to remove Tags (service, kubernetes-cluster-name) from BYO public IP even if the cluster has been upgraded to 1.20.6+.

**Comment by PSanetra** [comment]
@feiskyer thank you. Removing the tag has solved our issue.
