### ISSUE TITLE
Feature: add support for loadBalancerClass

### ISSUE THREAD

**Issue by feiskyer** [kubernetes-sigs/cloud-provider-azure#917]
#### What would you like to be added:

Add support for https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class:

> FEATURE STATE: Kubernetes v1.22 [beta]

> spec.loadBalancerClass enables you to use a load balancer implementation other than the cloud provider default. This feature is available from v1.21, you must enable the ServiceLoadBalancerClass feature gate to use this field in v1.21, and the feature gate is enabled by default from v1.22 onwards. By default, spec.loadBalancerClass is nil and a LoadBalancer type of Service uses the cloud provider's default load balancer implementation if the cluster is configured with a cloud provider using the --cloud-provider component flag. If spec.loadBalancerClass is specified, it is assumed that a load balancer implementation that matches the specified class is watching for Services. Any default load balancer implementation (for example, the one provided by the cloud provider) will ignore Services that have this field set. spec.loadBalancerClass can be set on a Service of type LoadBalancer only. Once set, it cannot be changed. The value of spec.loadBalancerClass must be a label-style identifier, with an optional prefix such as "internal-vip" or "example.com/internal-vip". Unprefixed names are reserved for end-users.

**Comment by nilo19** [comment]
What classes do we support?

**Comment by feiskyer** [comment]
At least the default one when `loadBalancerClass` is not specified and skip when it is set to other values.

For non-default ones, we need to validate what sets of LoadBalancers could be worked together, including different SKUs (Basic LB, Standard LB, Gateway LB, Global LB) and different nodepools (VM IP config, VM IP address, Pod IP address).
