### ISSUE TITLE
Deprecate aks-engine e2e test

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#919]
#### What would you like to be added:

Deprecate aks-engine based e2e test and migrate to use capz.

**Comment by bridgetkromhout** [comment]
Currently in progress.

**Comment by bridgetkromhout** [comment]
Waiting for CAPZ team to refactor: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1994#issuecomment-1098252590

**Comment by bridgetkromhout** [comment]
@lzhecheng Please take a look at https://github.com/Azure/aks-engine/issues/4874 - thanks.

**Comment by lzhecheng** [comment]
I will start adding templates into cloud-provider-azure repo. Here is one of the prerequisite issue.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2299

**Comment by lzhecheng** [comment]
An issue on test-infra repo
https://github.com/kubernetes/test-infra/issues/24957

**Comment by jackfrancis** [comment]
Great to see this woork @lzhecheng!

Because "Basic" LoadBalancer is not supported in capz, will we keep that AKS Engine test in cloud-provider-azure indefinitely?

cc @CecileRobertMichon @bridgetkromhout @ritazh

**Comment by lzhecheng** [comment]
@jackfrancis as far as I know, basic lb and autoscaling will be verified in downstream tests on aks clusters.

**Comment by lzhecheng** [comment]
> @lzhecheng Thanks for confirming. May I remove this (and other similar) test jobs?:
> 
> * https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-presubmit-1.23.yaml#L25

I have no strong opinion. I didn't remove these tests because there's no harm to keep them and aks clustesr jobs are not ready yet. Gradually, they will be deleted with the whole release-branch.

**Comment by bridgetkromhout** [comment]
>  basic lb and autoscaling will be verified in downstream tests on aks clusters.

@lzhecheng  Do we need to open an issue to make sure this happens? Do we know who is going to prepare those tests? Thanks.

**Comment by lzhecheng** [comment]
> > basic lb and autoscaling will be verified in downstream tests on aks clusters.
> 
> @lzhecheng Do we need to open an issue to make sure this happens? Do we know who is going to prepare those tests? Thanks.

I have created one #1929 and I think @mainred will take the task.
