### ISSUE TITLE
Help text of `--feature-gates` flag is wrong

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/cloud-provider-azure#943]
#### What happened:
The help text of `--feature-gates` flag lists irrelevant feature gates and does not list the relevant ones - like `IPv6DualStack`.

#### What you expected to happen:
The help text of `--feature-gates` flag to list only feature gates that are relevant for the azure CCM.

#### How to reproduce it (as minimally and precisely as possible):
```
$ docker run mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.23.0 --help

      --feature-gates mapStringBool              A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                                                 APIListChunking=true|false (BETA - default=true)
                                                 APIPriorityAndFairness=true|false (BETA - default=true)
                                                 APIResponseCompression=true|false (BETA - default=true)
                                                 APIServerIdentity=true|false (ALPHA - default=false)
                                                 APIServerTracing=true|false (ALPHA - default=false)
                                                 AllAlpha=true|false (ALPHA - default=false)
                                                 AllBeta=true|false (BETA - default=false)
                                                 ControllerManagerLeaderMigration=true|false (BETA - default=true)
                                                 CustomResourceValidationExpressions=true|false (ALPHA - default=false)
                                                 EfficientWatchResumption=true|false (BETA - default=true)
                                                 OpenAPIEnums=true|false (ALPHA - default=false)
                                                 OpenAPIV3=true|false (ALPHA - default=false)
                                                 RemainingItemCount=true|false (BETA - default=true)
                                                 RemoveSelfLink=true|false (BETA - default=true)
                                                 ServerSideFieldValidation=true|false (ALPHA - default=false)
                                                 StorageVersionAPI=true|false (ALPHA - default=false)
                                                 StorageVersionHash=true|false (BETA - default=true)
```

#### Environment:

- Kubernetes version (use `kubectl version`): v1.23.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nilo19** [comment]
@ialidzhikov it has been gradurated and removed since v1.23.0. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#ipv4ipv6-dual-stack-networking-graduates-to-ga

**Comment by ialidzhikov** [comment]
Still the `--help` output for feature gates is quite wrong and lists kube-apiserver feature gates that have no handling in the azure CCM code. In the `-help` output I would like to see only feature gates that are supported by azure CCM.

/reopen

**Comment by nilo19** [comment]
We don't have dedicated feature gates and this option is not managed by us as well.

**Comment by ialidzhikov** [comment]
> We don't have dedicated feature gates and this option is not managed by us as well.

Instead of reusing the FeatureGates from the apiserver pkg, you can create your own FeatureGate and add only the cloud-provider feature gates (not sure whether there is already such interface like `SetupCurrentKubernetesSpecificFeatureGates`  https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/controller-manager/pkg/features/kube_features.go for CCM features specific feature gates). But I haven't tried this myself to be honest.

**Comment by nilo19** [comment]
@ialidzhikov we control the feature by config file and I don't think the feature gate is needed.

**Comment by ialidzhikov** [comment]
You say that `--feature-gates` flag is not needed at all?

**Comment by nilo19** [comment]
I mean we don't need dedicated feature gates to control the features of the cloud provider.
