### ISSUE TITLE
Add more parameters support to annotations in order to customize probe behavior. 

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes-sigs/cloud-provider-azure#948]
#### What would you like to be added:

Add  numOfProbe and probeInterval annotation to supported annotation list in order to customize probe behavior. 

#### Why is this needed:
Customer may want to customize health probe behavior rather than using default configuration when they are running mission critical workloads.

**Comment by feiskyer** [comment]
Reopen because we still need to do the cherry-picking.

**Comment by MartinForReal** [comment]
related: #949
