### ISSUE TITLE
Refine hack/update-mock-clients.sh

### ISSUE THREAD

**Issue by nilo19** [kubernetes-sigs/cloud-provider-azure#951]
#### What happened:

There are two kinds of problems in `hack/update-mock-clients.sh`:
1. the local source path will show up in the code, e.g., 
```
// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/pomelo/Documents/go/src/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/deploymentclient/interface.go
```
2. many unnecessary changes about punctuation due to different versions of mockgen binary.

I thinks it would be better if the mockgen is performed from a container.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by feiskyer** [comment]
> I thinks it would be better if the mockgen is performed from a container.

What about installing a fixed version inside "hack/update-mock-clients.sh" script? (so that it could be run on MacOS/WSL without docker)

**Comment by MartinForReal** [comment]
Source Path is hard to change if we don't use container. 
https://github.com/golang/mock/blob/aba2ff9a6844d5e3289e8472d3217d5b3090f083/mockgen/mockgen.go#L695

https://github.com/golang/mock/blob/aba2ff9a6844d5e3289e8472d3217d5b3090f083/mockgen/parse.go#L620-L642

How about adding an extra step in ci process to validate whether stub files are up to date?

**Comment by MartinForReal** [comment]
How about using relative path instead?

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/bb44e05c22914dddb2009871ea79b5e7577553c6/hack/update-mock-clients.sh#L20

Value of Source would be ```./pkg/azureclients/armclient/interface.go ```

**Comment by MartinForReal** [comment]
related #1104

**Comment by MartinForReal** [comment]
updated by @lzhecheng  and close this issue.
